import test from "node:test";
import assert from "node:assert/strict";
import { frameCells, toSolidity, LOCAL, BLOCK, THICK, DAY_CELLS, TOTAL_CELLS } from "../frame-geometry.mjs";

test("376 unique cells, all in the two rings outside the block", () => {
  const cells = frameCells();
  assert.equal(cells.length, TOTAL_CELLS);
  assert.equal(cells.length, 376);
  const seen = new Set();
  for (const [x, y] of cells) {
    const ring = Math.min(x, y, LOCAL - 1 - x, LOCAL - 1 - y);
    assert.ok(ring < THICK, `cell ${x},${y} is inside the block`);
    assert.ok(x >= 0 && x < LOCAL && y >= 0 && y < LOCAL, `off grid ${x},${y}`);
    const k = `${x},${y}`;
    assert.ok(!seen.has(k), `duplicate ${k}`);
    seen.add(k);
  }
});

test("the block interior is never touched, so the quiet zone stays clear", () => {
  const occupied = new Set(frameCells().map(([x, y]) => `${x},${y}`));
  for (let y = THICK; y < THICK + BLOCK; y++)
    for (let x = THICK; x < THICK + BLOCK; x++)
      assert.ok(!occupied.has(`${x},${y}`), `frame intrudes into the block at ${x},${y}`);
});

test("fill starts at the top and both arms descend together", () => {
  const cells = frameCells();
  const mid = (LOCAL - 1) / 2;
  assert.equal(cells[0][1], 0, "first cell is on the top row");
  assert.ok(Math.abs(cells[0][0] - mid) <= 1, "first cell is at the top centre");
  // the two arms should stay within a cell or so of each other all the way round
  let left = 0, right = 0;
  for (const [x] of cells.slice(0, DAY_CELLS)) (x < mid ? left++ : right++);
  assert.ok(Math.abs(left - right) < 20, `arms badly unbalanced: ${left} vs ${right}`);
});

test("the surplus that seals on wholeness sits at the bottom", () => {
  const cells = frameCells();
  const surplus = cells.slice(DAY_CELLS);
  assert.equal(surplus.length, 11);
  for (const [, y] of surplus) assert.ok(y > LOCAL / 2, "sealing cells should be low on the grid");
});

test("Solidity output carries the header, constants and two bytes per cell", () => {
  const sol = toSolidity(frameCells());
  assert.match(sol, /GENERATED by tools\/frame-geometry.mjs/);
  assert.match(sol, /uint256 constant CELL_COUNT = 376;/);
  assert.match(sol, /uint256 constant DAY_CELLS = 365;/);
  assert.equal(sol.match(/hex"([0-9a-f]+)"/)[1].length, 376 * 2 * 2);
});

test("generation is deterministic", () => {
  assert.deepEqual(frameCells(), frameCells());
});
