import test from "node:test";
import assert from "node:assert/strict";
import { frameCells, frameRows, toSolidity, unitsFor, LOCAL, BLOCK, THICK, QUIET, DAY_CELLS, TOTAL_CELLS } from "../frame-geometry.mjs";

test("376 unique cells, all in the two rings outside the block", () => {
  const cells = frameCells();
  assert.equal(cells.length, TOTAL_CELLS);
  assert.equal(cells.length, 376);
  const seen = new Set();
  for (const [x, y] of cells) {
    const ring = Math.min(x, y, LOCAL - 1 - x, LOCAL - 1 - y);
    assert.ok(ring < THICK, `cell ${x},${y} is inside the block`);
    assert.ok(x >= 0 && x < LOCAL && y >= 0 && y < LOCAL, `off grid ${x},${y}`);
    const k = `${x},${y}`;
    assert.ok(!seen.has(k), `duplicate ${k}`);
    seen.add(k);
  }
});

test("the block interior is never touched, so the quiet zone stays clear", () => {
  const occupied = new Set(frameCells().map(([x, y]) => `${x},${y}`));
  for (let y = THICK; y < THICK + BLOCK; y++)
    for (let x = THICK; x < THICK + BLOCK; x++)
      assert.ok(!occupied.has(`${x},${y}`), `frame intrudes into the block at ${x},${y}`);
});

test("fill starts at the top and both arms descend together", () => {
  const cells = frameCells();
  const mid = (LOCAL - 1) / 2;
  assert.equal(cells[0][1], 0, "first cell is on the top row");
  assert.ok(Math.abs(cells[0][0] - mid) <= 1, "first cell is at the top centre");
  // the two arms should stay within a cell or so of each other all the way round
  let left = 0, right = 0;
  for (const [x] of cells.slice(0, DAY_CELLS)) (x < mid ? left++ : right++);
  assert.ok(Math.abs(left - right) < 20, `arms badly unbalanced: ${left} vs ${right}`);
});

test("the surplus that seals on wholeness sits at the bottom", () => {
  const cells = frameCells();
  const surplus = cells.slice(DAY_CELLS);
  assert.equal(surplus.length, 11);
  for (const [, y] of surplus) assert.ok(y > LOCAL / 2, "sealing cells should be low on the grid");
});

test("Solidity output carries the header, constants and two bytes per cell", () => {
  const sol = toSolidity(frameCells(), unitsFor(37));
  assert.match(sol, /GENERATED by tools\/frame-geometry.mjs/);
  assert.match(sol, /uint256 constant CELL_COUNT = 376;/);
  assert.match(sol, /uint256 constant DAY_CELLS = 365;/);
  assert.equal(sol.match(/hex"([0-9a-f]+)"/)[1].length, 376 * 2 * 2);
  // The unit system reaches Solidity, or the contract draws the frame at the
  // wrong pitch while every count still looks right.
  assert.match(sol, /uint256 constant CELL_UNITS = 1;/);
  assert.match(sol, /uint256 constant MODULE_UNITS = 1;/);
  assert.match(sol, /uint256 constant BLOCK_MODULES = 45;/);

  const ten = toSolidity(frameCells(), unitsFor(57));
  assert.match(ten, /uint256 constant CELL_UNITS = 13;/);
  assert.match(ten, /uint256 constant MODULE_UNITS = 9;/);
  assert.match(ten, /uint256 constant BLOCK_MODULES = 65;/);
});

test("generation is deterministic", () => {
  assert.deepEqual(frameCells(), frameCells());
});

test("the row bitmap holds exactly the cells the list does", () => {
  const cells = frameCells();
  const rows = frameRows(cells);
  assert.equal(rows.length, LOCAL);

  // Same cells, counted two ways.
  const bits = rows.reduce((n, r) => n + [...r.toString(2)].filter(c => c === "1").length, 0);
  assert.equal(bits, cells.length, "bitmap and list disagree on how many cells there are");

  for (const [x, y] of cells)
    assert.equal((rows[y] >> BigInt(LOCAL - 1 - x)) & 1n, 1n, `cell ${x},${y} missing from the bitmap`);

  // Nothing set outside the 49 columns that exist.
  for (const r of rows) assert.ok(r < (1n << BigInt(LOCAL)), "a bit is set off the grid");
});

// The unit system: a frame cell stops being a QR module above version 5, and
// the whole point is that the ratio is EXACT. A rounded ratio would put the
// frame a fraction of a module out of true on every side, which is the bug
// these tests exist to make impossible.

test("version 5 reduces to one unit each, so nothing moves", () => {
  const u = unitsFor(37);
  assert.equal(u.blockModules, 45);
  assert.equal(u.cell, 1);
  assert.equal(u.module, 1);
});

test("version 10 is exactly 13 units to a cell and 9 to a module", () => {
  const u = unitsFor(57);
  assert.equal(u.blockModules, 65);
  assert.equal(u.cell, 13);
  assert.equal(u.module, 9);
  // The identity the whole design rests on: the block is the same width
  // measured either way, with no remainder.
  assert.equal(BLOCK * u.cell, u.blockModules * u.module);
  assert.equal(BLOCK * u.cell, 585);
});

test("the block spans a whole number of units at every QR version", () => {
  for (let v = 1; v <= 40; v++) {
    const u = unitsFor(17 + 4 * v);
    assert.equal(BLOCK * u.cell, u.blockModules * u.module, `version ${v} does not divide`);
    assert.ok(Number.isInteger(u.cell) && Number.isInteger(u.module), `version ${v} is fractional`);
  }
});

test("the day frame is 376 cells whatever the version does", () => {
  // TOTAL_CELLS is a property of BLOCK, not of the code inside it. If a
  // version raise ever changes this, the 365 days no longer fit the frame.
  for (const modules of [37, 57]) {
    unitsFor(modules);
    assert.equal(TOTAL_CELLS, 376);
    assert.equal(frameCells().length, 376);
  }
});

test("the quiet zone is four modules and is counted on both sides", () => {
  assert.equal(QUIET, 4);
  assert.equal(unitsFor(37).blockModules, 37 + 2 * QUIET);
});
