// The two byte strings the contracts need: a per-token code bitmap and the one
// shared heart mask. Nothing downstream can be built or tested without them.
import test from "node:test";
import assert from "node:assert/strict";
import { tokenBitmap, SIZE, BYTES, HEX_CHARS } from "../token-bitmap.mjs";
import { heartMaskBytes, toSolidity } from "../heart-mask.mjs";
import { unpackModules, bestOfAllMasks, payloadFor } from "../qart.mjs";
import { heartTarget } from "../heart-target.mjs";
import { renderModules, scanResult } from "./helpers/decode.mjs";

test("the hex round-trips to the same modules the solver produced", () => {
  const r = tokenBitmap("example.com", 1);
  // Token 1's best-matching mask is also robust, so the gate does not move it
  // and the two selectors agree here. That is asserted rather than assumed --
  // if it ever stops being true, every generated fixture keyed to token 1 moves
  // with it, and this is the test that says so first.
  const best = bestOfAllMasks(payloadFor("example.com", 1));
  assert.equal(r.rejected, 0, "token 1 is expected to need no gate rejection");
  const bytes = Uint8Array.from(Buffer.from(r.hex, "hex"));
  assert.deepEqual(Array.from(unpackModules(bytes, SIZE)), Array.from(best.modules));
});

test("the hex is exactly the width the contract expects", () => {
  const r = tokenBitmap("example.com", 1);
  assert.equal(r.size, SIZE);
  assert.equal(r.bytes, BYTES);
  assert.equal(r.hex.length, HEX_CHARS);
  assert.equal(HEX_CHARS, 344);
  assert.match(r.hex, /^[0-9a-f]+$/, "hex must be lower case and unprefixed");
  assert.equal(BYTES, Math.ceil(SIZE * SIZE / 8));
});

test("two token ids produce different bitmaps", () => {
  assert.notEqual(tokenBitmap("example.com", 1).hex, tokenBitmap("example.com", 2).hex);
});

test("a bitmap still scans to its own destination after the round trip", () => {
  // The bitmap is what the contract will draw from. If it does not scan after
  // packing and unpacking, everything downstream is drawing a broken code.
  for (const id of [1, 2, 365]) {
    const r = tokenBitmap("example.com", id);
    const modules = unpackModules(Uint8Array.from(Buffer.from(r.hex, "hex")), SIZE);
    const got = scanResult(renderModules(modules, SIZE));
    assert.ok(got.ok, `token ${id}: ${got.why}`);
    assert.equal(got.destination, payloadFor("example.com", id).slice(0, -1));
  }
});

test("the heart mask is one shared constant, identical for every token", () => {
  // Storing the target per token would add 172 bytes to every mint for no
  // information: only the noise differs between tokens, never the heart.
  const a = heartMaskBytes();
  const b = heartMaskBytes();
  assert.deepEqual(Array.from(a), Array.from(b));
  assert.equal(a.length, BYTES);
  const { want } = heartTarget(SIZE);
  assert.deepEqual(Array.from(unpackModules(a, SIZE)), Array.from(want));
});

test("the generated Solidity carries the header, constants and 172 bytes", () => {
  const sol = toSolidity();
  assert.match(sol, /GENERATED by tools\/heart-mask\.mjs/);
  assert.match(sol, /library HeartMask/);
  assert.match(sol, new RegExp(`SIZE = ${SIZE}`));
  const hex = sol.match(/hex"([0-9a-f]+)"/)[1];
  assert.equal(hex.length, HEX_CHARS);
});
