// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test} from "forge-std/Test.sol";
import {FrameRenderer} from "../src/render/FrameRenderer.sol";
import {FrameGeometry} from "../src/render/FrameGeometry.sol";
import {TokenView} from "../src/render/TokenView.sol";
import {PathParser} from "./helpers/PathParser.sol";

/// @notice Exposes the library externally so `forge test --gas-report` can bill it.
contract FrameRendererHarness {
    function paths(TokenView memory v, string memory colour, string memory ghostFill)
        external
        pure
        returns (string memory)
    {
        return FrameRenderer.paths(v, colour, ghostFill);
    }
}

contract FrameRendererTest is Test {
    string constant COLOUR = "#c8102e";
    string constant GHOST = "#f4eef0";

    FrameRendererHarness harness;

    function setUp() public {
        harness = new FrameRendererHarness();
    }

    /// @dev Only the fields the frame reads. Everything else stays at zero.
    function _view(uint32 level) internal pure returns (TokenView memory v) {
        v.level = level;
        v.code = new bytes(172);
    }

    function _out(uint32 level) internal view returns (string memory) {
        return harness.paths(_view(level), COLOUR, GHOST);
    }

    /// @dev Pulls the d attribute of the path with the given fill, or "" if that
    /// path was not emitted at all.
    function _pathFor(string memory out, string memory fill) internal pure returns (string memory) {
        string[] memory parts = vm.split(out, "\"");
        for (uint256 i = 1; i + 2 < parts.length; i += 4) {
            if (keccak256(bytes(parts[i])) == keccak256(bytes(fill))) return parts[i + 2];
        }
        return "";
    }

    // ---------------------------------------------------------------------
    // Expected path data, generated by `node tools/frame-path-fixture.mjs`.
    // Re-run that and paste the output back here if the fill order, the ring
    // rule or the path format ever changes.
    // ---------------------------------------------------------------------

    // level 0, no rings: nothing earned, so the whole frame is ghost.
    function _newGhostD() internal pure returns (string memory) {
        return
        "M1 1h49v1h-49zM1 2h49v1h-49zM1 3h2v1h-2zM48 3h2v1h-2zM1 4h2v1h-2zM48 4h2v1h-2zM1 5h2v1h-2z"
        "M48 5h2v1h-2zM1 6h2v1h-2zM48 6h2v1h-2zM1 7h2v1h-2zM48 7h2v1h-2zM1 8h2v1h-2zM48 8h2v1h-2zM1"
        " 9h2v1h-2zM48 9h2v1h-2zM1 10h2v1h-2zM48 10h2v1h-2zM1 11h2v1h-2zM48 11h2v1h-2zM1 12h2v1h-2z"
        "M48 12h2v1h-2zM1 13h2v1h-2zM48 13h2v1h-2zM1 14h2v1h-2zM48 14h2v1h-2zM1 15h2v1h-2zM48 15h2v"
        "1h-2zM1 16h2v1h-2zM48 16h2v1h-2zM1 17h2v1h-2zM48 17h2v1h-2zM1 18h2v1h-2zM48 18h2v1h-2zM1 1"
        "9h2v1h-2zM48 19h2v1h-2zM1 20h2v1h-2zM48 20h2v1h-2zM1 21h2v1h-2zM48 21h2v1h-2zM1 22h2v1h-2z"
        "M48 22h2v1h-2zM1 23h2v1h-2zM48 23h2v1h-2zM1 24h2v1h-2zM48 24h2v1h-2zM1 25h2v1h-2zM48 25h2v"
        "1h-2zM1 26h2v1h-2zM48 26h2v1h-2zM1 27h2v1h-2zM48 27h2v1h-2zM1 28h2v1h-2zM48 28h2v1h-2zM1 2"
        "9h2v1h-2zM48 29h2v1h-2zM1 30h2v1h-2zM48 30h2v1h-2zM1 31h2v1h-2zM48 31h2v1h-2zM1 32h2v1h-2z"
        "M48 32h2v1h-2zM1 33h2v1h-2zM48 33h2v1h-2zM1 34h2v1h-2zM48 34h2v1h-2zM1 35h2v1h-2zM48 35h2v"
        "1h-2zM1 36h2v1h-2zM48 36h2v1h-2zM1 37h2v1h-2zM48 37h2v1h-2zM1 38h2v1h-2zM48 38h2v1h-2zM1 3"
        "9h2v1h-2zM48 39h2v1h-2zM1 40h2v1h-2zM48 40h2v1h-2zM1 41h2v1h-2zM48 41h2v1h-2zM1 42h2v1h-2z"
        "M48 42h2v1h-2zM1 43h2v1h-2zM48 43h2v1h-2zM1 44h2v1h-2zM48 44h2v1h-2zM1 45h2v1h-2zM48 45h2v"
        "1h-2zM1 46h2v1h-2zM48 46h2v1h-2zM1 47h2v1h-2zM48 47h2v1h-2zM1 48h49v1h-49zM1 49h49v1h-49z";
    }

    // level 200, no rings: part lit, the rest still ghost.
    function _midGhostD() internal pure returns (string memory) {
        return
        "M2 28h1v1h-1zM48 28h1v1h-1zM1 29h2v1h-2zM48 29h2v1h-2zM1 30h2v1h-2zM48 30h2v1h-2zM1 31h2v1"
        "h-2zM48 31h2v1h-2zM1 32h2v1h-2zM48 32h2v1h-2zM1 33h2v1h-2zM48 33h2v1h-2zM1 34h2v1h-2zM48 3"
        "4h2v1h-2zM1 35h2v1h-2zM48 35h2v1h-2zM1 36h2v1h-2zM48 36h2v1h-2zM1 37h2v1h-2zM48 37h2v1h-2z"
        "M1 38h2v1h-2zM48 38h2v1h-2zM1 39h2v1h-2zM48 39h2v1h-2zM1 40h2v1h-2zM48 40h2v1h-2zM1 41h2v1"
        "h-2zM48 41h2v1h-2zM1 42h2v1h-2zM48 42h2v1h-2zM1 43h2v1h-2zM48 43h2v1h-2zM1 44h2v1h-2zM48 4"
        "4h2v1h-2zM1 45h2v1h-2zM48 45h2v1h-2zM1 46h2v1h-2zM48 46h2v1h-2zM1 47h2v1h-2zM48 47h2v1h-2z"
        "M1 48h49v1h-49zM1 49h49v1h-49z";
    }

    function _midFrameD() internal pure returns (string memory) {
        return
        "M1 1h49v1h-49zM1 2h49v1h-49zM1 3h2v1h-2zM48 3h2v1h-2zM1 4h2v1h-2zM48 4h2v1h-2zM1 5h2v1h-2z"
        "M48 5h2v1h-2zM1 6h2v1h-2zM48 6h2v1h-2zM1 7h2v1h-2zM48 7h2v1h-2zM1 8h2v1h-2zM48 8h2v1h-2zM1"
        " 9h2v1h-2zM48 9h2v1h-2zM1 10h2v1h-2zM48 10h2v1h-2zM1 11h2v1h-2zM48 11h2v1h-2zM1 12h2v1h-2z"
        "M48 12h2v1h-2zM1 13h2v1h-2zM48 13h2v1h-2zM1 14h2v1h-2zM48 14h2v1h-2zM1 15h2v1h-2zM48 15h2v"
        "1h-2zM1 16h2v1h-2zM48 16h2v1h-2zM1 17h2v1h-2zM48 17h2v1h-2zM1 18h2v1h-2zM48 18h2v1h-2zM1 1"
        "9h2v1h-2zM48 19h2v1h-2zM1 20h2v1h-2zM48 20h2v1h-2zM1 21h2v1h-2zM48 21h2v1h-2zM1 22h2v1h-2z"
        "M48 22h2v1h-2zM1 23h2v1h-2zM48 23h2v1h-2zM1 24h2v1h-2zM48 24h2v1h-2zM1 25h2v1h-2zM48 25h2v"
        "1h-2zM1 26h2v1h-2zM48 26h2v1h-2zM1 27h2v1h-2zM48 27h2v1h-2zM1 28h1v1h-1zM49 28h1v1h-1z";
    }

    // level 365, one ring: whole, so every cell lights and the ghost disappears.
    function _wholeFrameD() internal pure returns (string memory) {
        return
        "M0 0h53v1h-53zM0 1h1v1h-1zM52 1h1v1h-1zM0 2h1v1h-1zM2 2h49v1h-49zM52 2h1v1h-1zM0 3h1v1h-1z"
        "M2 3h49v1h-49zM52 3h1v1h-1zM0 4h1v1h-1zM2 4h2v1h-2zM49 4h2v1h-2zM52 4h1v1h-1zM0 5h1v1h-1zM"
        "2 5h2v1h-2zM49 5h2v1h-2zM52 5h1v1h-1zM0 6h1v1h-1zM2 6h2v1h-2zM49 6h2v1h-2zM52 6h1v1h-1zM0 "
        "7h1v1h-1zM2 7h2v1h-2zM49 7h2v1h-2zM52 7h1v1h-1zM0 8h1v1h-1zM2 8h2v1h-2zM49 8h2v1h-2zM52 8h"
        "1v1h-1zM0 9h1v1h-1zM2 9h2v1h-2zM49 9h2v1h-2zM52 9h1v1h-1zM0 10h1v1h-1zM2 10h2v1h-2zM49 10h"
        "2v1h-2zM52 10h1v1h-1zM0 11h1v1h-1zM2 11h2v1h-2zM49 11h2v1h-2zM52 11h1v1h-1zM0 12h1v1h-1zM2"
        " 12h2v1h-2zM49 12h2v1h-2zM52 12h1v1h-1zM0 13h1v1h-1zM2 13h2v1h-2zM49 13h2v1h-2zM52 13h1v1h"
        "-1zM0 14h1v1h-1zM2 14h2v1h-2zM49 14h2v1h-2zM52 14h1v1h-1zM0 15h1v1h-1zM2 15h2v1h-2zM49 15h"
        "2v1h-2zM52 15h1v1h-1zM0 16h1v1h-1zM2 16h2v1h-2zM49 16h2v1h-2zM52 16h1v1h-1zM0 17h1v1h-1zM2"
        " 17h2v1h-2zM49 17h2v1h-2zM52 17h1v1h-1zM0 18h1v1h-1zM2 18h2v1h-2zM49 18h2v1h-2zM52 18h1v1h"
        "-1zM0 19h1v1h-1zM2 19h2v1h-2zM49 19h2v1h-2zM52 19h1v1h-1zM0 20h1v1h-1zM2 20h2v1h-2zM49 20h"
        "2v1h-2zM52 20h1v1h-1zM0 21h1v1h-1zM2 21h2v1h-2zM49 21h2v1h-2zM52 21h1v1h-1zM0 22h1v1h-1zM2"
        " 22h2v1h-2zM49 22h2v1h-2zM52 22h1v1h-1zM0 23h1v1h-1zM2 23h2v1h-2zM49 23h2v1h-2zM52 23h1v1h"
        "-1zM0 24h1v1h-1zM2 24h2v1h-2zM49 24h2v1h-2zM52 24h1v1h-1zM0 25h1v1h-1zM2 25h2v1h-2zM49 25h"
        "2v1h-2zM52 25h1v1h-1zM0 26h1v1h-1zM2 26h2v1h-2zM49 26h2v1h-2zM52 26h1v1h-1zM0 27h1v1h-1zM2"
        " 27h2v1h-2zM49 27h2v1h-2zM52 27h1v1h-1zM0 28h1v1h-1zM2 28h2v1h-2zM49 28h2v1h-2zM52 28h1v1h"
        "-1zM0 29h1v1h-1zM2 29h2v1h-2zM49 29h2v1h-2zM52 29h1v1h-1zM0 30h1v1h-1zM2 30h2v1h-2zM49 30h"
        "2v1h-2zM52 30h1v1h-1zM0 31h1v1h-1zM2 31h2v1h-2zM49 31h2v1h-2zM52 31h1v1h-1zM0 32h1v1h-1zM2"
        " 32h2v1h-2zM49 32h2v1h-2zM52 32h1v1h-1zM0 33h1v1h-1zM2 33h2v1h-2zM49 33h2v1h-2zM52 33h1v1h"
        "-1zM0 34h1v1h-1zM2 34h2v1h-2zM49 34h2v1h-2zM52 34h1v1h-1zM0 35h1v1h-1zM2 35h2v1h-2zM49 35h"
        "2v1h-2zM52 35h1v1h-1zM0 36h1v1h-1zM2 36h2v1h-2zM49 36h2v1h-2zM52 36h1v1h-1zM0 37h1v1h-1zM2"
        " 37h2v1h-2zM49 37h2v1h-2zM52 37h1v1h-1zM0 38h1v1h-1zM2 38h2v1h-2zM49 38h2v1h-2zM52 38h1v1h"
        "-1zM0 39h1v1h-1zM2 39h2v1h-2zM49 39h2v1h-2zM52 39h1v1h-1zM0 40h1v1h-1zM2 40h2v1h-2zM49 40h"
        "2v1h-2zM52 40h1v1h-1zM0 41h1v1h-1zM2 41h2v1h-2zM49 41h2v1h-2zM52 41h1v1h-1zM0 42h1v1h-1zM2"
        " 42h2v1h-2zM49 42h2v1h-2zM52 42h1v1h-1zM0 43h1v1h-1zM2 43h2v1h-2zM49 43h2v1h-2zM52 43h1v1h"
        "-1zM0 44h1v1h-1zM2 44h2v1h-2zM49 44h2v1h-2zM52 44h1v1h-1zM0 45h1v1h-1zM2 45h2v1h-2zM49 45h"
        "2v1h-2zM52 45h1v1h-1zM0 46h1v1h-1zM2 46h2v1h-2zM49 46h2v1h-2zM52 46h1v1h-1zM0 47h1v1h-1zM2"
        " 47h2v1h-2zM49 47h2v1h-2zM52 47h1v1h-1zM0 48h1v1h-1zM2 48h2v1h-2zM49 48h2v1h-2zM52 48h1v1h"
        "-1zM0 49h1v1h-1zM2 49h49v1h-49zM52 49h1v1h-1zM0 50h1v1h-1zM2 50h49v1h-49zM52 50h1v1h-1zM0 "
        "51h1v1h-1zM52 51h1v1h-1zM0 52h53v1h-53z";
    }

    // ---------------------------------------------------------------------
    // Canvas and rings
    // ---------------------------------------------------------------------

    function test_theCanvasGrowsTwoCellsPerCompletedYear() public pure {
        assertEq(FrameRenderer.canvas(0), 51, "year zero");
        assertEq(FrameRenderer.canvas(1), 53, "one completed year");
        assertEq(FrameRenderer.canvas(3), 57, "three completed years");
    }

    function test_ringsCountCompletedYears() public pure {
        assertEq(FrameRenderer.rings(0), 0, "day one");
        assertEq(FrameRenderer.rings(364), 0, "a year is not complete at 364 days");
        assertEq(FrameRenderer.rings(365), 1, "one completed year");
        assertEq(FrameRenderer.rings(729), 1, "still one");
        assertEq(FrameRenderer.rings(1095), 3, "three completed years");
    }

    function test_ringsStopGrowingAtTheMeasuredCeiling() public pure {
        // Measured on the reference renderer: the tokenURI crosses the 20,000
        // byte limit at 85 completed years (84 came to 19,932, 85 to 20,044).
        // The cap also keeps a canvas row inside the single word the renderer
        // holds it in: 80 rings make the canvas 211 cells, 107 would make it 265.
        assertEq(FrameRenderer.MAX_RINGS, 80, "the cap is 80 years");
        assertEq(FrameRenderer.rings(365 * 80), 80, "eighty years still counts");
        assertEq(FrameRenderer.rings(365 * 200), 80, "beyond the cap it stops");
        assertEq(FrameRenderer.rings(type(uint32).max), 80, "a runaway clock cannot grow it");
        assertLt(FrameRenderer.canvas(FrameRenderer.MAX_RINGS), 256, "a row still fits one word");
        assertEq(FrameRenderer.canvas(FrameRenderer.MAX_RINGS), 211, "the widest canvas");
    }

    // ---------------------------------------------------------------------
    // What lights, and when
    // ---------------------------------------------------------------------

    function test_oneCellLightsPerCreditedDay() public view {
        assertEq(PathParser.countCells(_pathFor(_out(1), COLOUR)), 1, "day one lights one cell");
        assertEq(PathParser.countCells(_pathFor(_out(200), COLOUR)), 200, "day 200 lights 200");
        assertEq(PathParser.countCells(_pathFor(_out(364), COLOUR)), 364, "day 364 lights 364");
    }

    function test_theGhostHoldsEveryCellNotYetEarned() public view {
        assertEq(
            PathParser.countCells(_pathFor(_out(0), GHOST)),
            FrameGeometry.CELL_COUNT,
            "nothing earned yet, so every cell is ghost"
        );
        assertEq(
            PathParser.countCells(_pathFor(_out(200), GHOST)),
            FrameGeometry.CELL_COUNT - 200,
            "the rest of the frame is still ghost"
        );
    }

    function test_theFrameSealsOnlyWhenTheHeartIsWhole() public view {
        // The 11 surplus cells are the seal. They stay dark through the whole
        // year and close the ring on the day the heart completes.
        assertEq(PathParser.countCells(_pathFor(_out(364), COLOUR)), 364, "still open on day 364");
        assertEq(PathParser.countCells(_pathFor(_out(364), GHOST)), 12, "twelve cells still ghost");

        // Day 365 is also the day the first year ring appears, so the lit path
        // carries the whole frame plus that ring's outline.
        assertEq(
            PathParser.countCells(_pathFor(_out(365), COLOUR)),
            FrameGeometry.CELL_COUNT + _ringCells(1),
            "all 376 light once the heart is whole, plus the first ring"
        );
        assertEq(bytes(_pathFor(_out(365), GHOST)).length, 0, "no ghost path is emitted at all");
    }

    /// @dev Cells in the outlines of the first `count` rings, outermost first.
    function _ringCells(uint256 count) internal pure returns (uint256 n) {
        uint256 c = FrameRenderer.canvas(count);
        for (uint256 k; k < count; ++k) n += 4 * (c - 1 - 2 * k);
    }

    function test_anEmptyPathIsOmittedRatherThanEmitted() public view {
        // An empty <path> element would be pure waste in a budget measured in
        // bytes, and the reference renderer omits it, so this one must too.
        string memory dayOne = _out(0);
        assertEq(vm.split(dayOne, "<path").length, 2, "day zero draws the ghost only");

        string memory whole = _out(365);
        assertEq(vm.split(whole, "<path").length, 2, "a whole frame draws the lit path only");
    }

    // ---------------------------------------------------------------------
    // Year rings
    // ---------------------------------------------------------------------

    function test_ringsNeverTouchTheFrameOrTheBlock() public view {
        // A ring that overlapped the day frame would make a day unreadable, and
        // one that reached the block would break the scan. The GAP between them
        // is what keeps both safe.
        uint32 level = 365 * 3;
        uint256 canvas = FrameRenderer.canvas(3);
        uint256 frameStart = 3 + FrameRenderer.GAP;
        PathParser.Run[] memory runs = PathParser.parse(_pathFor(_out(level), COLOUR));

        uint256 ringCells;
        for (uint256 i; i < runs.length; ++i) {
            for (uint256 k; k < runs[i].w; ++k) {
                uint256 x = runs[i].x + k;
                uint256 y = runs[i].y;
                uint256 depth = x;
                if (y < depth) depth = y;
                if (canvas - 1 - x < depth) depth = canvas - 1 - x;
                if (canvas - 1 - y < depth) depth = canvas - 1 - y;
                if (depth < 3) {
                    ++ringCells;   // a ring cell: inside the three outermost rings
                } else {
                    assertGe(depth, frameStart, "a lit cell fell in the gap");
                    assertLt(depth, frameStart + FrameGeometry.THICK, "a lit cell fell inside the block");
                }
            }
        }
        assertGt(ringCells, 0, "three completed years should draw rings");
    }

    function test_theWidestCanvasStillRendersAndStaysInBudget() public view {
        // The capped case, 80 completed years. This is the largest image the
        // piece can ever produce, so it is the one that has to stay renderable.
        string memory out = harness.paths(_view(uint32(365 * FrameRenderer.MAX_RINGS)), COLOUR, GHOST);
        assertEq(bytes(_pathFor(out, GHOST)).length, 0, "a whole frame has no ghost left");

        uint256 cells = PathParser.countCells(_pathFor(out, COLOUR));
        assertEq(
            cells,
            FrameGeometry.CELL_COUNT + _ringCells(FrameRenderer.MAX_RINGS),
            "every frame cell and every ring cell is drawn"
        );
        // The reference renderer measured the whole tokenURI at 19,552 bytes here,
        // against a 20,000 limit. The frame's own share has to leave room for the
        // code block, the JSON and the base64 wrapper on top of it.
        assertLt(bytes(out).length, 6000, "the widest frame overruns its share of the budget");
    }

    // ---------------------------------------------------------------------
    // The differential check: this must match the JS reference exactly
    // ---------------------------------------------------------------------

    function test_dayZeroMatchesTheJavascriptReference() public view {
        string memory out = _out(0);
        assertEq(_pathFor(out, GHOST), _newGhostD(), "ghost path differs from the reference");
    }

    function test_aPartYearMatchesTheJavascriptReference() public view {
        string memory out = _out(200);
        assertEq(_pathFor(out, GHOST), _midGhostD(), "ghost path differs from the reference");
        assertEq(_pathFor(out, COLOUR), _midFrameD(), "frame path differs from the reference");
    }

    function test_aWholeHeartWithOneRingMatchesTheJavascriptReference() public view {
        string memory out = _out(365);
        assertEq(_pathFor(out, COLOUR), _wholeFrameD(), "frame path differs from the reference");
    }

    function test_theGhostIsDrawnBeforeTheLitFrame() public view {
        // Fixed so each renderer's pair of paths is adjacent in the assembled
        // image, which is what lets the assembler simply concatenate them.
        string[] memory fields = vm.split(_out(200), "\"");
        assertEq(fields[1], GHOST, "the ghost path comes first");
        assertEq(fields[5], COLOUR, "the lit frame comes second");
    }
}
