// SPDX-License-Identifier: MIT
// GENERATED by tools/identity-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/identity-fixture.mjs example.com
pragma solidity ^0.8.30;

/// @notice One rendered state at four token identities, with the byte length
/// and keccak256 of the tokenURI tools/render-token.mjs produces for each.
///
/// @dev RenderFixture varies STATE at a fixed identity. This varies IDENTITY at
/// a fixed state, which is the axis that file cannot cover: every case there
/// shares one bitmap, and a bitmap encodes its own token's url.
///
/// State held constant across all four: level 365, streak 400,
/// lastDay 1000, today 1000, no Marks, live.
library IdentityFixture {
    struct Case {
        uint256 tokenId;
        uint32 mintDay;
        uint256 bytesLen;
        bytes32 hash;
        bytes code;
        string label;
    }

    uint256 internal constant COUNT = 4;

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
        c[i++] = Case(1, 900, 14689, 0x450a6a62480d8ea3c20447db8b55d33e791fa53f727252c0d28e5937d0007470, hex"fe7f926bb8df3fc116bae8ac88906e9d1d71e35bcbb757fff47edfa5dbafffffe6f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebcfbfbf9effffffe7f9bb78beffffebbe9af7efff5c71df04ffefbfffffffffdff3fffffffddfddf3effffebbfbbfbfffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fb7bfeeb6fbbfae62e7fffbfddfcc92e7fffffffff7722dfdc7ddf9dfbd68feeb6fb9dbcecbffffdbffefbee0ffffffbfb727b7e7dc7ddfdfb48c93fff7ffffeb9737fffbfddfd6e4e4dffffbfbb336fadeeffbbbb6bef17eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11aeb6fbbfaa8032d1bbfffabfc80640151beb0c7bfb0187ade0c2b905c377c5eecf11ba3096fe8120ff5d0c265706c9af2e9f2aedba037bf05c26b879ae9c0fede58a39525f100", "id 1, one digit");
        c[i++] = Case(42, 0, 14836, 0x68dd749ddad9ae3d5644b8fbda89ad5634d1ad634f0e3e8d2df7a9a431f9f09e, hex"fe7c96ebb8df3fc11632e8ac88906e9d1d71a75bcbb757fff44fffa5dbaffffff7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb6fb3bf9effffffffffbb78beffffebbc9af7efff5c71de04fff7bfffffffffdffbfffffffddfddf5effffebbfbbfbfffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff3bdf3fffdc71dfd9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4737ffeeffbba37fa7bfeeb6fbbfae69e7fffbfddfcc9263fffffffff772ebfdc7ddf9dfbd4afeeb6fbbdbcecbffffdbffefbee0ffffffbf3727b7efdc7ddf9fb48c9bfff7ffffeb9733fffbfddfd6e4e61ffffbfbb336fadeeffbbbb6bef94eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11aeb6fbbfaa802ac53bfffabfc8064aed1beb0c7bfb0583ade0c2b905c377c7eecf11ba3096ff8120ff5d0c265786c9af2e86aaebba037bf05866b879ae9c0fe9e58a39525f100", "id 42, mint day zero");
        c[i++] = Case(4242, 12345, 13986, 0x8edab802ce29bcce182d488b753f19562e1818456899b652872ad35f8723898d, hex"fee67fabe8bf3fc13d3eea4f86906e8f38e1881ecbb747ffd7f7dfa5dba7fffbfff752ec13edbf1b7ff107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedf7f339863fffff9ffdbb78deffffd3ff9ef78ffe7cf39fa07de7bfffffffffdff3fffffffdffdff9effffefbffbfdfffeeefbbbbbfbdfbfedbffb7eb3f7ffffffffde7be3effffffff3bdf1fffce79fbdbe1efbffedf7fb7dbfbfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7f7b51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37ff1bfedbefb7fae56f7ffffffdfe80067fffffffff77bedfce7dfb9fbbdbaffed7ffa5fd4afffffdbffefaed2ffffffff3b3b69affcff9fbba3d42ffff7ffffff527a3ff9bdffcd0e63dffffbffab9c6bdeeffbbbb4fe7a7edbefbffdadf20ffffffdb78436e4fffffdd73769bc4e7dfa97c1ff10f657ffb7cb20385d3bffeb3fc806669f1ff0cc7ff80bcfa9e202af0483f7c4cecf1fbad03fff5b2dfbdd583531b389a92e892eebb08b2af056adbcda7e90bfef8f72e7c6b9c00", "id 4242, four digits");
        c[i++] = Case(4294967295, 16777215, 15131, 0xdd7d9005f74efd05c87bc42ef42234aa8f33b2a02af21b2efbcf16e2eeac813a, hex"fe7b35ebb8df3fc116ba68ac88906e9d1d71e13bcbb757fff46ddfa5dbafffffe7e7d2ec13ebaf1bf7f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb4f3bbf9effffffdf9fbb78beffffe3ac9af7dfff5c71d784ffffbfffffffffdff9fffffffddfddf0effffebbfbbfbfffeeefbbbbbfbfbbfaebffabdbfe7fffffffcd75ff7effffffff3bdf3fffdc71d9d9e9cfbfeebffbbfbbe3ffffffffffffffeffffebbfbbfb5fffdc6fdf9dfecf1ffffc773b51f7affffebddddad2c7ffff18cba4727ffeeffba237fb7bfeeb6fbbfae6feffffbfddfcc94e7fffffffff772adfdc7ddf9dfbd4afeeb6fabdbcecbffffdbffefbee0ffffffb3372777e7dc7ddb9fb48c97fff7ffffeb9735fffbfddfd6e4857ffffbfbb336fadeeffbbbb6bef17eeb6ffbef6efa6fffbffbb4cd34b6ffffedd73f69e01c7dd78590bf11a6b6fbbfaa8022da5bfffabfc80648651beb0c7bfb05c3ade0c2b905c377c6eecf11ba3096fe8920ff5d0c26530ac9af2e9e2aedba037bf05866b879ae9c0feb258a39525f100", "id 2**32-1, the widest the contract can mint");
    }
}
