// SPDX-License-Identifier: MIT
// GENERATED by tools/identity-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/identity-fixture.mjs example.com
pragma solidity ^0.8.30;

/// @notice One rendered state at four token identities, with the byte length
/// and keccak256 of the tokenURI tools/render-token.mjs produces for each.
///
/// @dev RenderFixture varies STATE at a fixed identity. This varies IDENTITY at
/// a fixed state, which is the axis that file cannot cover: every case there
/// shares one bitmap, and a bitmap encodes its own token's url.
///
/// State held constant across all four: level 365, streak 400,
/// lastDay 1000, today 1000, no Marks, live.
library IdentityFixture {
    struct Case {
        uint256 tokenId;
        uint32 mintDay;
        uint256 bytesLen;
        bytes32 hash;
        bytes code;
        string label;
    }

    uint256 internal constant COUNT = 4;

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
        c[i++] = Case(1, 900, 8813, 0x227fb2fd2e6afd93bef260395c40c0484274e5de0cb1e704a633f9da422abecd, hex"fe00810bfc16532d506ebd1a58bb74fffff5dbabfabfaec16ed7ed07faaaaaafe01fe9fe00d33eefebb3eefffff37fff66f70afbdfedf8b7feeeeea0fefdffdf85ffef66e727bfffff6abfeefeef296ffdfff5fbfe666796e3fedfeb623feefee8d8ffffff86fff66f7362bdfedfd0b3eeeeea5bcfdffdda69bef66f8ac0fffff12f62efecfa0057dfec67fa66642bf04b6df716ba7aed8f95d52ffa2d2e9306943305132d230fe84883cd80", "id 1, one digit");
        c[i++] = Case(42, 0, 8644, 0x9d4839cc04086f823dd6f6f125b2940c95ef6afcb90a4183ef49a313102fe79f, hex"fe94a053fc156056506ebf5b7cbb75ff57f5dba3f33faec14ec9ed07faaaaaafe00fe5fe00ce0efee97deefddfc59ffeff6ef4fbfedfe3d7feefeeb2beffddfc7affeff6ee1fbfedfe4ebfeefeef2c4ffddfe79dfeff6e210bfedfeb613eefeeb3eeffddfcebcfeff6ec8fbfedfe66dbeefeeb7daffddfe582deff6a181bfedfeb6eecefecfa0067ddf443f86ff6ea9053adf514bae6f86fa5d2fdc2dbee90d96ecd05be53a86fe8410a1f80", "id 42, mint day zero");
        c[i++] = Case(4242, 12345, 9210, 0x213c193cb37f2b958855002d809c074a669b738d65bed82a0c7444080d778d5c, hex"feeee4c3fc15d9d9d06e9cd4dcbb74dd85d5dbaff5ffaec14ddddd07faaaaaafe011d9dd00e6ffffff99eeddddd9efff777616fbdddddb37fffffff5fefdddddbdfff777603fbdddddc07ffffff35fcfdddd7be6ff7772c3b3ddddd38b3ffffff4c6fdddd52caff77742b0bddddee80fffffff0ac7ddddb9f5ff7776fa4b5ddde38dedfffdfd005dddcc47f897772ab0515d951bba59fbffd5d28c4507aead73722f0519d5b08fe9533fd880", "id 4242, four digits");
        c[i++] = Case(4294967295, 16777215, 8719, 0x4b7e47b48f676e032536f3cde958a1f44c69fb6cb666f874657dbc5a9dda617b, hex"fe8da173fc152015506ebf526cbb75ff8765dba3f93f2ec14ec9e507faaaaaafe00fe9f300ce0ede997beefdde85bffeff6ef4fbfedfd3d7feefeeb2deffddf87bffeff6ce17bfedfc4e7feefeef2deffddfa78dfeff6e2153fedfcb653eefeeb39effddf8e8ffeff6cc9ebfedff6663eefefb7d2ffddfa587deff6e1823fedfeb6d28efeefa0077ddfc43f9cff6aa9057edbb14ba8cf88fadd1ec579b2e9efd0ccd05be9fc86fe84d601f80", "id 2**32-1, the widest the contract can mint");
    }
}
