// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test, console} from "forge-std/Test.sol";

import {CodeRenderer} from "../src/render/CodeRenderer.sol";
import {HeartMask} from "../src/render/HeartMask.sol";
import {PathWriter} from "../src/render/PathWriter.sol";

/// @notice WHAT A BIGGER QR ACTUALLY COSTS, measured rather than estimated.
///
/// @dev The version raise was killed on an ESTIMATE: path bytes scaled by a
/// gas-per-byte figure borrowed from a harness call. A later estimate on a
/// gas-per-RUN basis disagreed with it by 60% (+1.07M against +1.74M). Two
/// estimates that disagree are not a measurement, and the decision they were
/// being used to make -- whether the artwork's heart can be drawn better -- is
/// worth a real number.
///
/// `CodeRenderer` reads `HeartMask.SIZE`, so it can only draw 37. This harness
/// is that code with the size as a PARAMETER, and nothing else changed.
///
/// THE CONTROL IS THE WHOLE TEST. At size 37 the harness must produce output
/// BYTE-IDENTICAL to the real CodeRenderer. Without that, a v10 number measures
/// this file rather than the renderer.
contract SizedCodeRenderer {
    function paths(
        bytes memory code,
        bytes memory mask,
        uint256 size,
        uint256 offset,
        string memory heartFill,
        string memory noiseFill
    ) external pure returns (string memory) {
        uint256 maxRuns = size * ((size + 1) / 2);
        PathWriter.Buffer memory noiseBuf = PathWriter.create(maxRuns);
        PathWriter.Buffer memory heartBuf = PathWriter.create(maxRuns);

        for (uint256 y; y < size; ++y) {
            uint256 codeRow = _rowBits(code, y, size);
            if (codeRow == 0) continue;
            uint256 maskRow = _rowBits(mask, y, size);
            PathWriter.writeRow(noiseBuf, codeRow & ~maskRow, size, offset, y + offset);
            PathWriter.writeRow(heartBuf, codeRow & maskRow, size, offset, y + offset);
        }

        return string(
            abi.encodePacked(
                '<path fill="', noiseFill, '" d="', PathWriter.seal(noiseBuf),
                '"/><path fill="', heartFill, '" d="', PathWriter.seal(heartBuf), '"/>'
            )
        );
    }

    function _rowBits(bytes memory packed, uint256 y, uint256 size)
        private pure returns (uint256 bits)
    {
        uint256 start = y * size;
        uint256 byteIndex = start >> 3;
        uint256 bitOffset = start & 7;
        /// @solidity memory-safe-assembly
        assembly {
            bits := shr(sub(256, size), shl(bitOffset, mload(add(add(packed, 0x20), byteIndex))))
        }
    }
}

contract RealCodeHarness {
    function paths(
        bytes memory code,
        bytes memory mask,
        uint256 offset,
        string memory heartFill,
        string memory noiseFill
    ) external pure returns (string memory) {
        return CodeRenderer.paths(code, mask, offset, heartFill, noiseFill);
    }
}

contract QrVersionCostTest is Test {
    SizedCodeRenderer sized;
    RealCodeHarness real;

    string constant HEART = "#c8102e";
    string constant NOISE = "#767676";

    function setUp() public {
        sized = new SizedCodeRenderer();
        real = new RealCodeHarness();
    }

    // Generated by the solver against the real domain, mask 0, at each version.
    // Token 1 on machinereadableonly.com.
    function _code5() internal pure returns (bytes memory) {
        return hex"fe10bb93fc13bb33d06eb9918cbb74ff3f05dba3b2bfaec13ff3dd07faaaaaafe01fffff00efeecefe27efffff736ffe6669e2fbffffda9bfeeeefe0deffffe716ffe6678f6fbffffc0abfeeee8e0ecffffe7147fe66629793ffff9e233eeee9f184fffff3156fe66617f83ffffe82e7eeeef619efffff7261be66639ed97ffff128b4eeedf80057ffec6ffa66666b705bbfb112baeaea4f9dd137eecfeeac40246b0533bfb42feacae9c180";
    }
    function _mask5() internal pure returns (bytes memory) {
        return hex"00000000000380038000ff80ff801fff1fff01fffdfffc1ffffffff0ffffffff8ffffffffe7ffffffff3ffffffff9ffffffffcffffffffe7ffffffff3ffffffff9ffffffffcffffffffe7ffffffff3ffffffff8ffffffff87fffffffc1fffffffc0fffffffe03ffffffe01fffffff007ffffff001ffffff0007fffff0003fffff8000fffff80001ffff000007fff000001fff0000007ff0000000fe00000003e000000004000000002000000";
    }
    function _code10() internal pure returns (bytes memory) {
        return hex"fe21d548bcdb3fc12c08022230906eb3fff9bd99cbb74fffc8b888a5dba7ffffef67d2ec13c88b1377b107faaaaaaaaaaafe01f888c7333000efffffffffffe25effffcbbbbbfb87ffffeffffffeb7bf88883373c30bfffff8fbbba6d9effffcba8883ccfffffffe76659d7bf888f333323e7fffffffffffffdeffffcbbbbbf8ffffffffffffffcbbf888f033307e7ffffffe6fffdffeffffcbf373e8dfffffffdddfe7efbfc88f333303e7fffffffffffffdeefffcbbbbbf81fffffeffffffe971fc88c77fbf127affffebdfffadfc7ffff1aa88c477fffffff6663fafbfc88cf3331cabeffff9ffffe77c2fffffebbbba80affffffffffbcb63fc88ce3333e4e7ffff9effffe3e4fffffeb73fe0f9e7ffffbdfbbab60b488cf33324e633bff9ffffede9a8dfffebbbadc5cedffffffffba8eb5c88cfb7b5c0227fff9ff989e5825bfffea888e4a9b07fffe6662bbf14888cf33310403aa10ffffb6fb8040d471b99944ffa0bfbafffe2bb05c000c6331112ba80b7ffbfbffddd283418548244aeb23bfbb2c7afb054c002e01102efe8d163b2aa7cb80";
    }
    function _mask10() internal pure returns (bytes memory) {
        return hex"00000000000000000000000000000001fc0001fc000007ffc007ffc0000ffff80ffff8001ffffe0fffff001fffffdfffffc00fffffefffffe00ffffffffffff80ffffffffffffe07ffffffffffff07ffffffffffffc3ffffffffffffe1fffffffffffff1fffffffffffffcfffffffffffffe7fffffffffffff3fffffffffffff9fffffffffffffcfffffffffffffe7fffffffffffff3fffffffffffff9fffffffffffffcfffffffffffffe3ffffffffffffe1fffffffffffff0fffffffffffff87ffffffffffffc1ffffffffffffc0ffffffffffffe07ffffffffffff01ffffffffffff00ffffffffffff803fffffffffff800fffffffffff8007ffffffffffc001ffffffffffc000ffffffffffe0003fffffffffe0000fffffffffe00003ffffffffe00000ffffffffe000003fffffffe000000fffffffe0000003ffffffe0000000ffffffe00000003fffffe00000000fffffe000000003ffffe0000000007fffc0000000001fffc00000000003ff800000000000ff8000000000001f000000000000070000000000000100000000000000000000000";
    }

    /// @notice THE CONTROL. The harness must be the real renderer at 37.
    function test_theHarnessIsTheRealRendererAtThirtySeven() public view {
        string memory a = real.paths(_code5(), _mask5(), 7, HEART, NOISE);
        string memory b = sized.paths(_code5(), _mask5(), HeartMask.SIZE, 7, HEART, NOISE);
        assertEq(b, a, "the sized harness must match the shipped renderer exactly at 37");
        console.log("control: harness == real renderer at size 37, %d bytes", bytes(a).length);
    }

    /// @notice What version 10 costs, measured.
    function test_whatVersionTenCosts() public {
        // Warm both contracts so neither pays a cold account access.
        real.paths(_code5(), _mask5(), 7, HEART, NOISE);
        sized.paths(_code5(), _mask5(), 37, 7, HEART, NOISE);

        uint256 g0 = gasleft();
        string memory five = sized.paths(_code5(), _mask5(), 37, 7, HEART, NOISE);
        uint256 gas5 = g0 - gasleft();

        g0 = gasleft();
        string memory ten = sized.paths(_code10(), _mask10(), 57, 7, HEART, NOISE);
        uint256 gas10 = g0 - gasleft();

        console.log("version  5 (37 modules)");
        console.log("  gas  ", gas5);
        console.log("  bytes", bytes(five).length);
        console.log("version 10 (57 modules)");
        console.log("  gas  ", gas10);
        console.log("  bytes", bytes(ten).length);
        console.log("");
        console.log("THE CODE BLOCK COSTS THIS MUCH MORE AT VERSION 10");
        console.log("  gas  ", gas10 - gas5);
        console.log("  bytes", bytes(ten).length - bytes(five).length);

        assertGt(gas10, gas5, "a bigger code must cost more, or the inputs are wrong");
        assertGt(bytes(ten).length, bytes(five).length, "a bigger code must emit more");
    }
}
