// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs 1 example.com
pragma solidity ^0.8.30;

/// @notice Every state in the render matrix, with the byte length and
/// keccak256 of the tokenURI tools/render-token.mjs produces for it.
/// Token 1 on example.com.
library RenderFixture {
    struct Case {
        uint32 level;
        uint32 streak;
        uint32 lastDay;
        uint32 today;
        uint256 marks;
        bool resting;
        bool sunset;
        uint32 sunsetDay;
        uint16 fellRun;
        uint24 fellDay;
        uint32 echo;
        uint256 parent;
        uint32 generation;
        uint256 bytesLen;
        bytes32 hash;
        string label;
    }

    uint256 internal constant COUNT = 63;

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
        c[i++] = Case(365, 0, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8811, 0x5e7b7e2ec8f2f804e524fc5e3fdd28e8af1fc5c118d53cf483b954dc90bf54c7, "tier streak 0");
        c[i++] = Case(365, 0, 1000, 1030, 0, false, false, 0, 0, 0, 0, 0, 0, 8811, 0xeb470718d15361b9dc08f539b6a2b3c3f1f68d07051f52c44ef7539f34f0b4cb, "tier streak 0, 30 days lapsed");
        c[i++] = Case(365, 3, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8811, 0xfbadfecd1f0bb95bbfc6ef93b7b585fdba208c62cb6efa77baba862034dcf3c8, "tier streak 3");
        c[i++] = Case(365, 3, 1000, 1030, 0, false, false, 0, 0, 0, 0, 0, 0, 8811, 0x7d644dc4365ba673e4ddd560c9a16ed4874aea1cea1a8deffe25c5b94fa57dce, "tier streak 3, 30 days lapsed");
        c[i++] = Case(365, 7, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8811, 0xe755d1bc26edd033741cc9eb9616fe36ebc4420448b5dbd3686681f79e56b092, "tier streak 7");
        c[i++] = Case(365, 7, 1000, 1030, 0, false, false, 0, 0, 0, 0, 0, 0, 8811, 0x4a87deee41ba2228b323a6f5e2203734c298d9ebbe8f4bb99349c443fadeeb81, "tier streak 7, 30 days lapsed");
        c[i++] = Case(365, 30, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8812, 0xa373b5e3dee488152f6868b1cb3bcb464ce7b4f97f9c398e958212e0d0487784, "tier streak 30");
        c[i++] = Case(365, 30, 1000, 1030, 0, false, false, 0, 0, 0, 0, 0, 0, 8812, 0x9a1adb074794702c415f46cdee9ec59300b765eeb9c71a1c77f8168e5bc3be89, "tier streak 30, 30 days lapsed");
        c[i++] = Case(365, 100, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8813, 0xdb2a914bc80347f0545ee4afe3b7658d6eba871c664bd9c2cb6d4726f1bb6fd4, "tier streak 100");
        c[i++] = Case(365, 100, 1000, 1030, 0, false, false, 0, 0, 0, 0, 0, 0, 8813, 0x77a07ed2698299a17f2af75eba027eea7d8b1b90127d29a23372cc792c36f1a6, "tier streak 100, 30 days lapsed");
        c[i++] = Case(1, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8796, 0x07c1d9bdc14466081f6d473023846e8582ed17cb272910aa60d0a193d5fca54d, "0 years");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8813, 0x227fb2fd2e6afd93bef260395c40c0484274e5de0cb1e704a633f9da422abecd, "1 years");
        c[i++] = Case(730, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8897, 0x9ef8b24641a44397a48850358e071cfdd4c96991c71d43d4fc6db996c7c693ac, "2 years");
        c[i++] = Case(1825, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 9202, 0x276eb1a91f868ca415261be1a08d30bf2e7088d3628d55948050e33c5b81312e, "5 years");
        c[i++] = Case(3285, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 9534, 0x9c8b6dc723bd87b0aae2c107f302d4428af14a3972a9ec0a303a2036b0f07de6, "9 years");
        c[i++] = Case(3650, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 9615, 0x16f7524c821aca30a454df8f3560d61ef94072eed49ee8afdec7da09a5f647ca, "10 years");
        c[i++] = Case(4015, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 9615, 0x0ae4d93bd86ac5450b7d4627c58952e42ca68977c97da2bae9fdd3752485d16b, "11 years");
        c[i++] = Case(1, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8796, 0x07c1d9bdc14466081f6d473023846e8582ed17cb272910aa60d0a193d5fca54d, "fill 1");
        c[i++] = Case(12, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8834, 0xdd71aa9d6bf65907f627f8042f9300cea5a046e2295a0945d8e51ffb8ae98754, "fill 12");
        c[i++] = Case(200, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8800, 0xf0b57de466f03389a89a76823373f70ef6b92bf505254f85b1e6e776a52946ad, "fill 200");
        c[i++] = Case(364, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8844, 0x75dd676b5d717d6120f1da8522d137690ce3cfae888604fa956ed15f4ed8c81e, "fill 364");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8813, 0x227fb2fd2e6afd93bef260395c40c0484274e5de0cb1e704a633f9da422abecd, "fill 365");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 0, 0, 0, 8813, 0x227fb2fd2e6afd93bef260395c40c0484274e5de0cb1e704a633f9da422abecd, "no marks");
        c[i++] = Case(365, 400, 1000, 1000, 4, false, false, 0, 0, 0, 0, 0, 0, 8819, 0xd04f16c01d569c0bdda8b4f13dbc10dc3d8247b2ac4ca929bb6292da57e5f6af, "mark ache");
        c[i++] = Case(365, 400, 1000, 1000, 2, false, false, 0, 0, 0, 0, 0, 0, 8895, 0xeaba1aeedd95473a4b74e9efe3ffac276235ec31f2183fd506bf69e841cc02af, "mark hush");
        c[i++] = Case(365, 400, 1000, 1000, 16, false, false, 0, 0, 0, 0, 0, 0, 9031, 0x2f78fd6e14b8cc7e25db54dc57d29b0b92510cc4bd615e4afe40d624db822633, "mark beat");
        c[i++] = Case(365, 400, 1000, 1000, 1024, false, false, 0, 0, 0, 0, 0, 0, 8819, 0x873299440394a30c96f46d6c29d6d9691c9023460164449cfbc52d1911e3f97b, "mark aura");
        c[i++] = Case(365, 400, 1000, 1000, 128, false, false, 0, 0, 0, 0, 0, 0, 8821, 0xc0f8fab275171db4362b25ad561c7f893cb2cf2f2ede6e04d79e50f2dfd90876, "mark vessel");
        c[i++] = Case(365, 400, 1000, 1000, 1174, false, false, 0, 0, 0, 0, 0, 0, 9137, 0x2250fbdfb42f7607e24f56582414cc89a2530f9ac6723a2264872694f896a15d, "all drawing marks");
        c[i++] = Case(365, 400, 1000, 1000, 1438, false, false, 0, 0, 0, 0, 0, 0, 9154, 0x9cd5fa68c72a9b3ad556ea7132a5bf2f0894fe4510f4e75c5394ded35b2de387, "all seven marks");
        c[i++] = Case(365, 400, 1000, 1000, 65568, false, false, 0, 0, 0, 0, 0, 0, 9858, 0xe88adce63191aff7f6dbd4653cfc53230edf6c5a8e7af1b09a1a5c7c911b8534, "iris squircle");
        c[i++] = Case(365, 400, 1000, 1000, 131104, false, false, 0, 0, 0, 0, 0, 0, 10270, 0x69763d621caa55f4062944b6b214d06e1a4c455f4c4cbd6a9e6cffd2b2e8e276, "iris leaf");
        c[i++] = Case(365, 400, 1000, 1000, 544, false, false, 0, 0, 0, 0, 0, 0, 9703, 0x2545b560a78c4b8dccf76d46865d044397d9084751aaedbfb7b3c4c59b802195, "tint violet");
        c[i++] = Case(365, 400, 1000, 1000, 16777760, false, false, 0, 0, 0, 0, 0, 0, 9703, 0xd6f564a782c91aaf9f66109b09272f97f3b1bc83fe35033c2ce2fbf3f2b05b04, "tint gold");
        c[i++] = Case(365, 100, 1000, 1030, 429496729664, false, false, 0, 0, 0, 0, 0, 0, 9734, 0x9a0fe6db54fa3d093cc55ee9aa04beec2847606dd62be89ed4b75855e7243b25, "earned iris, lapsed to the start tier");
        c[i++] = Case(365, 400, 1000, 1000, 1056, false, false, 0, 0, 0, 0, 0, 0, 9703, 0x63f26e5d3fb6f3abc249a29cb2582f4e11d1bfb4c6998b83ed46b9895ffa3911, "iris on aura, no hush");
        c[i++] = Case(365, 100, 1000, 1000, 429513507392, false, false, 0, 0, 0, 0, 0, 0, 9741, 0xefdbb2db6cb61bb8ba8439a26154a55ef1e9263656dcf98ca7802abe8dd62f03, "tint on earned iris");
        c[i++] = Case(365, 400, 1000, 1000, 256, false, false, 0, 0, 0, 0, 0, 0, 8820, 0x6e6f399f8fde4e0af5df2c41a372055d37e5a54e142ecacebdb02c8b3d54aeab, "break alone");
        c[i++] = Case(365, 400, 1000, 1000, 264, false, false, 0, 0, 0, 0, 0, 0, 8829, 0xbf2d6a50bc5c61257a73a7d7a67441b0c56bd6c3e9f06a612d428fb8f15c0675, "break with static");
        c[i++] = Case(365, 400, 1000, 1000, 272, false, false, 0, 0, 0, 0, 0, 0, 9039, 0x6bda5b5318c1ff0b1f36d04b3d4bda785d46f1fc79ac3340ba38063192e49fd9, "break with beat");
        c[i++] = Case(365, 400, 1000, 1000, 8, false, false, 0, 0, 0, 0, 0, 0, 8821, 0xf73cca4405726279e4c9371a208a355d1d4d1ca076df7ac4d8bda61a063bb672, "mark static");
        c[i++] = Case(365, 100, 1000, 1030, 429496729920, false, false, 0, 0, 0, 0, 0, 0, 9742, 0x1c86a88f449e23398231aa979275a991d0ec5c5c3ee2c6d92521ad078e7ddcba, "break on earned iris, lapsed to the start tier");
        c[i++] = Case(1, 1, 1000, 1029, 0, false, false, 0, 0, 0, 0, 0, 0, 8794, 0x9c029ee2bb6882010a03500c45d1fb4bc6b357e3b6f9b66173f40892946cadfd, "never returned, 29 days");
        c[i++] = Case(1, 1, 1000, 1030, 0, false, false, 0, 0, 0, 0, 0, 0, 8794, 0xf726a6b6eecb33a5792f6575d5d0013c2c7ffb11d068ce0b88a0ada1b4621fac, "never returned, 30 days");
        c[i++] = Case(1, 1, 1000, 1365, 0, false, false, 0, 0, 0, 0, 0, 0, 8794, 0x997f4d1e76f68792af716cd4b9bda292477fedaa310afe11f83d2446d27e1145, "never returned, a year");
        c[i++] = Case(1, 1, 1000, 2095, 0, false, false, 0, 0, 0, 0, 0, 0, 8794, 0x997f4d1e76f68792af716cd4b9bda292477fedaa310afe11f83d2446d27e1145, "never returned, three years");
        c[i++] = Case(1, 1, 1000, 1365, 4, false, false, 0, 0, 0, 0, 0, 0, 8800, 0xbf283a616144467dbd516231e278127f4ebb82038866f93a5c9876bd24d10178, "ache, never returned, a year");
        c[i++] = Case(1, 1, 1000, 1365, 1024, false, false, 0, 0, 0, 0, 0, 0, 8800, 0x40db2e68915a19a59a950bfdc97bb3c21ae6df5d26dae114b48699876fcee968, "aura, never returned, a year");
        c[i++] = Case(365, 400, 1000, 9999, 0, true, false, 0, 0, 0, 0, 0, 0, 8816, 0x5d6f2c697114e3b0b95a8ce21f37cd77be6808030fb477ead1286cd95fd83e12, "resting");
        c[i++] = Case(365, 400, 1000, 9999, 0, false, true, 0, 0, 0, 0, 0, 0, 8816, 0xac0284ae81aca35c5be2b47cf83aa4223f6e133a3776a171faa1bfd76496b25a, "sunset");
        c[i++] = Case(365, 400, 1000, 9999, 0, false, true, 1040, 0, 0, 0, 0, 0, 8816, 0x0b9a6715033974613d193e72dd8c9bd8849323d97cd2027ad729f569b4b61f15, "sunset after this token lapsed");
        c[i++] = Case(365, 1, 1002, 1002, 0, false, false, 0, 400, 1000, 0, 0, 0, 8811, 0xae9f8905750bbd5fa5f2cd82a4fb90f76011a43f51d19f2847be23f6eca317d7, "slipped, day of return");
        c[i++] = Case(365, 4, 1005, 1005, 0, false, false, 0, 400, 1000, 0, 0, 0, 8811, 0xf7e3f566f86db45c5885e140ccd12c48960dd4551422e5972ad4c3c3b3301db6, "slipped, 3 days on");
        c[i++] = Case(365, 8, 1009, 1009, 0, false, false, 0, 400, 1000, 0, 0, 0, 8811, 0x336bb853f118380ec2a9e36f0dfd1dbc21157b37f743d2d20adfca6ddca62f57, "slipped, 7 days on");
        c[i++] = Case(365, 31, 1032, 1032, 0, false, false, 0, 400, 1000, 0, 0, 0, 8812, 0x99f06d41ae712473ad492a25360fd466b3e48a85c9c54df2fd3237969d1ed99e, "slipped, 30 days on");
        c[i++] = Case(365, 100, 1100, 1100, 0, false, false, 0, 400, 1000, 0, 0, 0, 8813, 0x7e813279b6693767e4e655f815f5b314674134bb4a9420b98fc3feb22698336a, "slipped, new run overtakes the fall");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 1, 7, 1, 9817, 0x28a72c62b9be1f579df81a91125d6d5a4cc240bb943307e3d676f98fb93e45eb, "child, echo of one day");
        c[i++] = Case(730, 400, 1000, 1000, 0, false, false, 0, 0, 0, 1000, 7, 1, 9900, 0xeff19754ddf6449a32abf5b65f63826cc8f60c44180a472b6581ef875e85bb99, "child, two years and an echo");
        c[i++] = Case(1, 1, 1000, 1365, 0, false, false, 0, 0, 0, 365, 7, 1, 9756, 0x6a830b9dbce684d7b05776d8254310fd7a72a0a7a3d553e20e64814ca27acca9, "child, never returned, a year");
        c[i++] = Case(365, 400, 1000, 1030, 0, false, false, 0, 0, 0, 365, 7, 1, 9819, 0x8b94e902001e4a18a91a467f218c0395e70def924bc91b8321efd567cfd2a01b, "child, 30 days lapsed");
        c[i++] = Case(365, 400, 1000, 9999, 0, true, false, 0, 0, 0, 365, 7, 1, 9822, 0xa6f609735e2f49918f18ca9ad7d7b648b2f44900061eb781a0849953a4f5d591, "child, resting");
        c[i++] = Case(365, 400, 1000, 9999, 0, false, true, 0, 0, 0, 365, 7, 1, 9822, 0x8bb3d5afb31e7d4b4ce663487e8b5c6561654642f46cfaba94c0154e52084440, "child, sunset");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 3650, 4242, 3, 9823, 0x4df7c10d0e6e7237814fcb2c2f09438246de3c706586a02d307f66b709d99515, "child, deep line and a wide parent");
    }
}
