// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test, console} from "forge-std/Test.sol";
import {Renderer} from "../src/render/Renderer.sol";
import {IRenderer} from "../src/render/IRenderer.sol";
import {FrameRenderer} from "../src/render/FrameRenderer.sol";
import {MarkRenderer} from "../src/render/MarkRenderer.sol";
import {Palette} from "../src/render/Palette.sol";
import {TokenView} from "../src/render/TokenView.sol";

/// @notice The assembled image and metadata, and the differential check that
/// keeps this renderer and the JS reference from drifting apart.
contract RendererTest is Test {
    Renderer r;

    /// @dev Token 1 on example.com, the same bitmap CodeRenderer.t.sol uses.
    /// Generated by tools/token-bitmap.mjs.
    function _bitmap() internal pure returns (bytes memory) {
        return
        hex"fe00810bfc16532d506ebd1a58bb74fffff5dbabfabfaec16ed7ed07faaaaaafe01fe9fe00d33eefebb3eeff"
        hex"fff37fff66f70afbdfedf8b7feeeeea0fefdffdf85ffef66e727bfffff6abfeefeef296ffdfff5fbfe666796"
        hex"e3fedfeb623feefee8d8ffffff86fff66f7362bdfedfd0b3eeeeea5bcfdffdda69bef66f8ac0fffff12f62ef"
        hex"ecfa0057dfec67fa66642bf04b6df716ba7aed8f95d52ffa2d2e9306943305132d230fe84883cd80";
    }

    /// @dev One Mark per pair -- the legal maximum a real token can hold, since
    /// `MachineReadableOnly.applyMark` excludes pair partners. Hush over Ache
    /// and Beat over Static were picked because they draw the larger amount of
    /// image (Hush adds a rect, Beat adds a gradient defs block), which makes
    /// this also the byte-worst-case fixture. Iris Bought is included even
    /// though it draws nothing yet, so the fixture reflects a token that took
    /// every pair rather than four of five.
    uint256 constant ALL_MARKS = MarkRenderer.HUSH | MarkRenderer.BEAT
        | MarkRenderer.IRIS_BOUGHT | MarkRenderer.VESSEL | MarkRenderer.AURA;

    function setUp() public {
        r = new Renderer();
    }

    function _view(uint32 level, uint32 streak, uint32 lastDay, uint32 today)
        internal
        pure
        returns (TokenView memory v)
    {
        v.tokenId = 1;
        v.level = level;
        v.streak = streak;
        v.lastDay = lastDay;
        v.today = today;
        v.mintDay = 900;
        v.code = _bitmap();
    }

    // ---------------------------------------------------------------------
    // The differential check. This is the important test in this file.
    // ---------------------------------------------------------------------
    //
    // Hashes rather than the strings themselves, because one tokenURI is around
    // 10,000 bytes. The byte length is asserted alongside each hash so a failure
    // says whether the two renderers disagree on length or only on content.
    //
    // Regenerate with: node tools/token-uri-fixture.mjs

    function _diff(string memory label, TokenView memory v, uint256 len, bytes32 hash) internal view {
        string memory uri = r.tokenURI(v);
        assertEq(bytes(uri).length, len, string.concat(label, ": byte length differs from the reference"));
        assertEq(keccak256(bytes(uri)), hash, string.concat(label, ": content differs from the reference"));
    }

    function test_dayOneMatchesTheJavascriptReference() public view {
        _diff("day one", _view(1, 1, 1000, 1000), 8826,
            0xc9776123c933b8ea853356412691c9e8072b4b847462b0da095dcf1ba1b7df26);
    }

    function test_aPartYearMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.agentKeyId = bytes32(uint256(0xa9e));
        _diff("day 200", v, 8827,
            0xa0378aded6012838abb1d42d2bbb6959733bbc6c229c9a4263178ae01c147ba4);
    }

    function test_aWholeHeartMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365, 140, 1000, 1000);
        v.generation = 1;
        v.parent = 7;
        v.seedsGiven = 2;
        _diff("whole, one ring", v, 8881,
            0x85eb55ad13ce55fa4a21d432cf09afd8090adc47a038066e5aba263c2cb29f33);
    }

    function test_aLapsedTokenMatchesTheJavascriptReference() public view {
        // Forty days without a check-in. This is the case that caught a real
        // divergence: the JS renderer had a lapse function it never called, so
        // the image never paled while this renderer's did.
        _diff("whole and lapsed", _view(365, 140, 1000, 1040), 8881,
            0xc92fc8193735bdd35f30efdadab7d7010e42945cfc0f71b2503ddddc04b22ca3);
    }

    function test_theRingCapMatchesTheJavascriptReference() public view {
        _diff("ten years, capped", _view(365 * 10, 400, 1000, 1000), 9751,
            0x47f0687968543a35be923154d13d7224668c1dbf3c8fc91c0f066db12c0e6430);
    }

    function test_everyMarkAtOnceMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365 * 10, 400, 1000, 1000);
        v.marks = ALL_MARKS;
        _diff("every drawn mark", v, 10976,
            0x9926de14952c582758e63867875c31734df52fb322a88fc796993e13b04840c1);
    }

    function test_aSealedTokenMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365 * 3, 200, 1000, 9999);
        v.resting = true;
        _diff("sealed at rest", v, 9117,
            0x3d365a93f4dc7bb11a537cfa45146857fe16807f7872184787c2cf149262be88);
    }

    function test_theEyesAreDrawnLastOverTheNoise() public view {
        // A Static + Iris token: Static already recolours the finder patterns,
        // because they are ordinary code modules. The eyes must land ON TOP of that
        // and the erase-to-ground step is what makes it clean rather than a green
        // square with a shape on it.
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.marks = MarkRenderer.STATIC | MarkRenderer.IRIS_BOUGHT;   // shape 0, target
        string memory s = r.svg(v);
        // The code block is the LAST TWO <path> elements. Everything after them is
        // eyes, so the tail of the SVG must open with the first eye's erase rect.
        uint256 lastPath = _lastIndexOf(s, "<path fill=");
        uint256 firstEye = _indexOfFrom(s, '<rect x=', lastPath);
        assertLt(lastPath, firstEye, "the eyes must be emitted after the code paths");
        assertLt(firstEye, bytes(s).length, "no eyes were emitted at all");
    }

    function test_tintOverridesTheUntintedEyeInk() public view {
        // Untinted, the bought Iris draws in the token's own heart colour.
        // Tint replaces it -- variant 0 violet, variant 1 gold -- regardless
        // of what the live rung would otherwise put there.
        TokenView memory v = _view(200, 45, 1000, 1000);
        uint256 base = MarkRenderer.IRIS_BOUGHT | MarkRenderer.TINT;

        v.marks = base;   // variant 0 -> violet
        string memory violet = r.svg(v);
        assertTrue(vm.contains(violet, "#9800fc"), "Tint variant 0 must draw violet eyes");

        v.marks = base | (uint256(1) << 24);   // variant 1 -> gold
        string memory gold = r.svg(v);
        assertTrue(vm.contains(gold, "#b8860b"), "Tint variant 1 must draw gold eyes");

        assertTrue(
            keccak256(bytes(violet)) != keccak256(bytes(gold)),
            "the two Tint variants must produce different images"
        );
    }

    function test_theEarnedIrisEyeKeepsItsStoredRunColourAndNeverLapses() public view {
        // The earned Iris was applied at a 100-day run -- the top tier -- and
        // must keep drawing that colour even once the token has since lapsed
        // all the way back down to the start tier. That is the whole point of
        // the Mark: it stops tracking the lapse.
        TokenView memory v = _view(200, 100, 1000, 1030);   // 30 days lapsed
        v.marks = MarkRenderer.IRIS_EARNED | (uint256(100) << 32);
        string memory out = r.svg(v);

        string memory storedColour = Palette.colourAt(Palette.tierIndex(100));
        string memory liveColour = Palette.colourAt(Palette.lapsedIndex(100, 1000, 1030));
        assertTrue(
            keccak256(bytes(storedColour)) != keccak256(bytes(liveColour)),
            "sanity: the live rung must actually differ from the stored run"
        );
        assertTrue(vm.contains(out, storedColour), "the earned Iris must draw in the run it was applied at");
    }

    function test_theIrisAttributesAppearOnlyWhenAnIrisIsWorn() public view {
        TokenView memory bare = _view(200, 45, 1000, 1000);
        string memory bareUri = r.tokenURI(bare);
        assertFalse(vm.contains(bareUri, "Iris Shape"), "no Iris Shape attribute without an Iris");
        assertFalse(vm.contains(bareUri, "Iris Run"), "no Iris Run attribute without an Iris");

        TokenView memory bought = _view(200, 45, 1000, 1000);
        bought.marks = MarkRenderer.IRIS_BOUGHT | (uint256(2) << 16);   // shape 2, leaf
        string memory boughtUri = r.tokenURI(bought);
        assertTrue(
            vm.contains(boughtUri, '{"trait_type":"Iris Shape","value":"leaf"}'),
            "the bought route must name its shape"
        );
        assertFalse(vm.contains(boughtUri, "Iris Run"), "the bought route has no run to report");

        TokenView memory earned = _view(200, 45, 1000, 1000);
        earned.marks = MarkRenderer.IRIS_EARNED | (uint256(365) << 32);
        string memory earnedUri = r.tokenURI(earned);
        assertTrue(
            vm.contains(earnedUri, '{"trait_type":"Iris Shape","value":"target"}'),
            "the earned route is always target"
        );
        assertTrue(
            vm.contains(earnedUri, '{"trait_type":"Iris Run","value":365}'),
            "the earned route must report its stored run"
        );
    }

    // ---------------------------------------------------------------------
    // The wrapper's own rules
    // ---------------------------------------------------------------------

    function test_noRawHashSurvivesIntoTheUri() public view {
        // The whole tokenURI is itself a URI, so one raw "#" opens a fragment
        // and truncates the JSON. Base64 hides every hash inside the SVG; the
        // one in the name is written %23. Beat is worn here because its
        // url(#b) reference is the easiest one to leak.
        TokenView memory v = _view(365, 140, 1000, 1000);
        v.marks = MarkRenderer.BEAT;
        bytes memory uri = bytes(r.tokenURI(v));
        for (uint256 i; i < uri.length; ++i) {
            assertTrue(uri[i] != "#", "a raw hash reached the tokenURI");
        }
    }

    function test_theJsonIsUtf8AndOnlyTheImageIsBase64() public view {
        string memory uri = r.tokenURI(_view(365, 140, 1000, 1000));
        assertTrue(
            vm.contains(uri, "data:application/json;utf-8,{"),
            "the JSON must be served as plain utf-8"
        );
        assertTrue(vm.contains(uri, "data:image/svg+xml;base64,"), "the image must be base64");
    }

    function test_theImageIsDrawnInTheFixedOrder() public view {
        // Ghost, frame, noise, heart. Fixed so each library emits one adjacent
        // pair of paths and the assembler can simply concatenate them.
        //
        // Vessel is worn so the frame is gold and the four fills are four
        // distinct strings. On a bare token the frame and the heart share the
        // streak colour, and searching for it would find the frame every time.
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.marks = MarkRenderer.VESSEL;
        string memory out = r.svg(v);

        // Both inks are read off the palette rather than pasted in. They are a
        // matched pair now -- one per rung -- so a hardcoded noise here would
        // rot the moment a tier is retuned, which is exactly what it did.
        uint256 rung = Palette.tierIndex(45);
        string memory heart = Palette.colourAt(rung);
        string memory noise = Palette.noiseAt(rung);

        assertLt(_indexOf(out, "#f4eef0"), _indexOf(out, "#b8860b"), "ghost before frame");
        assertLt(_indexOf(out, "#b8860b"), _indexOf(out, noise), "frame before noise");
        assertLt(_indexOf(out, noise), _indexOf(out, heart), "noise before heart");
    }

    function test_aRestingTokenNeverPales() public view {
        // A sealed token keeps the colour it stopped at, however long ago that
        // was. A live one with the same clock does not.
        TokenView memory sealed_ = _view(365, 140, 1000, 9999);
        sealed_.resting = true;
        TokenView memory live = _view(365, 140, 1000, 9999);
        TokenView memory fresh = _view(365, 140, 1000, 1000);

        assertEq(r.svg(sealed_), r.svg(fresh), "a sealed token holds its colour");
        assertTrue(
            keccak256(bytes(r.svg(live))) != keccak256(bytes(r.svg(fresh))),
            "a live token that stopped checking in must pale"
        );
    }

    function test_sunsetFreezesTheSameWayRestingDoes() public view {
        TokenView memory sunset = _view(365, 140, 1000, 9999);
        sunset.sunset = true;
        TokenView memory fresh = _view(365, 140, 1000, 1000);
        assertEq(r.svg(sunset), r.svg(fresh), "sunset freezes the image too");
    }

    function test_theRendererIsReachableThroughItsInterface() public view {
        // The token contract holds an address behind IRenderer, so the concrete
        // contract has to satisfy it.
        IRenderer iface = IRenderer(address(r));
        assertGt(bytes(iface.tokenURI(_view(200, 45, 1000, 1000))).length, 0, "no output through the interface");
    }

    function test_theWorstCaseStaysInsideTheHardLimit() public view {
        // Ten rings and every Mark: the largest image a token can reach. The
        // spike's hard limit is 2,000,000 gas and 20,000 bytes.
        // Logged whether or not they pass, so the results table can be filled
        // from a test run rather than from a one-off probe. Run with -vv.
        string[4] memory labels =
            ["day one          ", "whole, one ring  ", "ten years, capped", "cap + all Marks  "];
        TokenView[4] memory vs = [
            _view(1, 1, 1000, 1000),
            _view(365, 140, 1000, 1000),
            _view(365 * 10, 400, 1000, 1000),
            _view(365 * 10, 400, 1000, 1000)
        ];
        vs[3].marks = ALL_MARKS;

        for (uint256 i; i < 4; ++i) {
            uint256 before = gasleft();
            string memory uri = r.tokenURI(vs[i]);
            uint256 used = before - gasleft();
            console.log("%s  %s gas  %s bytes", labels[i], used, bytes(uri).length);
            if (_gasIsMeaningful()) {
                assertLt(used, 2_000_000, "the worst case overruns the gas limit");
            }
            assertLt(bytes(uri).length, 20_000, "the worst case overruns the byte limit");
        }
    }

/// @dev Gas is only meaningful on the profile that ships. `forge coverage`
    /// cannot use the IR pipeline (foundry-rs/foundry#13001), so [profile.coverage]
    /// turns off both via_ir and the optimiser -- and the same source then costs
    /// roughly two and a half times as much. Asserting a gas ceiling against that
    /// build measures the coverage profile, not the contract, so the ceiling is
    /// skipped there. The numbers are still logged, and byte lengths, which the
    /// optimiser does not touch, are still asserted.
    function _gasIsMeaningful() internal view returns (bool) {
        return keccak256(bytes(vm.envOr("FOUNDRY_PROFILE", string("default"))))
            != keccak256(bytes("coverage"));
    }

    function _indexOf(string memory haystack, string memory needle) internal pure returns (uint256) {
        bytes memory h = bytes(haystack);
        bytes memory n = bytes(needle);
        for (uint256 i; i + n.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j; j < n.length; ++j) {
                if (h[i + j] != n[j]) { hit = false; break; }
            }
            if (hit) return i;
        }
        revert("not found");
    }

    /// @dev Byte index of the LAST occurrence, or the string length if absent.
    function _lastIndexOf(string memory hay, string memory needle) internal pure returns (uint256) {
        bytes memory h = bytes(hay);
        bytes memory k = bytes(needle);
        uint256 found = h.length;
        for (uint256 i = 0; i + k.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j = 0; j < k.length; ++j) {
                if (h[i + j] != k[j]) { hit = false; break; }
            }
            if (hit) found = i;
        }
        return found;
    }

    /// @dev Byte index of the first occurrence at or after `from`, or the string
    /// length if absent.
    function _indexOfFrom(string memory hay, string memory needle, uint256 from)
        internal pure returns (uint256)
    {
        bytes memory h = bytes(hay);
        bytes memory k = bytes(needle);
        for (uint256 i = from; i + k.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j = 0; j < k.length; ++j) {
                if (h[i + j] != k[j]) { hit = false; break; }
            }
            if (hit) return i;
        }
        return h.length;
    }

    /// @notice Static may change the ink and nothing else.
    ///
    /// @dev The Mark claims the noise, which is the one surface no other Mark
    /// touches. `CodeRenderer.paths` already takes that ink as a parameter, so
    /// wearing the Mark swaps one seven-character hex colour for another and the
    /// image cannot change length. If it ever does, the Mark has reached a
    /// surface that belongs to somebody else -- which is the rule that keeps a
    /// token wearing every drawing Mark legible.
    function test_staticChangesTheInkAndNothingElse() public view {
        TokenView memory v = _view(200, 45, 1000, 1000);
        string memory bare = r.svg(v);

        v.marks = MarkRenderer.STATIC;
        string memory marked = r.svg(v);

        assertTrue(
            keccak256(bytes(bare)) != keccak256(bytes(marked)),
            "Static must actually change the image"
        );
        assertEq(
            bytes(marked).length, bytes(bare).length,
            "a colour swap cannot change the image length"
        );
        assertTrue(
            vm.contains(marked, Palette.staticAt(Palette.tierIndex(45))),
            "the green ink is missing from a Static token"
        );
        assertFalse(
            vm.contains(marked, Palette.noiseAt(Palette.tierIndex(45))),
            "the neutral noise ink survived into a Static token"
        );
    }
}
