// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs 1 example.com
pragma solidity ^0.8.30;

/// @notice Every state in the render matrix, with the byte length and
/// keccak256 of the tokenURI tools/render-token.mjs produces for it.
/// Token 1 on example.com.
library RenderFixture {
    struct Case {
        uint32 level;
        uint32 streak;
        uint32 lastDay;
        uint32 today;
        uint256 marks;
        bool resting;
        bool sunset;
        uint32 sunsetDay;
        uint16 fellRun;
        uint24 fellDay;
        uint256 bytesLen;
        bytes32 hash;
        string label;
    }

    uint256 internal constant COUNT = 56;

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
        c[i++] = Case(365, 0, 1000, 1000, 0, false, false, 0, 0, 0, 8911, 0x7165496aaa5b85d2cde595dfbab2d7900169c5fbcd8942a2694b327dd7526e5a, "tier streak 0");
        c[i++] = Case(365, 0, 1000, 1030, 0, false, false, 0, 0, 0, 8911, 0x0cbb32547ef98109c09307a723a4bc8098abf2dd3060813748ef3c3c315ede6d, "tier streak 0, 30 days lapsed");
        c[i++] = Case(365, 3, 1000, 1000, 0, false, false, 0, 0, 0, 8911, 0x8cd876df3c73138370211edef6b5c61c9b5c404f386cd9b6d149e203239ab558, "tier streak 3");
        c[i++] = Case(365, 3, 1000, 1030, 0, false, false, 0, 0, 0, 8911, 0x2a2a679f40a4b7c323a9361946e65609d775298ed01358ec95709df27bb28e97, "tier streak 3, 30 days lapsed");
        c[i++] = Case(365, 7, 1000, 1000, 0, false, false, 0, 0, 0, 8911, 0xfd59718094397259f06c872541703e4c6f18928fe2a446841873cfec4925c2c4, "tier streak 7");
        c[i++] = Case(365, 7, 1000, 1030, 0, false, false, 0, 0, 0, 8911, 0x33e45ef95bcb41141ae82ef3115abcfd509a6a440775dd040b04acf73c08dea6, "tier streak 7, 30 days lapsed");
        c[i++] = Case(365, 30, 1000, 1000, 0, false, false, 0, 0, 0, 8912, 0xf9c08de6a24d013892e6c7728311a2c257ff8ded289337dadc2a908e5fc9c08d, "tier streak 30");
        c[i++] = Case(365, 30, 1000, 1030, 0, false, false, 0, 0, 0, 8912, 0xf7b0d1561ae62686d0f9833ac60be3e8f70354f8422bae93a02225b9b572ee82, "tier streak 30, 30 days lapsed");
        c[i++] = Case(365, 100, 1000, 1000, 0, false, false, 0, 0, 0, 8913, 0x82c2b7a7f6342d45dc3f66835b44f572ad9a771be166efb0351777a8fa2e1406, "tier streak 100");
        c[i++] = Case(365, 100, 1000, 1030, 0, false, false, 0, 0, 0, 8913, 0xe40b86e84cdfa7b2c8e92b7287e46ee99faf31fcc34422623efd1491828af63d, "tier streak 100, 30 days lapsed");
        c[i++] = Case(1, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8860, 0xe07a5009e5c263788207b776138e8299331e7ed3e286df5ce932a0594ffa2c8b, "0 years");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8913, 0xd9098ca34cd3f4f125845a3710ec2a3f05a42fb6acdeca597b3680f478d0d658, "1 years");
        c[i++] = Case(730, 400, 1000, 1000, 0, false, false, 0, 0, 0, 9065, 0xdc83fbea62b6a75b18e09d9f84e0e6f2b2b35989f9e9bc22e2c24f7419974102, "2 years");
        c[i++] = Case(1825, 400, 1000, 1000, 0, false, false, 0, 0, 0, 9370, 0x53e1a3d6bf70783ed7c61771979edc938f7162fc83b804e9f67008b453fa712b, "5 years");
        c[i++] = Case(3285, 400, 1000, 1000, 0, false, false, 0, 0, 0, 9702, 0xe66beac0bbeb83d6d1c358c4e3b0cd6fb8643b396e94d1f115dcfd40d30eedc4, "9 years");
        c[i++] = Case(3650, 400, 1000, 1000, 0, false, false, 0, 0, 0, 9783, 0x4bde6972e8d158bb33392cd8799fbf119b666bc4af6d754355b764914e722092, "10 years");
        c[i++] = Case(4015, 400, 1000, 1000, 0, false, false, 0, 0, 0, 9783, 0xdd260b23ecca3b26a8f8b06a2e198bdc720ceff38ea7fc4fa51f7b95bc1b5346, "11 years");
        c[i++] = Case(1, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8860, 0xe07a5009e5c263788207b776138e8299331e7ed3e286df5ce932a0594ffa2c8b, "fill 1");
        c[i++] = Case(12, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8898, 0x1f9e3c31877e04b532019b940afec7352b8a474265e87a44f6b184ddb0c3e215, "fill 12");
        c[i++] = Case(200, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8860, 0xcb437493db4758c5be998cbc7fd76d0f2fcaf14c83f369969085ab9c59f13b62, "fill 200");
        c[i++] = Case(364, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8904, 0x5d8dd04df1b289d43c9fc0548c0a50aef6b9960c62dc68c14a5dca12f2158688, "fill 364");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8913, 0xd9098ca34cd3f4f125845a3710ec2a3f05a42fb6acdeca597b3680f478d0d658, "fill 365");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 0, 0, 0, 8913, 0xd9098ca34cd3f4f125845a3710ec2a3f05a42fb6acdeca597b3680f478d0d658, "no marks");
        c[i++] = Case(365, 400, 1000, 1000, 4, false, false, 0, 0, 0, 8919, 0x8fd7a2ed3659f76b1d425b0d90b9c1c306d75d594f2ce8ffad9fb453cc998b8b, "mark ache");
        c[i++] = Case(365, 400, 1000, 1000, 2, false, false, 0, 0, 0, 8995, 0xbb294f87a42580da8aaff9f0daa107b08c4192ef831f2afa0a0da43c51bacce9, "mark hush");
        c[i++] = Case(365, 400, 1000, 1000, 16, false, false, 0, 0, 0, 9131, 0xeef7a8fb896eb9f29379c3485827cd7902d22a61868e37f7b2660502681e58a5, "mark beat");
        c[i++] = Case(365, 400, 1000, 1000, 1024, false, false, 0, 0, 0, 8919, 0x4f87623b9bb4533a32a25f1cdea922943e19c4c69dbda43fda21fdd84b2fad0a, "mark aura");
        c[i++] = Case(365, 400, 1000, 1000, 128, false, false, 0, 0, 0, 8921, 0x103463e721ae2ac3bdd5a9d14e80ac59ce5f2e0f813667e62093b7efcf3f3756, "mark vessel");
        c[i++] = Case(365, 400, 1000, 1000, 1174, false, false, 0, 0, 0, 9237, 0x105162870e74ef11d88cad1176061c1eb0935cd85a84642e6f80179853c3d352, "all drawing marks");
        c[i++] = Case(365, 400, 1000, 1000, 1438, false, false, 0, 0, 0, 9254, 0x806a1f8b94519565bf33aa27eb28d30bed836123abe07b9061859c9c170e47b3, "all seven marks");
        c[i++] = Case(365, 400, 1000, 1000, 65568, false, false, 0, 0, 0, 9962, 0xfc21f6752fc557a01c0444548c7b50e6935cb188c35fb903104dfebac2d8e989, "iris squircle");
        c[i++] = Case(365, 400, 1000, 1000, 131104, false, false, 0, 0, 0, 10382, 0x2904603eef8a70e6b945fd5a194fae60bf2d201afae8c686fa006ccee1b10e4a, "iris leaf");
        c[i++] = Case(365, 400, 1000, 1000, 544, false, false, 0, 0, 0, 9819, 0xc0607acbb9b3f77b98108a74d8833de3e23ab3d06077a248cb461253d46be96b, "tint violet");
        c[i++] = Case(365, 400, 1000, 1000, 16777760, false, false, 0, 0, 0, 9819, 0x331484e56016c8a38548b8ac55a29fb11a1ab5d8f562990e134d657f1ac3daa9, "tint gold");
        c[i++] = Case(365, 100, 1000, 1030, 429496729664, false, false, 0, 0, 0, 9850, 0xa54cdf5a152ab95a6cf79738bd29fe0e42a6d0f529d48468ae4a5322fbe23c3a, "earned iris, lapsed to the start tier");
        c[i++] = Case(365, 400, 1000, 1000, 1056, false, false, 0, 0, 0, 9819, 0xcf4fe205334fcddabc05f8fc2c8d9931b403fa8e706eb6d9550a3e911fcdc7ca, "iris on aura, no hush");
        c[i++] = Case(365, 100, 1000, 1000, 429513507392, false, false, 0, 0, 0, 9857, 0x19eab682a013f6b9f6c00e82b60e552a579e1e055989a4a1352b4991897276b8, "tint on earned iris");
        c[i++] = Case(365, 400, 1000, 1000, 256, false, false, 0, 0, 0, 8920, 0x9352bcc960fe594f6ce7ce9b3ff8b6ece43245a73bc4d22a7577dd5f1dc62870, "break alone");
        c[i++] = Case(365, 400, 1000, 1000, 264, false, false, 0, 0, 0, 8929, 0xa017b02513a76a22ceeae0e06614039f39fe024b0a574c14c03915f4fb7b2a4d, "break with static");
        c[i++] = Case(365, 400, 1000, 1000, 272, false, false, 0, 0, 0, 9139, 0xd7f388b471f4299c0d749f8c5a40ef114ca42e1aab4d83ebb8de5f42e80083a9, "break with beat");
        c[i++] = Case(365, 400, 1000, 1000, 8, false, false, 0, 0, 0, 8921, 0x9de652d686e7b4c60aec3189a17e8377641b63b106b9f29b88e7437255b92241, "mark static");
        c[i++] = Case(365, 100, 1000, 1030, 429496729920, false, false, 0, 0, 0, 9858, 0xf8fd228ea1392a9803ee36fce8c83653b67bdbb7ca846797831c8b051a51713d, "break on earned iris, lapsed to the start tier");
        c[i++] = Case(1, 1, 1000, 1029, 0, false, false, 0, 0, 0, 8858, 0xea28a05e5dd4706abd4244cbd4ff692bb82e678a4d395308ee4c9e0e7a7ddb37, "never returned, 29 days");
        c[i++] = Case(1, 1, 1000, 1030, 0, false, false, 0, 0, 0, 8858, 0x4ec7f7e7bf3c4e5484b753e482b40bdebb0c5c39e48dc1533a8f75bf95332091, "never returned, 30 days");
        c[i++] = Case(1, 1, 1000, 1365, 0, false, false, 0, 0, 0, 8858, 0x456fb845a45d72bf6d2e4bfbf702ed21709d791f67ece3509fc2ca0750ebab26, "never returned, a year");
        c[i++] = Case(1, 1, 1000, 2095, 0, false, false, 0, 0, 0, 8858, 0x456fb845a45d72bf6d2e4bfbf702ed21709d791f67ece3509fc2ca0750ebab26, "never returned, three years");
        c[i++] = Case(1, 1, 1000, 1365, 4, false, false, 0, 0, 0, 8864, 0xcc8f28d7a4e99a5a2794f30d2f6c5debdbb6f2343e71ae6da4c12ce829da6db9, "ache, never returned, a year");
        c[i++] = Case(1, 1, 1000, 1365, 1024, false, false, 0, 0, 0, 8864, 0x909a7c199c9debfe8d7569fd72c74aaedda0ff3d2884291491c7ab2de9a380d8, "aura, never returned, a year");
        c[i++] = Case(365, 400, 1000, 9999, 0, true, false, 0, 0, 0, 8916, 0x808b2d13cb5c7a79652f5cb90bba522629b292986bbe937aa5d14a60fd43c09e, "resting");
        c[i++] = Case(365, 400, 1000, 9999, 0, false, true, 0, 0, 0, 8916, 0x5d30aee92e26ce34e1027d8768f003ec1855aa5d504c21d880209ae191bf1b56, "sunset");
        c[i++] = Case(365, 400, 1000, 9999, 0, false, true, 1040, 0, 0, 8916, 0x0bdf3a5b910142dd95606206a4a0947c48edf0763cd75d6086fb33f14eaa7048, "sunset after this token lapsed");
        c[i++] = Case(365, 1, 1002, 1002, 0, false, false, 0, 400, 1000, 8911, 0xf8d280c7223928cc516b1d5557442a8f1ef72f4cc8cdeadf5549ea2848e6fcce, "slipped, day of return");
        c[i++] = Case(365, 4, 1005, 1005, 0, false, false, 0, 400, 1000, 8911, 0x24f16447a2870f5e527348d2b3a34b6ce740d19733493a3c983978833dc65a86, "slipped, 3 days on");
        c[i++] = Case(365, 8, 1009, 1009, 0, false, false, 0, 400, 1000, 8911, 0x93553e51190fb047d719ae78c943132145950645dc939063861e181e2b32c602, "slipped, 7 days on");
        c[i++] = Case(365, 31, 1032, 1032, 0, false, false, 0, 400, 1000, 8912, 0x4ebcd79943f72b71e31d2a9b5ef279d267eb16ec3c98847a03a481560e3e6abf, "slipped, 30 days on");
        c[i++] = Case(365, 100, 1100, 1100, 0, false, false, 0, 400, 1000, 8913, 0x17cb8f701ddeb91a557b0473f503e48f2fa4ea152c0640c53548afe322cf0c0b, "slipped, new run overtakes the fall");
    }
}
