// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test, console} from "forge-std/Test.sol";
import {Renderer} from "../src/render/Renderer.sol";
import {IRenderer} from "../src/render/IRenderer.sol";
import {FrameRenderer} from "../src/render/FrameRenderer.sol";
import {MarkRenderer} from "../src/render/MarkRenderer.sol";
import {Palette} from "../src/render/Palette.sol";
import {TokenView} from "../src/render/TokenView.sol";

/// @notice The assembled image and metadata, and the differential check that
/// keeps this renderer and the JS reference from drifting apart.
contract RendererTest is Test {
    Renderer r;

    /// @dev Token 1 on example.com, the same bitmap CodeRenderer.t.sol uses.
    /// Generated by tools/token-bitmap.mjs.
    function _bitmap() internal pure returns (bytes memory) {
        return
        hex"fe7f926bb8df3fc116bae8ac88906e9d1d71e35bcbb757fff47edfa5dbafffffe6f7d2ec13ebaf1bf3f107fa"
        hex"aaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebcfbfbf9efffff"
        hex"fe7f9bb78beffffebbe9af7efff5c71df04ffefbfffffffffdff3fffffffddfddf3effffebbfbbfbfffeeefb"
        hex"bbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffff"
        hex"ffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37"
        hex"fb7bfeeb6fbbfae62e7fffbfddfcc92e7fffffffff7722dfdc7ddf9dfbd68feeb6fb9dbcecbffffdbffefbee"
        hex"0ffffffbfb727b7e7dc7ddfdfb48c93fff7ffffeb9737fffbfddfd6e4e4dffffbfbb336fadeeffbbbb6bef17"
        hex"eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11aeb6fbbfaa8032d1bbfffabfc806401"
        hex"51beb0c7bfb0187ade0c2b905c377c5eecf11ba3096fe8120ff5d0c265706c9af2e9f2aedba037bf05c26b87"
        hex"9ae9c0fede58a39525f100";
    }

    /// @dev One Mark per pair -- the legal maximum a real token can hold, since
    /// `MachineReadableOnly.applyMark` excludes pair partners. Hush over Ache
    /// and Beat over Static were picked because they draw the larger amount of
    /// image (Hush adds a rect, Beat adds a gradient defs block), which makes
    /// this also the byte-worst-case fixture -- WHICH IT IS NOT, and that is
    /// worth saying: this set uses the default Iris shape and Aura, while the
    /// byte worst case is GasBudget.t.sol's MAX_MARKS (leaf shape, Tint),
    /// measured at 11,550 bytes against this fixture's 10,976. Iris Bought is
    /// included and it DRAWS -- test_theEyesAreDrawnLastOverTheNoise depends on
    /// exactly that -- so the fixture reflects a token that took
    /// every pair rather than four of five.
    uint256 constant ALL_MARKS = MarkRenderer.HUSH | MarkRenderer.BEAT
        | MarkRenderer.IRIS_BOUGHT | MarkRenderer.VESSEL | MarkRenderer.AURA;

    /// The same five surfaces with Tint taken instead of Aura -- the other side
    /// of pair five, and the side that carries an ink choice.
    uint256 constant ALL_MARKS_TINTED = MarkRenderer.HUSH | MarkRenderer.BEAT
        | MarkRenderer.IRIS_BOUGHT | MarkRenderer.VESSEL | MarkRenderer.TINT;

    function setUp() public {
        r = new Renderer();
    }

    function _view(uint32 level, uint32 streak, uint32 lastDay, uint32 today)
        internal
        pure
        returns (TokenView memory v)
    {
        v.tokenId = 1;
        v.level = level;
        v.streak = streak;
        v.lastDay = lastDay;
        v.today = today;
        v.mintDay = 900;
        v.code = _bitmap();
    }

    // ---------------------------------------------------------------------
    // The differential check. This is the important test in this file.
    // ---------------------------------------------------------------------
    //
    // Hashes rather than the strings themselves, because one tokenURI is around
    // 10,000 bytes. The byte length is asserted alongside each hash so a failure
    // says whether the two renderers disagree on length or only on content.
    //
    // Regenerate with: node tools/token-uri-fixture.mjs

    function _diff(string memory label, TokenView memory v, uint256 len, bytes32 hash) internal view {
        string memory uri = r.tokenURI(v);
        assertEq(bytes(uri).length, len, string.concat(label, ": byte length differs from the reference"));
        assertEq(keccak256(bytes(uri)), hash, string.concat(label, ": content differs from the reference"));
    }

    function test_dayOneMatchesTheJavascriptReference() public view {
        _diff("day one", _view(1, 1, 1000, 1000), 14706,
            0xf120dcc8abb64a7af7962becc7c0a3e4545cb371498a8230ae627c8316a5e6c5);
    }

    function test_aPartYearMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.agentKeyId = bytes32(uint256(0xa9e));
        _diff("day 200", v, 14711,
            0x60fd404af2edaf50ac137ac314adac319a30a93a44603e825043ca5f42228b97);
    }

    function test_aWholeHeartMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365, 140, 1000, 1000);
        v.generation = 1;
        v.parent = 7;
        v.seedsGiven = 2;
        _diff("whole, one ring", v, 14725,
            0xbb9cd57f6b70e2411c693879e662613cf369af219a53f37c04553b3945014a9f);
    }

    function test_aLapsedTokenMatchesTheJavascriptReference() public view {
        // Forty days without a check-in, ONE DAY SHORT OF WHOLE. This is the
        // case that caught a real divergence: the JS renderer had a lapse
        // function it never called, so the image never paled while this
        // renderer's did. It was level 365 until Spec 10f, which is now a token
        // that cannot lapse at all -- at 364 the lapse is measured again.
        _diff("lapsed, one day short", _view(364, 140, 1000, 1040), 14756,
            0xfaff44e9c318b366447298b89f442bbf9d367eaddaf612e70a85374826e06221);
    }

    /// The finish freezes the token on its last credited day, and this is the
    /// case that says the freeze runs the ordinary lapse rules with the clock
    /// stopped rather than short-circuiting to the stored run: a token that
    /// slipped during its year must not be un-paled by finishing it. Replaces
    /// the ten-year ring-cap case, which the chain can no longer produce.
    function test_aFinishedTokenAfterASlipMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365, 5, 1000, 1400);
        v.fellRun = 200;
        v.fellDay = 900;
        _diff("finished after a slip", v, 14723,
            0x313b3e448c2ecd4dc00f4cf77d8ead93bcd3a5203011cc344500f00cccf8d8b6);
    }

    function test_everyMarkAtOnceMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365, 400, 1000, 1000);
        v.marks = ALL_MARKS;
        _diff("every drawn mark", v, 15930,
            0x890c5bfd06ea786fa30c51ecd257f56a0fccdb2913f3439c806474a8af688cd3);
    }

    function test_aSealedTokenMatchesTheJavascriptReference() public view {
        // Level 300, not whole: a finished token freezes on its own, so resting
        // a whole one would prove nothing about `resting`.
        TokenView memory v = _view(300, 200, 1000, 9999);
        v.resting = true;
        _diff("sealed at rest", v, 14759,
            0x274040460cb491e8166c7113a366a73f2e93b96e8258f98311235065de3cadb4);
    }

    /// A seeded child, at both extremes of the echo ring.
    ///
    /// These were once the ONLY cross-language check on the dashed ring at the
    /// whole-tokenURI level, because the render matrix carried no `echo` field
    /// and every case in RenderFixture and CombinationFixture rendered a
    /// founding token. That is no longer true: the matrix now carries seven
    /// seeded children and the combination fixture ten more, one per
    /// echo-sensitive drawing site.
    ///
    /// They are kept because they are not redundant. These two are the
    /// EXTREMES -- the smallest canvas the piece draws and the ring cap -- and
    /// they are written by hand, so they fail with a name rather than as case
    /// number 57 of 63. Verified 2026-09-07 by setting the dash period to 5 in
    /// FrameRenderer: these went red, and so did both fixtures.
    function test_aNewbornChildMatchesTheJavascriptReference() public view {
        // Level 1, so the token has no ring of its own: the echo ring is the
        // outermost thing on the smallest canvas the piece draws, 53 cells.
        TokenView memory v = _view(1, 1, 1000, 1000);
        v.generation = 1;
        v.parent = 7;
        v.echo = 365;
        _diff("a newborn child", v, 15668,
            0x40471f087b61ae465d12014e759ae09e374abf3fbc15a0332c4e1cfa14c79e60);
    }

    function test_aFinishedChildMatchesTheJavascriptReference() public view {
        // Its own finishing ring plus the echo ring, so the dash sits at depth
        // 2 -- one slot inside its own ring, and the deepest it can now go.
        // Before Spec 10f this case was a nine-ring child with the echo at
        // depth 18.
        TokenView memory v = _view(365, 400, 1000, 1000);
        v.generation = 2;
        v.parent = 7;
        v.echo = 3650;
        _diff("a finished child", v, 15736,
            0x45f05fa99bbdec4787b7fedb0fff3fdaa8f1fb0aac49db560301ab4b3d27109c);
    }

    /// A child wearing the maximal LEGAL Mark set.
    ///
    /// Fix round 1. The other two child cases are Mark-free, and TWO of the six
    /// `_blockOff` call sites are Mark-gated: `_eyes` returns early when no
    /// Iris is worn, and `_quiet` returns "" when Hush is not. So neither was
    /// ever reached with a non-zero echo, and a regression at either would have
    /// shipped green. A misplaced Hush rect paints a 45-cell cream square over
    /// the code and kills the decode.
    ///
    /// Five Marks is the legal maximum -- the exclusive pairs make six
    /// unreachable. Level 365 -- finished -- because that is where the echo
    /// ring still discriminates: `rings(365, 1825)` is 2 against
    /// `rings(365, 0)`'s 1, so a broken site computes a different offset. The
    /// heart is also whole, so the ghost element exists ONLY to carry the echo
    /// ring.
    function test_aChildWithEveryDrawnMarkMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365, 400, 1000, 1000);
        v.generation = 2;
        v.parent = 7;
        v.echo = 365 * 5;
        // The bought Iris in leaf (shape 2) and Tint in gold (ink 1). Both
        // non-default on purpose, so the shape and ink bits are read rather
        // than defaulting to 0. Mirrors the packing applyMark writes.
        v.marks = ALL_MARKS_TINTED | (uint256(2) << 16) | (uint256(1) << 24);
        _diff("a child with every drawn mark", v, 17515,
            0xa10dbcc000939fa6ef20f14d978a3e174b2ef6a0e92d51bd4787ef5ac317f109);
    }

    function test_theEyesAreDrawnLastOverTheNoise() public view {
        // A Static + Iris token: Static already recolours the finder patterns,
        // because they are ordinary code modules. The eyes must land ON TOP of that
        // and the erase-to-ground step is what makes it clean rather than a green
        // square with a shape on it.
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.marks = MarkRenderer.STATIC | MarkRenderer.IRIS_BOUGHT;   // shape 0, target
        string memory s = r.svg(v);
        // The code block is the LAST TWO <path> elements. Everything after them is
        // eyes, so the tail of the SVG must open with the first eye's erase rect.
        uint256 lastPath = _lastIndexOf(s, "<path fill=");
        uint256 firstEye = _indexOfFrom(s, '<rect x=', lastPath);
        assertLt(lastPath, firstEye, "the eyes must be emitted after the code paths");
        assertLt(firstEye, bytes(s).length, "no eyes were emitted at all");
    }

    function test_tintOverridesTheUntintedEyeInk() public view {
        // Untinted, the bought Iris draws in the token's own heart colour.
        // Tint replaces it -- variant 0 violet, variant 1 gold -- regardless
        // of what the live rung would otherwise put there.
        TokenView memory v = _view(200, 45, 1000, 1000);
        uint256 base = MarkRenderer.IRIS_BOUGHT | MarkRenderer.TINT;

        v.marks = base;   // variant 0 -> violet
        string memory violet = r.svg(v);
        assertTrue(vm.contains(violet, "#9800fc"), "Tint variant 0 must draw violet eyes");

        v.marks = base | (uint256(1) << 24);   // variant 1 -> gold
        string memory gold = r.svg(v);
        assertTrue(vm.contains(gold, "#b8860b"), "Tint variant 1 must draw gold eyes");

        assertTrue(
            keccak256(bytes(violet)) != keccak256(bytes(gold)),
            "the two Tint variants must produce different images"
        );
    }

    function test_theEarnedIrisEyeKeepsItsStoredRunColourAndNeverLapses() public view {
        // The earned Iris was applied at a 100-day run -- the top tier -- and
        // must keep drawing that colour even once the token has since lapsed
        // all the way back down to the start tier. That is the whole point of
        // the Mark: it stops tracking the lapse.
        TokenView memory v = _view(200, 100, 1000, 1030);   // 30 days lapsed
        v.marks = MarkRenderer.IRIS_EARNED | (uint256(100) << 32);
        string memory out = r.svg(v);

        string memory storedColour = Palette.colourAt(Palette.tierIndex(100));
        string memory liveColour = Palette.colourAt(Palette.lapsedIndex(100, 1000, 1030));
        assertTrue(
            keccak256(bytes(storedColour)) != keccak256(bytes(liveColour)),
            "sanity: the live rung must actually differ from the stored run"
        );
        assertTrue(vm.contains(out, storedColour), "the earned Iris must draw in the run it was applied at");
    }

    function test_theIrisAttributesAppearOnlyWhenAnIrisIsWorn() public view {
        TokenView memory bare = _view(200, 45, 1000, 1000);
        string memory bareUri = r.tokenURI(bare);
        assertFalse(vm.contains(bareUri, "Iris Shape"), "no Iris Shape attribute without an Iris");
        assertFalse(vm.contains(bareUri, "Iris Run"), "no Iris Run attribute without an Iris");

        TokenView memory bought = _view(200, 45, 1000, 1000);
        bought.marks = MarkRenderer.IRIS_BOUGHT | (uint256(2) << 16);   // shape 2, leaf
        string memory boughtUri = r.tokenURI(bought);
        assertTrue(
            vm.contains(boughtUri, '{"trait_type":"Iris Shape","value":"leaf"}'),
            "the bought route must name its shape"
        );
        assertFalse(vm.contains(boughtUri, "Iris Run"), "the bought route has no run to report");

        TokenView memory earned = _view(200, 45, 1000, 1000);
        earned.marks = MarkRenderer.IRIS_EARNED | (uint256(365) << 32);
        string memory earnedUri = r.tokenURI(earned);
        assertTrue(
            vm.contains(earnedUri, '{"trait_type":"Iris Shape","value":"target"}'),
            "the earned route is always target"
        );
        assertTrue(
            vm.contains(earnedUri, '{"trait_type":"Iris Run","value":365}'),
            "the earned route must report its stored run"
        );
    }

    // ---------------------------------------------------------------------
    // The wrapper's own rules
    // ---------------------------------------------------------------------

    function test_noRawHashSurvivesIntoTheUri() public view {
        // The whole tokenURI is itself a URI, so one raw "#" opens a fragment
        // and truncates the JSON. Base64 hides every hash inside the SVG; the
        // one in the name is written %23. Beat is worn here because its
        // url(#b) reference is the easiest one to leak.
        TokenView memory v = _view(365, 140, 1000, 1000);
        v.marks = MarkRenderer.BEAT;
        bytes memory uri = bytes(r.tokenURI(v));
        for (uint256 i; i < uri.length; ++i) {
            assertTrue(uri[i] != "#", "a raw hash reached the tokenURI");
        }
    }

    function test_theJsonIsUtf8AndOnlyTheImageIsBase64() public view {
        string memory uri = r.tokenURI(_view(365, 140, 1000, 1000));
        assertTrue(
            vm.contains(uri, "data:application/json;utf-8,{"),
            "the JSON must be served as plain utf-8"
        );
        assertTrue(vm.contains(uri, "data:image/svg+xml;base64,"), "the image must be base64");
    }

    function test_theImageIsDrawnInTheFixedOrder() public view {
        // Ghost, frame, noise, heart. Fixed so each library emits one adjacent
        // pair of paths and the assembler can simply concatenate them.
        //
        // Vessel is worn so the frame is gold and the four fills are four
        // distinct strings. On a bare token the frame and the heart share the
        // streak colour, and searching for it would find the frame every time.
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.marks = MarkRenderer.VESSEL;
        string memory out = r.svg(v);

        // Both inks are read off the palette rather than pasted in. They are a
        // matched pair now -- one per rung -- so a hardcoded noise here would
        // rot the moment a tier is retuned, which is exactly what it did.
        uint256 rung = Palette.tierIndex(45);
        string memory heart = Palette.colourAt(rung);
        string memory noise = Palette.noiseAt(rung);

        assertLt(_indexOf(out, "#f4eef0"), _indexOf(out, "#b8860b"), "ghost before frame");
        assertLt(_indexOf(out, "#b8860b"), _indexOf(out, noise), "frame before noise");
        assertLt(_indexOf(out, noise), _indexOf(out, heart), "noise before heart");
    }

    function test_aRestingTokenNeverPales() public view {
        // A sealed token keeps the colour it stopped at, however long ago that
        // was. A live one with the same clock does not.
        //
        // Level 200, not 365: since Spec 10f a FINISHED token does not pale
        // either, so at 365 the control could not fail and this test would have
        // passed with `resting` doing nothing at all.
        TokenView memory sealed_ = _view(200, 140, 1000, 9999);
        sealed_.resting = true;
        TokenView memory live = _view(200, 140, 1000, 9999);
        TokenView memory fresh = _view(200, 140, 1000, 1000);

        assertEq(r.svg(sealed_), r.svg(fresh), "a sealed token holds its colour");
        assertTrue(
            keccak256(bytes(r.svg(live))) != keccak256(bytes(r.svg(fresh))),
            "a live token that stopped checking in must pale"
        );
    }

    /// A finished token's colour is the one it finished with, however long the
    /// calendar runs. Without this, a token that finished and then stopped
    /// checking in -- which is now the ONLY thing it can do, since `_credit`
    /// refuses a token at 365 -- would fade. Spec 10f.
    function test_aFinishedTokenDoesNotFade() public view {
        TokenView memory v = _view(365, 365, 20_000, 20_000);
        string memory atFinish = r.svg(v);
        v.today = 20_400;
        assertEq(r.svg(v), atFinish, "a finished token must hold the colour it finished with");
    }

    function test_sunsetFreezesTheSameWayRestingDoes() public view {
        // Level 200 for the same reason as the resting test above: at 365 the
        // finish would freeze the image whether `sunset` worked or not.
        TokenView memory sunset = _view(200, 140, 1000, 9999);
        sunset.sunset = true;
        TokenView memory fresh = _view(200, 140, 1000, 1000);
        assertEq(r.svg(sunset), r.svg(fresh), "sunset freezes the image too");
    }

    function test_theRendererIsReachableThroughItsInterface() public view {
        // The token contract holds an address behind IRenderer, so the concrete
        // contract has to satisfy it.
        IRenderer iface = IRenderer(address(r));
        assertGt(bytes(iface.tokenURI(_view(200, 45, 1000, 1000))).length, 0, "no output through the interface");
    }

    function test_theWorstCaseStaysInsideTheHardLimit() public view {
        // A finished child wearing every Mark: the largest image a token can
        // reach now the year ends at 365 and the rings stop at two. The spike's
        // hard limit is 4,000,000 gas and 24,000 bytes.
        // Logged whether or not they pass, so the results table can be filled
        // from a test run rather than from a one-off probe. Run with -vv.
        string[4] memory labels =
            ["day one          ", "whole, one ring  ", "finished child   ", "child + all Marks"];
        TokenView[4] memory vs = [
            _view(1, 1, 1000, 1000),
            _view(365, 140, 1000, 1000),
            _view(365, 400, 1000, 1000),
            _view(365, 400, 1000, 1000)
        ];
        vs[2].echo = 3650;
        vs[3].echo = 3650;
        vs[3].marks = ALL_MARKS;

        for (uint256 i; i < 4; ++i) {
            uint256 before = gasleft();
            string memory uri = r.tokenURI(vs[i]);
            uint256 used = before - gasleft();
            console.log("%s  %s gas  %s bytes", labels[i], used, bytes(uri).length);
            if (_gasIsMeaningful()) {
                // 3M since 2026-09-21 -- see TokenUriGolden.t.sol.
                assertLt(used, 4_000_000, "the worst case overruns the gas limit");
            }
            assertLt(bytes(uri).length, 24_000, "the worst case overruns the byte limit");
        }
    }

/// @dev Gas is only meaningful on the profile that ships. `forge coverage`
    /// cannot use the IR pipeline (foundry-rs/foundry#13001), so [profile.coverage]
    /// turns off both via_ir and the optimiser -- and the same source then costs
    /// roughly two and a half times as much. Asserting a gas ceiling against that
    /// build measures the coverage profile, not the contract, so the ceiling is
    /// skipped there. The numbers are still logged, and byte lengths, which the
    /// optimiser does not touch, are still asserted.
    /// @dev 2.M1. The Years ATTRIBUTE is computed from `level`, not from the
    /// ring budget. It was fed `FrameRenderer.rings()`, so a token in its
    /// eleventh year reported ten, and `Level` was the only surviving record of
    /// its age. The chain can no longer reach an eleventh year -- Spec 10f
    /// stops crediting at 365 -- so this is now a robustness assertion rather
    /// than a lifecycle one: the renderer is handed a `TokenView` by whatever
    /// calls it, and it must report what it was given rather than what the ring
    /// rule can draw. Asserted on the rendered TEXT, not on a recomputed number.
    function test_theYearsAttributeIsReadFromTheLevelNotTheRing() public view {
        string memory eleven = r.tokenURI(_view(365 * 11, 5, 1000, 1000));
        assertTrue(vm.contains(eleven, '{"trait_type":"Years","value":11}'), "eleven years must say eleven");
        assertTrue(vm.contains(eleven, '{"trait_type":"Level","value":4015}'));

        // The reachable control, so this is not an off-by-one dressed as a fix
        // -- and the drawn ring stops at one either way.
        string memory finished = r.tokenURI(_view(365, 5, 1000, 1000));
        assertTrue(vm.contains(finished, '{"trait_type":"Years","value":1}'));
        assertEq(FrameRenderer.rings(365 * 11, 0), 1, "the drawn ring still stops at one");
    }

    function _gasIsMeaningful() internal view returns (bool) {
        return keccak256(bytes(vm.envOr("FOUNDRY_PROFILE", string("default"))))
            != keccak256(bytes("coverage"));
    }

    function _indexOf(string memory haystack, string memory needle) internal pure returns (uint256) {
        bytes memory h = bytes(haystack);
        bytes memory n = bytes(needle);
        for (uint256 i; i + n.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j; j < n.length; ++j) {
                if (h[i + j] != n[j]) { hit = false; break; }
            }
            if (hit) return i;
        }
        revert("not found");
    }

    /// @dev Byte index of the LAST occurrence, or the string length if absent.
    function _lastIndexOf(string memory hay, string memory needle) internal pure returns (uint256) {
        bytes memory h = bytes(hay);
        bytes memory k = bytes(needle);
        uint256 found = h.length;
        for (uint256 i = 0; i + k.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j = 0; j < k.length; ++j) {
                if (h[i + j] != k[j]) { hit = false; break; }
            }
            if (hit) found = i;
        }
        return found;
    }

    /// @dev Byte index of the first occurrence at or after `from`, or the string
    /// length if absent.
    function _indexOfFrom(string memory hay, string memory needle, uint256 from)
        internal pure returns (uint256)
    {
        bytes memory h = bytes(hay);
        bytes memory k = bytes(needle);
        for (uint256 i = from; i + k.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j = 0; j < k.length; ++j) {
                if (h[i + j] != k[j]) { hit = false; break; }
            }
            if (hit) return i;
        }
        return h.length;
    }

    /// @notice Static may change the ink and nothing else.
    ///
    /// @dev The Mark claims the noise, which is the one surface no other Mark
    /// touches. `CodeRenderer.paths` already takes that ink as a parameter, so
    /// wearing the Mark swaps one seven-character hex colour for another and the
    /// image cannot change length. If it ever does, the Mark has reached a
    /// surface that belongs to somebody else -- which is the rule that keeps a
    /// token wearing every drawing Mark legible.
    function test_staticChangesTheInkAndNothingElse() public view {
        TokenView memory v = _view(200, 45, 1000, 1000);
        string memory bare = r.svg(v);

        v.marks = MarkRenderer.STATIC;
        string memory marked = r.svg(v);

        assertTrue(
            keccak256(bytes(bare)) != keccak256(bytes(marked)),
            "Static must actually change the image"
        );
        assertEq(
            bytes(marked).length, bytes(bare).length,
            "a colour swap cannot change the image length"
        );
        assertTrue(
            vm.contains(marked, Palette.staticAt(Palette.tierIndex(45))),
            "the green ink is missing from a Static token"
        );
        assertFalse(
            vm.contains(marked, Palette.noiseAt(Palette.tierIndex(45))),
            "the neutral noise ink survived into a Static token"
        );
    }
}
