// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs 1 example.com
pragma solidity ^0.8.30;

/// @notice Every state in the render matrix, with the byte length and
/// keccak256 of the tokenURI tools/render-token.mjs produces for it.
/// Token 1 on example.com.
library RenderFixture {
    struct Case {
        uint32 level;
        uint32 streak;
        uint32 lastDay;
        uint32 today;
        uint256 marks;
        bool resting;
        bool sunset;
        uint256 bytesLen;
        bytes32 hash;
        string label;
    }

    uint256 internal constant COUNT = 32;

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
        c[i++] = Case(365, 0, 1000, 1000, 0, false, false, 8847, 0x603cca57fa421b27d25f25c8d9072e4e35f7f8e71c1bc4bc05fb1818a8f4f91c, "tier streak 0");
        c[i++] = Case(365, 0, 1000, 1030, 0, false, false, 8847, 0x603cca57fa421b27d25f25c8d9072e4e35f7f8e71c1bc4bc05fb1818a8f4f91c, "tier streak 0, 30 days lapsed");
        c[i++] = Case(365, 3, 1000, 1000, 0, false, false, 8847, 0xde7c8f26e7fd23c6ab103660971453f5d274f9beaf4c5f612d5109fe9517fa08, "tier streak 3");
        c[i++] = Case(365, 3, 1000, 1030, 0, false, false, 8847, 0x4e80e1019d2db5c30c22e9dc16a1e85b34167b57c39faa2ebe9f78055848216d, "tier streak 3, 30 days lapsed");
        c[i++] = Case(365, 7, 1000, 1000, 0, false, false, 8847, 0x20a566c1262479e6b36c69a2b2b6ee385f2f71f181da0171413d054c8bbe3e6a, "tier streak 7");
        c[i++] = Case(365, 7, 1000, 1030, 0, false, false, 8847, 0xd5a0a0ac3708a7a3bbfa952d8473013b00448dbfc34b1d0d4fdc8d51c9d396b1, "tier streak 7, 30 days lapsed");
        c[i++] = Case(365, 30, 1000, 1000, 0, false, false, 8848, 0x57f97fbaec457035752a162c60fec539b87c00c408ed99593a9624ddb9babf9b, "tier streak 30");
        c[i++] = Case(365, 30, 1000, 1030, 0, false, false, 8848, 0x7d37791f568e75cc7c942df4e70ec499e4463f6c218996bc169802e1e7b13231, "tier streak 30, 30 days lapsed");
        c[i++] = Case(365, 100, 1000, 1000, 0, false, false, 8849, 0x60d998fa0eeb71a9d2fcc2c1e046b411abe5d83b38783e4ef95da1aeb0bd69cd, "tier streak 100");
        c[i++] = Case(365, 100, 1000, 1030, 0, false, false, 8849, 0x00178e7b9217f35b2317ebff51f409b136fad28731be06a9ca0374d7c0d39d19, "tier streak 100, 30 days lapsed");
        c[i++] = Case(1, 400, 1000, 1000, 0, false, false, 8792, 0x4f1acb7fe9130c989b9e4caee612fbae3b4560d2eed62627230e3b3459946d30, "0 years");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 8849, 0x124209caaf4596e135b72f786b769ad36364dd18fb485b46acde4af5717b1262, "1 years");
        c[i++] = Case(730, 400, 1000, 1000, 0, false, false, 8997, 0x12aeda4ce071646b04126742b59e01325448e1b41e70c3a36ffb7acdd211153f, "2 years");
        c[i++] = Case(1825, 400, 1000, 1000, 0, false, false, 9302, 0x2dd28fa40b9856774b17849d5aa0e99a99fddecf42b8e89a84d69eaf351e81e3, "5 years");
        c[i++] = Case(3285, 400, 1000, 1000, 0, false, false, 9634, 0x26346b850eb6920863abfa0fc266d15d02827cb4ad94761edd9f242e30095562, "9 years");
        c[i++] = Case(3650, 400, 1000, 1000, 0, false, false, 9715, 0x13436624752455693df20a735fad5ced5506e75da047e70737ee036c28556a9d, "10 years");
        c[i++] = Case(4015, 400, 1000, 1000, 0, false, false, 9715, 0xb03172514bd1dfd1756b6b94efac102fcbb99eb0d67d78348352799ba611d6cd, "11 years");
        c[i++] = Case(1, 400, 1000, 1000, 0, false, false, 8792, 0x4f1acb7fe9130c989b9e4caee612fbae3b4560d2eed62627230e3b3459946d30, "fill 1");
        c[i++] = Case(12, 400, 1000, 1000, 0, false, false, 8834, 0x4324c0def11a84986f990e9a6c24c7dc7d08ceaef93eef4b4008bccc2eecf134, "fill 12");
        c[i++] = Case(200, 400, 1000, 1000, 0, false, false, 8796, 0x19b5d3c6296703970749ea2d4e59d9ae53c638a759d4ba21e1c76b2f6e73d691, "fill 200");
        c[i++] = Case(364, 400, 1000, 1000, 0, false, false, 8840, 0xe2fa3da6448873a0f9c0d4ace45396d2f55efa2346b26515d9e9d4607e750f23, "fill 364");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 8849, 0x124209caaf4596e135b72f786b769ad36364dd18fb485b46acde4af5717b1262, "fill 365");
        c[i++] = Case(365, 400, 1000, 1000, 0, false, false, 8849, 0x124209caaf4596e135b72f786b769ad36364dd18fb485b46acde4af5717b1262, "no marks");
        c[i++] = Case(365, 400, 1000, 1000, 2, false, false, 8855, 0x065077c0e7fd9196ee1fdea72611accb82ec6104a843af5e5b3a86ac234f02f2, "mark vein");
        c[i++] = Case(365, 400, 1000, 1000, 8, false, false, 8932, 0x0ea48ef65140494194ba83fde834f78a4fbb6b295f1e29bd4833943757a1e34a, "mark voice");
        c[i++] = Case(365, 400, 1000, 1000, 16, false, false, 9068, 0xd100596248754236a6549c89e2780a3c37b77a63754efda085f097e5405229ab, "mark bloom");
        c[i++] = Case(365, 400, 1000, 1000, 32, false, false, 8855, 0x715154088a06534940ed15ee9fe162fc86f933c53c73dfdbc73520f05de8d02b, "mark halo");
        c[i++] = Case(365, 400, 1000, 1000, 64, false, false, 8856, 0x7258fdff77dd528e83d8040bc8373d22716475186c379abd8cb798ed20f6a805, "mark crown");
        c[i++] = Case(365, 400, 1000, 1000, 122, false, false, 9174, 0x1282708f18e3c8e3e981684912c1ddd79c731f4ee4732a65bea4bebc30d9cf4a, "all drawing marks");
        c[i++] = Case(365, 400, 1000, 1000, 254, false, false, 9196, 0x49e04a1f362388d5edfa15c809cef255cdc0cbebaf6f57a224f437fafc453ec5, "all seven marks");
        c[i++] = Case(365, 400, 1000, 9999, 0, true, false, 8852, 0xfd3ec80e599934f1a0c527fb0cf0adaf3dc6a710b19e25082c25b1699ad0a02e, "resting");
        c[i++] = Case(365, 400, 1000, 9999, 0, false, true, 8850, 0x9d4cd247b8a772ee140cb5bd37b1bfb0eb893082d279f5f191739356a2b63616, "sunset");
    }
}
