// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test, console} from "forge-std/Test.sol";
import {Renderer} from "../src/render/Renderer.sol";
import {IRenderer} from "../src/render/IRenderer.sol";
import {FrameRenderer} from "../src/render/FrameRenderer.sol";
import {MarkRenderer} from "../src/render/MarkRenderer.sol";
import {TokenView} from "../src/render/TokenView.sol";

/// @notice The assembled image and metadata, and the differential check that
/// keeps this renderer and the JS reference from drifting apart.
contract RendererTest is Test {
    Renderer r;

    /// @dev Token 1 on example.com, the same bitmap CodeRenderer.t.sol uses.
    /// Generated by tools/token-bitmap.mjs.
    function _bitmap() internal pure returns (bytes memory) {
        return
        hex"fe00810bfc16532d506ebd1a58bb74fffff5dbabfabfaec16ed7ed07faaaaaafe01fe9fe00d33eefebb3eeff"
        hex"fff37fff66f70afbdfedf8b7feeeeea0fefdffdf85ffef66e727bfffff6abfeefeef296ffdfff5fbfe666796"
        hex"e3fedfeb623feefee8d8ffffff86fff66f7362bdfedfd0b3eeeeea5bcfdffdda69bef66f8ac0fffff12f62ef"
        hex"ecfa0057dfec67fa66642bf04b6df716ba7aed8f95d52ffa2d2e9306943305132d230fe84883cd80";
    }

    uint256 constant ALL_MARKS = MarkRenderer.VEIN | MarkRenderer.PULSE | MarkRenderer.VOICE
        | MarkRenderer.BLOOM | MarkRenderer.HALO | MarkRenderer.CROWN | MarkRenderer.SINGULARITY;

    function setUp() public {
        r = new Renderer();
    }

    function _view(uint32 level, uint32 streak, uint32 lastDay, uint32 today)
        internal
        pure
        returns (TokenView memory v)
    {
        v.tokenId = 1;
        v.level = level;
        v.streak = streak;
        v.lastDay = lastDay;
        v.today = today;
        v.mintDay = 900;
        v.code = _bitmap();
    }

    // ---------------------------------------------------------------------
    // The differential check. This is the important test in this file.
    // ---------------------------------------------------------------------
    //
    // Hashes rather than the strings themselves, because one tokenURI is around
    // 10,000 bytes. The byte length is asserted alongside each hash so a failure
    // says whether the two renderers disagree on length or only on content.
    //
    // Regenerate with: node tools/token-uri-fixture.mjs

    function _diff(string memory label, TokenView memory v, uint256 len, bytes32 hash) internal view {
        string memory uri = r.tokenURI(v);
        assertEq(bytes(uri).length, len, string.concat(label, ": byte length differs from the reference"));
        assertEq(keccak256(bytes(uri)), hash, string.concat(label, ": content differs from the reference"));
    }

    function test_dayOneMatchesTheJavascriptReference() public view {
        _diff("day one", _view(1, 1, 1000, 1000), 8616,
            0x46cc67bfce84734d783bb39eebff3df264e5a1156e31f60ba8fb0418b4af7a1a);
    }

    function test_aPartYearMatchesTheJavascriptReference() public view {
        _diff("day 200", _view(200, 45, 1000, 1000), 8619,
            0x65c3d597b149beefa88e6cbff532e313dab813273573124c2dfa3f70dc0b9bc1);
    }

    function test_aWholeHeartMatchesTheJavascriptReference() public view {
        _diff("whole, one ring", _view(365, 140, 1000, 1000), 8665,
            0xdcc73a52bffcc1041a047fc3452e544cad1b6fdb546d9ab788014a065fadc4bb);
    }

    function test_aLapsedTokenMatchesTheJavascriptReference() public view {
        // Forty days without a check-in. This is the case that caught a real
        // divergence: the JS renderer had a lapse function it never called, so
        // the image never paled while this renderer's did.
        _diff("whole and lapsed", _view(365, 140, 1000, 1040), 8665,
            0x201dd62b27b2eb52e7230eec1da2c7f461e281766a6dd78f1e7b60f743460c53);
    }

    function test_theRingCapMatchesTheJavascriptReference() public view {
        _diff("ten years, capped", _view(365 * 10, 400, 1000, 1000), 9531,
            0xf6de7ed3f53b48a9171c558a9cb09b2298fb27400cc665a707469f72134a166d);
    }

    function test_everyMarkAtOnceMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365 * 10, 400, 1000, 1000);
        v.marks = ALL_MARKS;
        _diff("every drawn mark", v, 9882,
            0xfad6b25d9f788ceb1bc81c934f5e2befe45bae6b57ba8bfd1ccfe221c222c001);
    }

    function test_aSealedTokenMatchesTheJavascriptReference() public view {
        TokenView memory v = _view(365 * 3, 200, 1000, 9999);
        v.resting = true;
        _diff("sealed at rest", v, 8895,
            0xeb311c0c349f69d9922eda3e10a584008147016a8ed7bf632f22272df2f45b3e);
    }

    // ---------------------------------------------------------------------
    // The wrapper's own rules
    // ---------------------------------------------------------------------

    function test_noRawHashSurvivesIntoTheUri() public view {
        // The whole tokenURI is itself a URI, so one raw "#" opens a fragment
        // and truncates the JSON. Base64 hides every hash inside the SVG; the
        // one in the name is written %23. Bloom is worn here because its
        // url(#b) reference is the easiest one to leak.
        TokenView memory v = _view(365, 140, 1000, 1000);
        v.marks = MarkRenderer.BLOOM;
        bytes memory uri = bytes(r.tokenURI(v));
        for (uint256 i; i < uri.length; ++i) {
            assertTrue(uri[i] != "#", "a raw hash reached the tokenURI");
        }
    }

    function test_theJsonIsUtf8AndOnlyTheImageIsBase64() public view {
        string memory uri = r.tokenURI(_view(365, 140, 1000, 1000));
        assertTrue(
            vm.contains(uri, "data:application/json;utf-8,{"),
            "the JSON must be served as plain utf-8"
        );
        assertTrue(vm.contains(uri, "data:image/svg+xml;base64,"), "the image must be base64");
    }

    function test_theImageIsDrawnInTheFixedOrder() public view {
        // Ghost, frame, noise, heart. Fixed so each library emits one adjacent
        // pair of paths and the assembler can simply concatenate them.
        //
        // Crown is worn so the frame is gold and the four fills are four
        // distinct strings. On a bare token the frame and the heart share the
        // streak colour, and searching for it would find the frame every time.
        TokenView memory v = _view(200, 45, 1000, 1000);
        v.marks = MarkRenderer.CROWN;
        string memory out = r.svg(v);
        assertLt(_indexOf(out, "#f4eef0"), _indexOf(out, "#b8860b"), "ghost before frame");
        assertLt(_indexOf(out, "#b8860b"), _indexOf(out, "#767676"), "frame before noise");
        assertLt(_indexOf(out, "#767676"), _indexOf(out, "#bd2242"), "noise before heart");
    }

    function test_aRestingTokenNeverPales() public view {
        // A sealed token keeps the colour it stopped at, however long ago that
        // was. A live one with the same clock does not.
        TokenView memory sealed_ = _view(365, 140, 1000, 9999);
        sealed_.resting = true;
        TokenView memory live = _view(365, 140, 1000, 9999);
        TokenView memory fresh = _view(365, 140, 1000, 1000);

        assertEq(r.svg(sealed_), r.svg(fresh), "a sealed token holds its colour");
        assertTrue(
            keccak256(bytes(r.svg(live))) != keccak256(bytes(r.svg(fresh))),
            "a live token that stopped checking in must pale"
        );
    }

    function test_sunsetFreezesTheSameWayRestingDoes() public view {
        TokenView memory sunset = _view(365, 140, 1000, 9999);
        sunset.sunset = true;
        TokenView memory fresh = _view(365, 140, 1000, 1000);
        assertEq(r.svg(sunset), r.svg(fresh), "sunset freezes the image too");
    }

    function test_theRendererIsReachableThroughItsInterface() public view {
        // The token contract holds an address behind IRenderer, so the concrete
        // contract has to satisfy it.
        IRenderer iface = IRenderer(address(r));
        assertGt(bytes(iface.tokenURI(_view(200, 45, 1000, 1000))).length, 0, "no output through the interface");
    }

    function test_theWorstCaseStaysInsideTheHardLimit() public view {
        // Ten rings and every Mark: the largest image a token can reach. The
        // spike's hard limit is 2,000,000 gas and 20,000 bytes.
        // Logged whether or not they pass, so the results table can be filled
        // from a test run rather than from a one-off probe. Run with -vv.
        string[4] memory labels =
            ["day one          ", "whole, one ring  ", "ten years, capped", "cap + all Marks  "];
        TokenView[4] memory vs = [
            _view(1, 1, 1000, 1000),
            _view(365, 140, 1000, 1000),
            _view(365 * 10, 400, 1000, 1000),
            _view(365 * 10, 400, 1000, 1000)
        ];
        vs[3].marks = ALL_MARKS;

        for (uint256 i; i < 4; ++i) {
            uint256 before = gasleft();
            string memory uri = r.tokenURI(vs[i]);
            uint256 used = before - gasleft();
            console.log("%s  %s gas  %s bytes", labels[i], used, bytes(uri).length);
            assertLt(used, 2_000_000, "the worst case overruns the gas limit");
            assertLt(bytes(uri).length, 20_000, "the worst case overruns the byte limit");
        }
    }

    function _indexOf(string memory haystack, string memory needle) internal pure returns (uint256) {
        bytes memory h = bytes(haystack);
        bytes memory n = bytes(needle);
        for (uint256 i; i + n.length <= h.length; ++i) {
            bool hit = true;
            for (uint256 j; j < n.length; ++j) {
                if (h[i + j] != n[j]) { hit = false; break; }
            }
            if (hit) return i;
        }
        revert("not found");
    }
}
