// SPDX-License-Identifier: MIT
// GENERATED by tools/byte-gate-bitmap.mjs -- do not edit by hand.
// Regenerate with: ~/scripts/safe-build.sh node tools/byte-gate-bitmap.mjs
pragma solidity ^0.8.30;

/// @notice The one code bitmap the byte-gate deploy mints with.
/// @dev Token 1 on machinereadableonly.com, 407 bytes, QR version 10.
/// Payload: https://machinereadableonly.com/t/1#
///
/// A token's code encodes its own url, so this cannot be shared with another
/// id and cannot be invented. It comes from the same generator the renderer
/// tests and the live mint use.
library ByteGateBitmap {
    uint256 internal constant BYTES_LEN = 407;

    function code() internal pure returns (bytes memory) {
        return
        hex"fee3b2abe8bf3fc13dbe6a4f86906e8f38e18c5ecbb747ffd7c7ffa5dba7fffbfe7fd2ec13edbf1b3b3107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed07ff71863fffff8ff"
        hex"fff78deffffdbcdbef78ffe7cf396a15df7bfffffffffdff5fffffffdffdfffeffffefbffbfdf7feeefbbbbbfbdbbfedbfd85eb3f7fffffffece7be3effffff3fbfdf1fffce79d9bfe1efbffedf7fb7dbcbffffffffffffedeff"
        hex"ffdbffbffb4ffbfcff9fb9fe971ffffc7b3711d7affffebbfb8a9fc7ffff19cdbc547ffeeffa3337ff1bfedbefb7fae54f7ffffffdfe0046ffffffffff77beffce7dfb9ffbddaffed7ce85fd4afffffdbeeefaed2fffffffbbb3"
        hex"ba9b7fcffddbda3d4277ff7ffffff52bcfff9bdffcd0e203ffffbffab9c5bbeeffbbbb4fe625edbef337dadf20fffffbf958436e4ffffdff73769bc4e7dfa17e1ff10f657ffb7cb203857c3ffeb3fc80662731ff0cc7ff80f8fa"
        hex"9e202af0483f7c5ccef1fbad03fffca3cfbdd58353df349a92e802eedf68b2af05eedbeda7e90bfe8ef72e7c6b9c00";
    }
}
