// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs
pragma solidity ^0.8.30;

/// @notice Every state the Sepolia soak drives a token through, one token each.
/// @dev `gap` is days since the last check-in, rebuilt against the chain's own
/// clock rather than the fixture's. Sunset is not here: it is piece-wide and
/// irreversible, so the soak applies it last and on its own.
library SoakStates {
    struct State {
        uint32 level;
        uint32 streak;
        uint32 gap;
        uint256 marks;
        bool resting;
        string label;
    }

    uint256 internal constant COUNT = 33;

    function all() internal pure returns (State[] memory s) {
        s = new State[](COUNT);
        s[0] = State(365, 0, 0, 0, false, "tier streak 0");
        s[1] = State(365, 0, 30, 0, false, "tier streak 0, 30 days lapsed");
        s[2] = State(365, 3, 0, 0, false, "tier streak 3");
        s[3] = State(365, 3, 30, 0, false, "tier streak 3, 30 days lapsed");
        s[4] = State(365, 7, 0, 0, false, "tier streak 7");
        s[5] = State(365, 7, 30, 0, false, "tier streak 7, 30 days lapsed");
        s[6] = State(365, 30, 0, 0, false, "tier streak 30");
        s[7] = State(365, 30, 30, 0, false, "tier streak 30, 30 days lapsed");
        s[8] = State(365, 100, 0, 0, false, "tier streak 100");
        s[9] = State(365, 100, 30, 0, false, "tier streak 100, 30 days lapsed");
        s[10] = State(1, 400, 0, 0, false, "0 years");
        s[11] = State(365, 400, 0, 0, false, "1 years");
        s[12] = State(730, 400, 0, 0, false, "2 years");
        s[13] = State(1825, 400, 0, 0, false, "5 years");
        s[14] = State(3285, 400, 0, 0, false, "9 years");
        s[15] = State(3650, 400, 0, 0, false, "10 years");
        s[16] = State(4015, 400, 0, 0, false, "11 years");
        s[17] = State(1, 400, 0, 0, false, "fill 1");
        s[18] = State(12, 400, 0, 0, false, "fill 12");
        s[19] = State(200, 400, 0, 0, false, "fill 200");
        s[20] = State(364, 400, 0, 0, false, "fill 364");
        s[21] = State(365, 400, 0, 0, false, "fill 365");
        s[22] = State(365, 400, 0, 0, false, "no marks");
        s[23] = State(365, 400, 0, 1174, false, "all drawing marks");
        s[24] = State(365, 400, 0, 1438, false, "all seven marks");
        s[25] = State(365, 400, 0, 65568, false, "iris squircle");
        s[26] = State(365, 400, 0, 131104, false, "iris leaf");
        s[27] = State(365, 400, 0, 544, false, "tint violet");
        s[28] = State(365, 400, 0, 16777760, false, "tint gold");
        s[29] = State(365, 100, 30, 429496729664, false, "earned iris, lapsed to the start tier");
        s[30] = State(365, 400, 0, 1056, false, "iris on aura, no hush");
        s[31] = State(365, 100, 0, 429513507392, false, "tint on earned iris");
        s[32] = State(365, 400, 8999, 0, true, "resting");
    }
}
