// SPDX-License-Identifier: MIT
// GENERATED by tools/spike-bitmaps.mjs -- do not edit by hand.
// Regenerate with: node tools/spike-bitmaps.mjs example.com
pragma solidity ^0.8.30;

/// @notice The code bitmaps the deploy script mints with, one per token id.
/// @dev Each token's code encodes its own URL, so these cannot be shared
/// between ids. Domain: example.com.
library SpikeBitmaps {
    /// @dev The packed 37x37 grid, 172 bytes, the width HeartMask expects.
    uint256 internal constant BYTES = 172;

    error NoBitmapFor(uint256 id);

    function code(uint256 id) internal pure returns (bytes memory) {
        // day one -- https://example.com/t/1# (mask 7, heart match 64.9%)
        if (id == 1) {
            return hex"fe00810bfc16532d506ebd1a58bb74fffff5dbabfabfaec16ed7ed07faaaaaafe01fe9fe00d33eefebb3eefffff37fff66f70afbdfedf8b7feeeeea0fefdffdf85ffef66e727bfffff6abfeefeef296ffdfff5fbfe66"
                hex"6796e3fedfeb623feefee8d8ffffff86fff66f7362bdfedfd0b3eeeeea5bcfdffdda69bef66f8ac0fffff12f62efecfa0057dfec67fa66642bf04b6df716ba7aed8f95d52ffa2d2e9306943305132d230fe84883cd80";
        }

        // level 200, a part-filled frame -- https://example.com/t/2# (mask 4, heart match 64.5%)
        if (id == 2) {
            return hex"febf916bfc15e45e106ebe43fcbb75fe97f5dba3f33faec14ec1ed07faaaaaafe00fe5fe00ce0efee97feefddfc59ffeff6ef5fbfedfe3dffeefeeb2feffddfc79ffeff6ee07bfedfe4e7feefeef29cffddfe796feff"
                hex"6e20bbfedfeb67beefeeb38cffddfcebffeff6ec89bfedfe664feefeeb7e27fddfe58b9eff6d184afedfef6d28efeefa0077dde443f90ff6ea905badf316bae2fcafa5d0751a9bee98994bcd05be53386fea0b055f80";
        }

        // whole, one year, every Mark but Singularity -- https://example.com/t/3# (mask 1, heart match 64.5%)
        if (id == 3) {
            return hex"fed67643fc15511d906e9ccc5cbb74dc95d5dbaff4ffaec14d91dd07faaaaaafe011dddd00e6ffffff99eeddddd9dfff777616fbdddddb3ffffffff5fefdddddbdfff777603fbdddddc0bffffffb5cefddddfbd2ff77"
                hex"76c373ddddd381bffffff4b8fddddd2deff77762b13ddddde8c3ffffff080fddddf9f4bf7775fa7adddddf8c21fffffd0075ddd447f9d7756ab0515dd518ba3dffffd5d195d887aea153532f055111c08feb911c9880";
        }

        // level 364, the measured worst case -- https://example.com/t/4# (mask 4, heart match 64.5%)
        if (id == 4) {
            return hex"feb791dbfc15e056106ebe53fcbb75ff57f5dba3f03faec14ecded07faaaaaafe00fe1fe00ce0efee979eefddfc59ffeff6ef4fbfedfe3d7feefeeb29effddfc78ffeff6ee17bfedfe4effeefeef2d6ffddfe78bfeff"
                hex"6e2043fedfeb69feefeeb3c2ffddfcebffeff6ec81bfedfe6623eefeeb7e4ffddfe58cbeff6e183afedfeb6cb6efeefa0067ddf443f86ff4ea905f2db716bac8fc0fa5d2ac0b9bee86bd2bcd05f6d3f86feaeba15f80";
        }
        revert NoBitmapFor(id);
    }
}
