// SPDX-License-Identifier: MIT
// GENERATED by tools/spike-bitmaps.mjs -- do not edit by hand.
// Regenerate with: bash tools/spike-bitmaps.sh example.com
pragma solidity ^0.8.30;

/// @notice The code bitmaps the deploy script mints with, one per token id.
/// @dev Each token's code encodes its own URL, so these cannot be shared
/// between ids. Domain: example.com.
library SpikeBitmaps {
    /// @dev The packed 57x57 grid, 407 bytes, the width HeartMask expects.
    uint256 internal constant BYTES = 407;

    error NoBitmapFor(uint256 id);

    function code(uint256 id) internal pure returns (bytes memory) {
        // day one -- https://example.com/t/1# (mask 5, heart match 69.8%)
        if (id == 1) {
            return hex"fe7f926bb8df3fc116bae8ac88906e9d1d71e35bcbb757fff47edfa5dbafffffe6f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebcfbfbf9effffffe7f9bb78beffffebbe9af7efff5c71df04ffefbfffffffffdff3fffffffddfddf3effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fb7bfeeb6fbbfae62e7fffbfddfcc92e7fffffffff7722dfdc7ddf9dfbd68feeb6fb9dbc"
                hex"ecbffffdbffefbee0ffffffbfb727b7e7dc7ddfdfb48c93fff7ffffeb9737fffbfddfd6e4e4dffffbfbb336fadeeffbbbb6bef17eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11aeb6fbbfaa8032d1bbfffabfc80640151beb0c7bfb0187ade0c2b905c377c5eecf11ba3096fe8120ff5d0c265706c9a"
                hex"f2e9f2aedba037bf05c26b879ae9c0fede58a39525f100";
        }

        // level 200, a part-filled frame -- https://example.com/t/2# (mask 5, heart match 70.0%)
        if (id == 2) {
            return hex"fe7f886bb8df3fc1163ae8ac88906e9d1d71a15bcbb757fff44fdfa5dbaffffff6f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebafbfbf9effffffd7f9bb78beffffebbe9af7cfff5c71df04fff7bfffffffffdffbfffffffddfddf3effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fbfbfeeb6fbbfae6dfffffbfddfcc966ffffffffff7726ffdc7ddf9dfbd6afeeb6fb9dbc"
                hex"ecbffffdbffefbee0ffffffbf7727b7efdc7ddfdfb48c93fff7ffffeb97777ffbfddfd6e4c7dffffbfbb336fadeeffbbbb6bee17eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11a6b6fbbfaa803ad7dbfffabfc806465d1beb0c7bfb0583ade0c2b905c377c7cecf11ba3096ff0920ff5d0c265f86c9a"
                hex"f2e8e2aebba037bf05426ba79ae9c0feae58a39525f100";
        }

        // whole, one year, the maximal legal Mark set -- https://example.com/t/3# (mask 6, heart match 70.1%)
        if (id == 3) {
            return hex"fee6a52be8bf3fc13d3eea4f86906e8f38e18e7ecbb747ffd7f6dfa5dba7fffbeff752ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbeda7ff39863ffffff7f9bb78deffffdbfd9ef78ffe7cf39e207df7bfffffffffdffdfffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb4eb3f7ffffffffce7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbcbfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7ffb51d7affffebdf9ca9fc7ffff1bfdbc577ffeeffbba37ff1bfedbefb7fae5fffffffffdfe8046bfffffffff77beffce7dfb9fbbdfbffed7ff85fd"
                hex"4afffffdbffefaed2fffffffffb3b69bffcff9ffba3d42ffff7ffffff52bafff9bdffcd0e61dffffbffab9c7bdeeffbbbb4fe725edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb20204c7bffeb3fc80665b71ff0cc7ff80f8ba9e202af0483f7c6decf1fbad03fffd32dfbdd58353d3f89a"
                hex"92e90aeedb28b2af0566dbeda7e90bfe80f72e7c6b9c00";
        }

        // level 364, the measured worst case -- https://example.com/t/4# (mask 5, heart match 69.9%)
        if (id == 4) {
            return hex"fe7c6e6bb8df3fc116b268ac88906e9d1d71a55bcbb757fff45cdfa5dbaffffff6f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaeb2fbfbf9effffffdff9bb78beffffebbe9af7efff5c71df04fff7bfffffffffdff5fffffffddfddf3effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fafbfeeb6fbbfae62fffffbfddfcc946ffffffffff772affdc7ddf9dfbd49feeb6fb9dbc"
                hex"ecbffffdbffefbee0ffffffbf3727b7ffdc7ddf9fb48c9ffff7ffffeb97b7fffbfddfd6e486fffffbfbb336fadeeffbbbb6bef15eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11aeb6fbbfaa802acabbfffabfc8064ea51beb0c7bfb0583ade0c2b905c377c6fecf11ba3096ff0120ff5d0c265786c9a"
                hex"f2e8eaaedba037bf05c66b879ae9c0fedc58a39525f100";
        }

        // soak state 4 -- https://example.com/t/5# (mask 6, heart match 70.1%)
        if (id == 5) {
            return hex"fee5432be8bf3fc13db66a4f86906e8f38e18a7ecbb747ffd7e5dfa5dba7fffbeff752ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed27ff39863ffffffff9bb78deffffdbfd9ef7affe7cf39e207df7bfffffffffdff3fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb4eb3f7ffffffffce7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbcbfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7ffb51d7affffebdf9ca9fc7ffff1bfdbc577ffeeffbba37fe1bfedbefb7fae50ffffffffdfe8066bfffffffff77b2ffce7dfb9fbbdd8ffed7ff85fd"
                hex"4afffffdbffefaed2ffffffffbb3b69affcff9fbba3d423fff7ffffff527a7ff9bdffcd0e20fffffbffab9c7bdeeffbbbb4fe627edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb2030511bffeb3fc8066d4f1ff0cc7ff80f8ba9e202af0483f7c7eecf1fbad03fffdb2dfbdd5835353f89a"
                hex"92e902eebb28b2af05e2dbcda7e90bfef2f72e7c6b9c00";
        }

        // soak state 5 -- https://example.com/t/6# (mask 5, heart match 70.2%)
        if (id == 6) {
            return hex"fe7f4febb8df3fc116ba68ac88906e9d1d71a15bcbb757fff44ddfa5dbafffffe7f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebafbfbf9efffffffff9bb78beffffebbe9af7dfff5c71df04ffefbfffffffffdffffffffffddfddf5effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fa7bfeeb6fbbfae62e7fffbfddfcc9167fffffffff7726dfdc7ddf9dfbd4afeeb6fb9dbc"
                hex"ecbffffdbffefbee0ffffffbf7727b7e7dc7ddf9fb48c97fff7ffffeb97327ffbfddfd6e484fffffbfbb336cafeeffbbbb6bee95eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11a6b6fbbfaa8032dcdbfffabfc806428d1beb0c7bfb0187ade0c2b905c377c4cecf11ba3096ff0920ff5d0c265306c9a"
                hex"f2e86aaefba037bf054e6b879ae9c0fea058a39525f100";
        }

        // soak state 6 -- https://example.com/t/7# (mask 6, heart match 70.1%)
        if (id == 7) {
            return hex"fee662abe8bf3fc13dbe6a4f86906e8f38e18e7ecbb747ffd7f4dfa5dba7fffbfef752ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbeda7ff39863fffffdff9bb78deffffdbfd9ef79ffe7cf39e207defbfffffffffdff9fffffffdffdffbeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb4eb3f7ffffffffce7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbcbfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7ffb51d7affffebdf9ca9fc7ffff1bfdbc577ffeeffbba37fe9bfedbefb7fae50e7ffffffdfe80363fffffffff77bedfce7dfb9fbbddbffed7ff85fd"
                hex"4afffffdbffefaed2fffffffffb3b69b7fcff9fbba3d42bfff7ffffff52fffff9bdffcd0e22fffffbffab9c4bfeeffbbbb4fe7a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb2028477bffeb3fc80661671ff0cc7ff80b8fa9e202af0483f7c5decf1fbad03fffd32dfbdd583531bf89a"
                hex"92e982ee9b28b2af056adbcda7e90bfe8ef72e7c6b9c00";
        }

        // soak state 7 -- https://example.com/t/8# (mask 5, heart match 70.0%)
        if (id == 8) {
            return hex"fe7aa5ebb8df3fc116ba68ac88906e9d1d71875bcbb757fff45fdfa5dbafffffe6f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb1fbfbf9effffffdff9bb78beffffebbe9af7cfff5c71df04ffefbfffffffffdffdfffffffddfddf5effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fbfbfeeb6fbbfae6afffffbfddfcc91e7fffffffff7726ffdc7ddf9dfbd0bfeeb6fb9dbc"
                hex"ecbffffdbffefbee0ffffffbf3727b7f7dc7ddfffb48c9ffff7ffffeb97b2fffbfddfd6e4a69ffffbfbb336cadeeffbbbb6bef15eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11aeb6fbbfaa803acddbfffabfc8064c651beb0c7bfb0187ade0c2b905c377c7fecf11ba3096ff1920ff5d0c265b0ec9a"
                hex"f2e9faaefba037bf05ca6ba79ae9c0fe8858a39525f100";
        }

        // soak state 8 -- https://example.com/t/9# (mask 5, heart match 70.3%)
        if (id == 9) {
            return hex"fe799e6bb8df3fc1163268ac88906e9d1d71c15bcbb757fff47fdfa5dbafffffe7f7d2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaebffbfbf9effffffcff9bb78beffffebbe9af7dfff5c71df04ffefbfffffffffdffffffffffddfddf3effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb8dbfe7fffffffdc75ff7effffffffbbdf3fffdc71dfd9e9cfbfeebffbbfbbc3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7ffb51f7affffebddddad2c7ffff1bfba4727ffeeffbba37fbfbfeeb6fbbfae65fffffbfddfcc9067fffffffff772effdc7ddf9dfbd0afeeb6fb9dbc"
                hex"ecbffffdbffefbee0ffffffbfb727b7e7dc7ddfffb48c97fff7ffffeb9777fffbfddfd6e4879ffffbfbb336fafeeffbbbb6bef95eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11aeb6fbbfaa802adddbfffabfc80646051beb0c7bfb0187ade0c2b905c377c7eecf11ba3096fe9920ff5d0c26570ec9a"
                hex"f2e86aaebba037bf05c26b879ae9c0fe8458a39525f100";
        }

        // soak state 9 -- https://example.com/t/10# (mask 6, heart match 70.3%)
        if (id == 10) {
            return hex"fee20e2be8bf3fc13d366a4f86906e8f38e1ec7ecbb747ffd7d6ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedd7f339863fffffdfffbb78deffffdbff9ef79ffe7cf39f207defbfffffffffdffdfffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37fe1bfedbefb7fae52e7ffffffdfe8066ffffffffff77b2bfce7dfb9fbbddaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69b7fcff9ffba3d423fff7ffffff523d7ff9bdffcd0e001ffffbffab9c6bdeeffbbbb4fe725edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb2028449bffeb3fc806668f1ff0cc7ff80fcfa9e202af0483f7c4eecf1fbad03fffdb2dfbdd583535b789a"
                hex"92e88aeebb28b2af05a6dbcda7e90bfef0f72e7c6b9c00";
        }

        // soak state 10 -- https://example.com/t/11# (mask 6, heart match 70.0%)
        if (id == 11) {
            return hex"fee606abe8bf3fc13d366a4f86906e8f38e1e87ecbb747ffd7f7ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed27f339863fffffc7ffbb78deffffdbff9ef79ffe7cf39f207dffbfffffffffdff5fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37ff9bfedbefb7fae56f7ffffffdfe80467fffffffff77b6dfce7dfb9fbbddaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69bffcff9ffba3d42ffff7ffffff527a7ff9bdffcd0e435ffffbffab9c6bbeeffbbbb4fe725edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb2030449bffeb3fc80669871ff0cc7ff80b8ba9e202af0483f7c7fecf1fbad03fff432dfbdd583535b789a"
                hex"92e91aee9b28b2af05aadbcda7e90bfefcf72e7c6b9c00";
        }

        // soak state 11 -- https://example.com/t/12# (mask 5, heart match 69.8%)
        if (id == 12) {
            return hex"fe7f6aebb8df3fc1163a68ac88906e9d1d71e15bcbb757fff46dffa5dbafffffe7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb8fb3bf9effffffc7ffbb78beffffebbc9af7efff5c71de04ffefbfffffffffdffdfffffffddfddf5effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff3bdf3fffdc71dfd9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4737ffeeffbba37fbfbfeeb6fbbfae69fffffbfddfcc94ebfffffffff77269fdc7ddf9dfbd6bfeeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbfb727b7f7dc7ddfdfb48c97fff7ffffeb97b3fffbfddfd6e4843ffffbfbb336fadeeffbbbb6bef96eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11aeb6fbbfaa8032de3bfffabfc806445d1beb0c7bfb0187ade0c2b905c377c4fecf11ba3096fe0120ff5d0c265706c9a"
                hex"f2e972aebba037bf05826b879ae9c0fe9c58a39525f100";
        }

        // soak state 12 -- https://example.com/t/13# (mask 6, heart match 70.5%)
        if (id == 13) {
            return hex"fee174abe8bf3fc13db66a4f86906e8f38e18c7ecbb747ffd7d5ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed97f339863fffffefffbb78deffffdbff9ef7bffe7cf39f207dffbfffffffffdff1fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37fe9bfedbefb7fae50efffffffdfe80567fffffffff77b2ffce7dfb9fbbdfbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69bffcff9ffba3d42ffff7ffffff52fc7ff9bdffcd0e407ffffbffab9c4b9eeffbbbb4fe624edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb2020559bffeb3fc80662df1ff0cc7ff80fcba9e202af0483f7c6eecf1fbad03fffc32dfbdd583539bf89a"
                hex"92e89aeebb28b2af05a2dbeda7e90bfeb2f72e7c6b9c00";
        }

        // soak state 13 -- https://example.com/t/14# (mask 6, heart match 70.0%)
        if (id == 14) {
            return hex"fee3822be8bf3fc13dbe6a4f86906e8f38e1ee7ecbb747ffd7c4ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed07f339863fffffe7ffbb78deffffdbff9ef7affe7cf39f207dffbfffffffffdffffffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37fe1bfedbefb7fae5fffffffffdfe8056ffffffffff77b69fce7dfb9fbbdfaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69a7fcff9ffba3d42bfff7ffffff52fa7ff9bdffcd0e401ffffbffab9c4b9eeffbbbb4fe7a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb20205ffbffeb3fc806614f1ff0cc7ff80b8ba9e202af0483f7c5eecf1fbad03fffd32dfbdd5835393789a"
                hex"92e98aeebb28b2af05eadbcda7e90bfedaf72e7c6b9c00";
        }

        // soak state 14 -- https://example.com/t/15# (mask 6, heart match 69.9%)
        if (id == 15) {
            return hex"fee78aabe8bf3fc13dbe6a4f86906e8f38e1ea7ecbb747ffd7e5ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedf7f339863fffffffffbb78deffffdbff9ef7affe7cf39f207defbfffffffffdff7fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37ff9bfedbefb7fae5befffffffdfe80767fffffffff77b2ffce7dfb9fbbdfaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69affcff9ffba3d427fff7ffffff52bd7ff9bdffcd0e035ffffbffab9c4bfeeffbbbb4fe7a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb20385ffbffeb3fc8066e471ff0cc7ff80fcfa9e202af0483f7c6fecf1fbad03fff4b2dfbdd5835393789a"
                hex"92e81aee9b28b2af05e6dbcda7e90bfed6f72e7c6b9c00";
        }

        // soak state 15 -- https://example.com/t/16# (mask 6, heart match 70.0%)
        if (id == 16) {
            return hex"fee4f02be8bf3fc13d3e6a4f86906e8f38e18a7ecbb747ffd7e6ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedb7f339863fffffcfffbb78deffffdbff9ef78ffe7cf39f207dffbfffffffffdffbfffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff3bdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37ff1bfedbefb7fae59e7ffffffdfe8046ffffffffff77b2bfce7dfb9fbbddbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69a7fcff9ffba3d42bfff7ffffff527c7ff9bdffcd0e433ffffbffab9c6bbeeffbbbb4fe6a6edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb20304efbffeb3fc8066a171ff0cc7ff80fcba9e202af0483f7c4fecf1fbad03fff532dfbdd5835353f89a"
                hex"92e80aee9b28b2af05e2dbeda7e90bfe94f72e7c6b9c00";
        }

        // soak state 16 -- https://example.com/t/17# (mask 6, heart match 70.3%)
        if (id == 17) {
            return hex"fee0f8abe8bf3fc13d3e6a4f86906e8f38e18e7ecbb747ffd7c7ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed47f339863fffffd7ffbb78deffffdbff9ef78ffe7cf39f207defbfffffffffdff3fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37fe9bfedbefb7fae5df7ffffffdfe80667fffffffff77b6dfce7dfb9fbbddbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69affcff9ffba3d427fff7ffffff523b7ff9bdffcd0e007ffffbffab9c6bdeeffbbbb4fe6a6edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb20284efbffeb3fc806651f1ff0cc7ff80b8fa9e202af0483f7c7eecf1fbad03fffcb2dfbdd5835353f89a"
                hex"92e99aeebb28b2af05eedbeda7e90bfe98f72e7c6b9c00";
        }

        // soak state 17 -- https://example.com/t/18# (mask 5, heart match 69.9%)
        if (id == 18) {
            return hex"fe78a1ebb8df3fc1163268ac88906e9d1d71c35bcbb757fff44fffa5dbaffffff7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaeb2fb3bf9effffffefffbb78beffffebbc9af7cfff5c71de04fff7bfffffffffdff9fffffffddfddf5effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff7bdf3fffdc71dff9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4737ffeeffbba37fb7bfeeb6fbbfae69e7fffbfddfcc96e7fffffffff772abfdc7ddf9dfbd08feeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbfb727b7efdc7ddfdfb48c9ffff7ffffeb97f47ffbfddfd6e4c47ffffbfbb336da9eeffbbbb6bef17eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11a6b6fbbfaa8022d8bbfffabfc806408d1beb0c7bfb01c3ade0c2b905c377c6decf11ba3096fe8120ff5d0c26570ec9a"
                hex"f2e972aefba037bf05426ba79ae9c0fede58a39525f100";
        }

        // soak state 18 -- https://example.com/t/19# (mask 6, heart match 70.1%)
        if (id == 19) {
            return hex"fee6bfabe8bf3fc13dbe6a4f86906e8f38e1ae7ecbb747ffd7f7ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed37f339863fffffc7ffbb78deffffdbff9ef79ffe7cf39f207de7bfffffffffdff5fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbfbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37fe1bfedbefb7fae50f7ffffffdfe8076bfffffffff77bedfce7dfb9fbbd98ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69a7fcff9ffba3d427fff7ffffff52bbfff9bdffcd0e003ffffbffab9c6bdeeffbbbb4fe6a5edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb2030531bffeb3fc806660f1ff0cc7ff80f8fa9e202af0483f7c4cecf1fbad03fff432dfbdd583539b789a"
                hex"92e89aeefb28b2af0562dbcda7e90bfef0f72e7c6b9c00";
        }

        // soak state 19 -- https://example.com/t/20# (mask 6, heart match 70.4%)
        if (id == 20) {
            return hex"fee2142be8bf3fc13db66a4f86906e8f38e1ae7ecbb747ffd7e7ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedb7f339863fffffefffbb78deffffdbff9ef7bffe7cf39f207df7bfffffffffdff5fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37fe9bfedbefb7fae5dffffffffdfe802e7fffffffff77b69fce7dfb9fbbdd8ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69bffcff9ffba3d423fff7ffffff527dfff9bdffcd0e231ffffbffab9c6bdeeffbbbb4fe625edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb202042fbffeb3fc80660c71ff0cc7ff80bcba9e202af0483f7c6cecf1fbad03ffe532dfbdd58353d3789a"
                hex"92e99aeedb28b2af0526dbeda7e90bfe80f72e7c6b9c00";
        }

        // soak state 20 -- https://example.com/t/21# (mask 6, heart match 70.5%)
        if (id == 21) {
            return hex"fee61cabe8bf3fc13db66a4f86906e8f38e1aa7ecbb747ffd7c6ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed47f339863ffffff7ffbb78deffffdbff9ef7bffe7cf39f207de7bfffffffffdffdfffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37ff1bfedbefb7fae59efffffffdfe800effffffffff77b2ffce7dfb9fbbdd8ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69b7fcff9ffba3d42ffff7ffffff523afff9bdffcd0e605ffffbffab9c6bbeeffbbbb4fe625edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb203842fbffeb3fc8066fcf1ff0cc7ff80f8fa9e202af0483f7c5decf1fbad03ffecb2dfbdd58353d3789a"
                hex"92e80aeefb28b2af052adbeda7e90bfe8cf72e7c6b9c00";
        }

        // soak state 21 -- https://example.com/t/22# (mask 6, heart match 70.1%)
        if (id == 22) {
            return hex"fee5662be8bf3fc13d366a4f86906e8f38e1ca7ecbb747ffd7c5ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed07f339863fffffc7ffbb78deffffdbff9ef79ffe7cf39f207df7bfffffffffdff1fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff3bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37ff9bfedbefb7fae5be7ffffffdfe803e7fffffffff77b2bfce7dfb9fbbdf9ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69bffcff9ffba3d423fff7ffffff52fbfff9bdffcd0e203ffffbffab9c4bfeeffbbbb4fe724edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb203053fbffeb3fc8066b9f1ff0cc7ff80f8ba9e202af0483f7c7decf1fbad03ffed32dfbdd5835313f89a"
                hex"92e81aeefb28b2af052edbcda7e90bfecef72e7c6b9c00";
        }

        // soak state 22 -- https://example.com/t/23# (mask 6, heart match 70.2%)
        if (id == 23) {
            return hex"fee16eabe8bf3fc13d366a4f86906e8f38e1ce7ecbb747ffd7e4ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedf7f339863fffffdfffbb78deffffdbff9ef79ffe7cf39f207de7bfffffffffdff9fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37fe1bfedbefb7fae5ff7ffffffdfe801effffffffff77b6dfce7dfb9fbbdf9ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69b7fcff9ffba3d42ffff7ffffff52bcfff9bdffcd0e637ffffbffab9c4b9eeffbbbb4fe724edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb202853fbffeb3fc80664971ff0cc7ff80bcfa9e202af0483f7c4cecf1fbad03ffe4b2dfbdd5835313f89a"
                hex"92e98aeedb28b2af0522dbcda7e90bfec2f72e7c6b9c00";
        }

        // soak state 23 -- https://example.com/t/24# (mask 6, heart match 69.8%)
        if (id == 24) {
            return hex"fee3982be8bf3fc13d3e6a4f86906e8f38e1ac7ecbb747ffd7f5ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed67f339863fffffd7ffbb78deffffdbff9ef78ffe7cf39f207de7bfffffffffdff7fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37fe9bfedbefb7fae50e7ffffffdfe801e7fffffffff77b2bfce7dfb9fbbdf8ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69affcff9ffba3d42bfff7ffffff52bafff9bdffcd0e631ffffbffab9c4b9eeffbbbb4fe6a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb2028599bffeb3fc80667071ff0cc7ff80f8fa9e202af0483f7c7cecf1fbad03ffe5b2dfbdd583531b789a"
                hex"92e89aeedb28b2af056adbeda7e90bfeaaf72e7c6b9c00";
        }

        // soak state 24 -- https://example.com/t/25# (mask 6, heart match 70.0%)
        if (id == 25) {
            return hex"fee790abe8bf3fc13d3e6a4f86906e8f38e1a87ecbb747ffd7d4ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed97f339863fffffcfffbb78deffffdbff9ef78ffe7cf39f207df7bfffffffffdffffffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37ff1bfedbefb7fae54f7ffffffdfe803effffffffff77b6dfce7dfb9fbbdf8ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69a7fcff9ffba3d427fff7ffffff52fdfff9bdffcd0e205ffffbffab9c4bfeeffbbbb4fe6a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb2030599bffeb3fc806680f1ff0cc7ff80bcba9e202af0483f7c4decf1fbad03ffec32dfbdd583531b789a"
                hex"92e90aeefb28b2af0566dbeda7e90bfea6f72e7c6b9c00";
        }

        // soak state 25 -- https://example.com/t/26# (mask 6, heart match 70.1%)
        if (id == 26) {
            return hex"fee4ea2be8bf3fc13dbe6a4f86906e8f38e1c87ecbb747ffd7d7ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedd7f339863fffffffffbb78deffffdbff9ef7affe7cf39f207de7bfffffffffdff3fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff3bdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37ff9bfedbefb7fae56ffffffffdfe800e7fffffffff77b69fce7dfb9fbbdd9ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69affcff9ffba3d42bfff7ffffff523cfff9bdffcd0e603ffffbffab9c6bbeeffbbbb4fe7a6edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb2038489bffeb3fc8066c5f1ff0cc7ff80bcfa9e202af0483f7c6decf1fbad03ffedb2dfbdd58353dbf89a"
                hex"92e91aeefb28b2af0562dbcda7e90bfee4f72e7c6b9c00";
        }

        // soak state 26 -- https://example.com/t/27# (mask 5, heart match 70.1%)
        if (id == 27) {
            return hex"fe7af46bb8df3fc1163268ac88906e9d1d71a55bcbb757fff46fffa5dbafffffe6efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaebcfb3bf9effffffd7ffbb78beffffebbc9af7ffff5c71de04fff7bfffffffffdffffffffffddfddf1effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffffbbdf3fffdc71df99e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4737ffeeffbba37fafbfeeb6fbbfae6feffffbfddfcc916bfffffffff7722ffdc7ddf9dfbd49feeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbf7727b7e7dc7ddfdfb48c93fff7ffffeb97737ffbfddfd6e4a47ffffbfbb336dafeeffbbbb6bee14eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11a6b6fbbfaa802ac33bfffabfc8064add1beb0c7bfb0583ade0c2b905c377c4cecf11ba3096ff1920ff5d0c265306c9a"
                hex"f2e8f2aefba037bf05426ba79ae9c0feca58a39525f100";
        }

        // soak state 27 -- https://example.com/t/28# (mask 6, heart match 70.0%)
        if (id == 28) {
            return hex"fee2ad2be8bf3fc13d3e6a4f86906e8f38e1e87ecbb747ffd7e7ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbeda7f339863fffffefffbb78deffffdbff9ef7bffe7cf39f207defbfffffffffdff5fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbfbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37ff1bfedbefb7fae5bffffffffdfe801ebfffffffff77be9fce7dfb9fbbd9affed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff7b3b69a7fcff9ffba3d42bfff7ffffff52bc7ff9bdffcd0e607ffffbffab9c6bbeeffbbbb4fe7a5edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb2020557bffeb3fc8066f4f1ff0cc7ff80fcfa9e202af0483f7c5fecf1fbad03ffe532dfbdd5835313789a"
                hex"92e81aeebb28b2af05eedbeda7e90bfe8cf72e7c6b9c00";
        }

        // soak state 28 -- https://example.com/t/29# (mask 5, heart match 70.2%)
        if (id == 29) {
            return hex"fe7cb36bb8df3fc116b268ac88906e9d1d71855bcbb757fff45fffa5dbaffffff7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaebbfb3bf9effffffc7ffbb78beffffebbc9af7efff5c71de04ffffbfffffffffdff9fffffffddfddf1effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7efffffffffbdf3fffdc71dff9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4727ffeeffbba37fa7bfeeb6fbbfae62effffbfddfcc9067fffffffff772affdc7ddf9dfbd0afeeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbf7727b7efdc7ddfdfb48c93fff7ffffeb97f3fffbfddfd6e4a43ffffbfbb336dafeeffbbbb6bee17eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11a6b6fbbfaa8032dedbfffabfc80649cd1beb0c7bfb0183ade0c2b905c377c7eecf11ba3096ff9120ff5d0c265f8ec9a"
                hex"f2e9f2aebba037bf05ce6b879ae9c0fea258a39525f100";
        }

        // soak state 29 -- https://example.com/t/30# (mask 6, heart match 70.3%)
        if (id == 30) {
            return hex"fee12fabe8bf3fc13d3e6a4f86906e8f38e1e87ecbb747ffd7c7ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed57f339863fffffffffbb78deffffdbff9ef7affe7cf39f207df7bfffffffffdff7fffffffdffdfffeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37fe9bfedbefb7fae52ffffffffdfe80367fffffffff77be9fce7dfb9fbbdd9ffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69affcff9ffba3d42bfff7ffffff52b8fff9bdffcd0e021ffffbffab9c5bfeeffbbbb4fe6a5edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb203052fbffeb3fc8066aa71ff0cc7ff80bcba9e202af0483f7c6decf1fbad03fffd32dfbdd5835313789a"
                hex"92e80aee9b28b2af052edbcda7e90bfe8cf72e7c6b9c00";
        }

        // soak state 30 -- https://example.com/t/31# (mask 6, heart match 70.4%)
        if (id == 31) {
            return hex"fee5272be8bf3fc13d3e6a4f86906e8f38e1ec7ecbb747ffd7e6ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbeda7f339863fffffe7ffbb78deffffdbff9ef7affe7cf39f207de7bfffffffffdffffffffffdffdffbeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37ff1bfedbefb7fae56efffffffdfe8016ffffffffff77baffce7dfb9fbbdd9ffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69a7fcff9ffba3d427fff7ffffff52fffff9bdffcd0e415ffffbffab9c5b9eeffbbbb4fe6a5edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb202852fbffeb3fc80665af1ff0cc7ff80f8fa9e202af0483f7c5cecf1fbad03fff4b2dfbdd5835313789a"
                hex"92e99aeebb28b2af0522dbcda7e90bfe80f72e7c6b9c00";
        }

        // soak state 31 -- https://example.com/t/32# (mask 6, heart match 70.3%)
        if (id == 32) {
            return hex"fee65dabe8bf3fc13dbe6a4f86906e8f38e18c7ecbb747ffd7e5ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbede7f339863fffffd7ffbb78deffffdbff9ef78ffe7cf39f207df7bfffffffffdff3fffffffdffdffbeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff3bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37ff9bfedbefb7fae54e7ffffffdfe80267fffffffff77babfce7dfb9fbbdf8ffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69affcff9ffba3d42bfff7ffffff523efff9bdffcd0e013ffffbffab9c7bdeeffbbbb4fe7a4edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb202043fbffeb3fc80661ff1ff0cc7ff80f8ba9e202af0483f7c7cecf1fbad03fff532dfbdd58353d3f89a"
                hex"92e98aeebb28b2af0526dbeda7e90bfec2f72e7c6b9c00";
        }

        // soak state 32 -- https://example.com/t/33# (mask 6, heart match 70.3%)
        if (id == 33) {
            return hex"fee2552be8bf3fc13dbe6a4f86906e8f38e1887ecbb747ffd7c4ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed17f339863fffffcfffbb78deffffdbff9ef78ffe7cf39f207de7bfffffffffdffbfffffffdffdfffeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37fe1bfedbefb7fae50f7ffffffdfe8006ffffffffff77bedfce7dfb9fbbdf8ffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69a7fcff9ffba3d427fff7ffffff5279fff9bdffcd0e427ffffbffab9c7bbeeffbbbb4fe7a4edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb203843fbffeb3fc8066ef71ff0cc7ff80bcfa9e202af0483f7c4decf1fbad03fffcb2dfbdd58353d3f89a"
                hex"92e81aee9b28b2af052adbeda7e90bfecef72e7c6b9c00";
        }

        // soak state 33 -- https://example.com/t/34# (mask 5, heart match 70.1%)
        if (id == 34) {
            return hex"fe7ab56bb8df3fc1163a68ac88906e9d1d71835bcbb757fff44cffa5dbafffffe6efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb6fb3bf9efffffff7ffbb78beffffebbc9af7cfff5c71de04ffe7bfffffffffdff1fffffffddfddf7effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff7bdf3fffdc71df99e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4707ffeeffbba37fa7bfeeb6fbbfae62e7fffbfddfcc93e3fffffffff772abfdc7ddf9dfbd69feeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbff727b7ffdc7ddfdfb48c97fff7ffffeb97777ffbfddfd6e4c51ffffbfbb336ca9eeffbbbb6bef95eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11aeb6fbbfaa8032c23bfffabfc80644ed1beb0c7bfb0587ade0c2b905c377c6decf11ba3096fe8120ff5d0c26530ec9a"
                hex"f2e972aebba037bf054e6ba79ae9c0fe8458a39525f100";
        }

        // soak state 34 -- https://example.com/t/35# (mask 6, heart match 70.3%)
        if (id == 35) {
            return hex"fee4ab2be8bf3fc13db66a4f86906e8f38e1ee7ecbb747ffd7f4ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed77f339863fffffdfffbb78deffffdbff9ef79ffe7cf39f207df7bfffffffffdffdfffffffdffdffbeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37ff1bfedbefb7fae5bf7ffffffdfe8026ffffffffff77bedfce7dfb9fbbdf9ffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69b7fcff9ffba3d42ffff7ffffff5238fff9bdffcd0e015ffffbffab9c7bdeeffbbbb4fe627edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb2020499bffeb3fc806626f1ff0cc7ff80bcba9e202af0483f7c4cecf1fbad03fff432dfbdd58353db789a"
                hex"92e89aeebb28b2af056edbcda7e90bfeaaf72e7c6b9c00";
        }

        // soak state 35 -- https://example.com/t/36# (mask 5, heart match 70.0%)
        if (id == 36) {
            return hex"fe7dc76bb8df3fc116ba68ac88906e9d1d71e75bcbb757fff46effa5dbaffffff7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebdfb3bf9effffffdfffbb78beffffebbc9af7efff5c71de04ffe7bfffffffffdff5fffffffddfddf3effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff3bdf3fffdc71df99e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4727ffeeffbba37fb7bfeeb6fbbfae64fffffbfddfcc92e3fffffffff772e9fdc7ddf9dfbd48feeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbff727b7ffdc7ddfdfb48c97fff7ffffeb97f17ffbfddfd6e4c63ffffbfbb336eabeeffbbbb6bee94eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11aeb6fbbfaa8022d33bfffabfc8064fb51beb0c7bfb01c7ade0c2b905c377c7cecf11ba3096fe0120ff5d0c265f06c9a"
                hex"f2e8f2ae9ba037bf05466b879ae9c0feca58a39525f100";
        }

        // soak state 36 -- https://example.com/t/37# (mask 6, heart match 70.1%)
        if (id == 37) {
            return hex"fee3d92be8bf3fc13d366a4f86906e8f38e18a7ecbb747ffd7d6ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbedc7f339863ffffff7ffbb78deffffdbff9ef7bffe7cf39f207df7bfffffffffdff9fffffffdffdfffeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37fe1bfedbefb7fae5defffffffdfe8036ffffffffff77baffce7dfb9fbbdd8ffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69b7fcff9ffba3d42ffff7ffffff52befff9bdffcd0e027ffffbffab9c5bfeeffbbbb4fe726edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb2030589bffeb3fc80669371ff0cc7ff80f8ba9e202af0483f7c5decf1fbad03fffc32dfbdd583531bf89a"
                hex"92e91aee9b28b2af0566dbeda7e90bfee4f72e7c6b9c00";
        }

        // soak state 37 -- https://example.com/t/38# (mask 6, heart match 70.6%)
        if (id == 38) {
            return hex"fee196abe8bf3fc13db66a4f86906e8f38e1ae7ecbb747ffd7c7ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed47f339863fffffffffbb78deffffdbff9ef7affe7cf39f207defbfffffffffdff7fffffffdffdffbeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbfbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37ff1bfedbefb7fae54ffffffffdfe8006bfffffffff77b69fce7dfb9fbbd9bffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69b7fcff9ffba3d423fff7ffffff52797ff9bdffcd0e417ffffbffab9c5b9eeffbbbb4fe725edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb2030457bffeb3fc806652f1ff0cc7ff80fcfa9e202af0483f7c5eecf1fbad03fffd32dfbdd58353d3789a"
                hex"92e98aeefb28b2af05e6dbcda7e90bfe80f72e7c6b9c00";
        }

        // soak state 38 -- https://example.com/t/39# (mask 6, heart match 70.5%)
        if (id == 39) {
            return hex"fee59e2be8bf3fc13db66a4f86906e8f38e1aa7ecbb747ffd7e6ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbedb7f339863fffffe7ffbb78deffffdbff9ef7affe7cf39f207dffbfffffffffdffffffffffdffdfffeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbfbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37fe9bfedbefb7fae50efffffffdfe80263fffffffff77b2ffce7dfb9fbbd9bffed7ffa5fd"
                hex"4afffffdbffefaed2fffffffffb3b69bffcff9ffba3d42ffff7ffffff523e7ff9bdffcd0e023ffffbffab9c5bfeeffbbbb4fe725edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb2028457bffeb3fc8066a271ff0cc7ff80b8ba9e202af0483f7c6fecf1fbad03fff4b2dfbdd58353d3789a"
                hex"92e81aeedb28b2af05eadbcda7e90bfe8cf72e7c6b9c00";
        }

        // soak state 39 -- https://example.com/t/40# (mask 6, heart match 69.8%)
        if (id == 40) {
            return hex"fee1f22be8bf3fc13d3eea4f86906e8f38e1aa7ecbb747ffd7f4ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed37f339863fffffe7ffbb78deffffdbff9ef79ffe7cf39f207df7bfffffffffdffbfffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37ff9bfedbefb7fae52ffffffffdfe800e7fffffffff77ba9fce7dfb9fbbdfbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69affcff9fbba3d42ffff7ffffff52bd7ff9bdffcd0e623ffffbffab9c6bdeeffbbbb4fe727edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10f6d7ffb7cb20305f9bffeb3fc806683f1ff0cc7ff80bcba9e202af0483f7c7fecf1fbad03ffe5b2dfbdd5835353789a"
                hex"92e992eebb28b2af05a2dbcda7e90bfef2f72e7c6b9c00";
        }

        // soak state 40 -- https://example.com/t/41# (mask 6, heart match 69.9%)
        if (id == 41) {
            return hex"fee5faabe8bf3fc13d3eea4f86906e8f38e1ae7ecbb747ffd7d5ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbedc7f339863fffffffffbb78deffffdbff9ef79ffe7cf39f207de7bfffffffffdff3fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc557ffeeffbba37fe1bfedbefb7fae56efffffffdfe802effffffffff77beffce7dfb9fbbdfbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69a7fcff9fbba3d423fff7ffffff52fa7ff9bdffcd0e217ffffbffab9c6bbeeffbbbb4fe727edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb20285f9bffeb3fc80667371ff0cc7ff80f8fa9e202af0483f7c4eecf1fbad03ffec32dfbdd5835353789a"
                hex"92e802ee9b28b2af05aedbcda7e90bfefef72e7c6b9c00";
        }

        // soak state 41 -- https://example.com/t/42# (mask 5, heart match 69.9%)
        if (id == 42) {
            return hex"fe7c96ebb8df3fc11632e8ac88906e9d1d71a75bcbb757fff44fffa5dbaffffff7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb6fb3bf9effffffffffbb78beffffebbc9af7efff5c71de04fff7bfffffffffdffbfffffffddfddf5effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff3bdf3fffdc71dfd9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4737ffeeffbba37fa7bfeeb6fbbfae69e7fffbfddfcc9263fffffffff772ebfdc7ddf9dfbd4afeeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbf3727b7efdc7ddf9fb48c9bfff7ffffeb9733fffbfddfd6e4e61ffffbfbb336fadeeffbbbb6bef94eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf8590bf11aeb6fbbfaa802ac53bfffabfc8064aed1beb0c7bfb0583ade0c2b905c377c7eecf11ba3096ff8120ff5d0c265786c9a"
                hex"f2e86aaebba037bf05866b879ae9c0fe9e58a39525f100";
        }

        // soak state 42 -- https://example.com/t/43# (mask 6, heart match 70.1%)
        if (id == 43) {
            return hex"fee288abe8bf3fc13dbeea4f86906e8f38e1ca7ecbb747ffd7f7ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed77f339863fffffd7ffbb78deffffdbff9ef7bffe7cf39f207de7bfffffffffdff7fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37ff1bfedbefb7fae50f7ffffffdfe803effffffffff77badfce7dfb9fbbddaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69a7fcff9fbba3d423fff7ffffff527c7ff9bdffcd0e225ffffbffab9c4b9eeffbbbb4fe626edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb17c1ff10fed7ffb7cb20384e9bffeb3fc8066c6f1ff0cc7ff80bcfa9e202af0483f7c5fecf1fbad03ffe432dfbdd5835393f89a"
                hex"92e982eebb28b2af05a6dbeda7e90bfeb0f72e7c6b9c00";
        }

        // soak state 43 -- https://example.com/t/44# (mask 5, heart match 69.9%)
        if (id == 44) {
            return hex"fe7a68ebb8df3fc1163ae8ac88906e9d1d71c15bcbb757fff47fffa5dbafffffe7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaeb0fb3bf9effffffefffbb78beffffebbc9af7ffff5c71de04ffe7bfffffffffdffdfffffffddfddf1effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff7bdf3fffdc71df99e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4707ffeeffbba37fb7bfeeb6fbbfae62e7fffbfddfcc9063fffffffff772ebfdc7ddf9dfbd4bfeeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbf3727b7ffdc7ddf9fb48c93fff7ffffeb9772fffbfddfd6e4a53ffffbfbb336fabeeffbbbb6bee17eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11a6b6fbbfaa8032cf5bfffabfc80646751beb0c7bfb0587ade0c2b905c377c7fecf11ba3096ff0920ff5d0c26570ec9a"
                hex"f2e8eaae9ba037bf05c26ba79ae9c0fefa58a39525f100";
        }

        // soak state 44 -- https://example.com/t/45# (mask 6, heart match 70.1%)
        if (id == 45) {
            return hex"fee476abe8bf3fc13db6ea4f86906e8f38e1ac7ecbb747ffd7c7ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed17f339863fffffc7ffbb78deffffdbff9ef7affe7cf39f207df7bfffffffffdff1fffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37fe1bfedbefb7fae5bf7ffffffdfe801effffffffff77badfce7dfb9fbbddbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69b7fcff9fbba3d42bfff7ffffff523d7ff9bdffcd0e617ffffbffab9c4bfeeffbbbb4fe7a5edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb202044fbffeb3fc80660f71ff0cc7ff80bcba9e202af0483f7c5eecf1fbad03ffecb2dfbdd583539b789a"
                hex"92e902ee9b28b2af05e2dbcda7e90bfed4f72e7c6b9c00";
        }

        // soak state 45 -- https://example.com/t/46# (mask 6, heart match 69.9%)
        if (id == 46) {
            return hex"fee70c2be8bf3fc13d36ea4f86906e8f38e1cc7ecbb747ffd7c4ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbed57f339863ffffff7ffbb78deffffdbff9ef78ffe7cf39f207de7bfffffffffdffdfffffffdffdffdeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff3bdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37fe9bfedbefb7fae59ffffffffdfe802e7fffffffff77ba9fce7dfb9fbbdfaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69bffcff9fbba3d427fff7ffffff52fc7ff9bdffcd0e211ffffbffab9c6bbeeffbbbb4fe6a4edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10fed7ffb7cb202855fbffeb3fc80664a71ff0cc7ff80bcfa9e202af0483f7c7eecf1fbad03ffed32dfbdd583535bf89a"
                hex"92e912ee9b28b2af05e6dbeda7e90bfe96f72e7c6b9c00";
        }

        // soak state 46 -- https://example.com/t/47# (mask 6, heart match 69.9%)
        if (id == 47) {
            return hex"fee304abe8bf3fc13d36ea4f86906e8f38e1c87ecbb747ffd7e5ffa5dba7fffbfeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbeda7f339863fffffefffbb78deffffdbff9ef78ffe7cf39f207df7bfffffffffdff5fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffffbbdf1fffce79fb9be1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37ff1bfedbefb7fae5defffffffdfe800effffffffff77beffce7dfb9fbbdfaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69b7fcff9fbba3d42bfff7ffffff52bb7ff9bdffcd0e625ffffbffab9c6bdeeffbbbb4fe6a4edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb203055fbffeb3fc8066baf1ff0cc7ff80f8ba9e202af0483f7c4fecf1fbad03ffe4b2dfbdd583535bf89a"
                hex"92e882eebb28b2af05eadbeda7e90bfe9af72e7c6b9c00";
        }

        // soak state 47 -- https://example.com/t/48# (mask 5, heart match 70.0%)
        if (id == 48) {
            return hex"fe7b5debb8df3fc1163ae8ac88906e9d1d71855bcbb757fff46dffa5dbafffffe7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c61df9df8afbfaebcfb3bf9effffffd7ffbb78beffffebbc9af7cfff5c71de04ffefbfffffffffdffffffffffddfddf5effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7effffffff7bdf3fffdc71dff9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4737ffeeffbba37fafbfeeb6fbbfae69fffffbfddfcc906ffffffffff77229fdc7ddf9dfbd29feeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbf3727b7f7dc7ddf9fb48c93fff7ffffeb97747ffbfddfd6e4a65ffffbfbb336da9eeffbbbb6bef15eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11a6b6fbbfaa803ac3bbfffabfc8064e3d1beb0c7bfb05c7ade0c2b905c377c5cecf11ba3096ff0120ff5d0c26578ec9a"
                hex"f2e86aaefba037bf05466ba79ae9c0fedc58a39525f100";
        }

        // soak state 48 -- https://example.com/t/49# (mask 6, heart match 70.3%)
        if (id == 49) {
            return hex"fee543abe8bf3fc13db6ea4f86906e8f38e1e87ecbb747ffd7d5ffa5dba7fffbefef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbedd7f339863fffffffffbb78deffffdbff9ef79ffe7cf39f207dffbfffffffffdff3fffffffdffdff9effffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3efffffffffbdf1fffce79fbfbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc577ffeeffbba37ff9bfedbefb7fae50efffffffdfe801e3fffffffff77b6ffce7dfb9fbbdb9ffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffff3b3b69bffcff9fbba3d42bfff7ffffff523bfff9bdffcd0e621ffffbffab9c6bdeeffbbbb4fe6a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb2028481bffeb3fc80668bf1ff0cc7ff80b8ba9e202af0483f7c7decf1fbad03ffec32dfbdd5835393789a"
                hex"92e982eefb28b2af0566dbcda7e90bfef2f72e7c6b9c00";
        }

        // soak state 49 -- https://example.com/t/50# (mask 6, heart match 70.0%)
        if (id == 50) {
            return hex"fee2c9abe8bf3fc13db6ea4f86906e8f38e1ec7ecbb747ffd7d4ffa5dba7fffbffef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce79fb9ff9f7bfbedd7f339863ffffff7ffbb78deffffdbff9ef78ffe7cf39f207df7bfffffffffdff9fffffffdffdfffeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff7bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc547ffeeffbba37ff9bfedbefb7fae5dffffffffdfe80167fffffffff77b29fce7dfb9fbbdfaffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69bffcff9fbba3d427fff7ffffff52787ff9bdffcd0e433ffffbffab9c5bfeeffbbbb4fe7a7edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb20204f9bffeb3fc806625f1ff0cc7ff80bcba9e202af0483f7c7eecf1fbad03fffdb2dfbdd5835393789a"
                hex"92e802eefb28b2af05aadbeda7e90bfefef72e7c6b9c00";
        }

        // soak state 50 -- https://example.com/t/51# (mask 5, heart match 70.2%)
        if (id == 51) {
            return hex"fe7cd7ebb8df3fc1163ae8ac88906e9d1d71815bcbb757fff46cffa5dbaffffff7efd2ec13ebaf1bf3f107faaaaaaaaaaafe00faebc7bbfb00c77fffffddfd8c5efffffffffffcafff5c71df9df8afbfaebcfb3bf9effffffdfffbb78beffffebbc9af7dfff5c71de04ffe7bfffffffffdff5fffffffddfddf3effffebbfbbfb"
                hex"fffeeefbbbbbfbffbfaebffb9dbfe7fffffffdd75ff7efffffffffbdf3fffdc71dfd9e9cfbfeebffbbfbbe3fffffffffffff7effffebbfbbfb5fffdc6fdf9dfecf1ffffc7fbb51f7affffebdfddad2c7ffff1beba4707ffeeffbba37fafbfeeb6fbbfae64effffbfddfcc90ebfffffffff7726ffdc7ddf9dfbd6afeeb6fbbdbc"
                hex"ecbffffdbffefbee0ffffffbfb727b7f7dc7ddf9fb48c9ffff7ffffeb9737fffbfddfd6e4877ffffbfbb336eabeeffbbbb6bee15eeb6fbbef6efa6fffbfddb4cd34b6ffffffd73f69e01c7ddf0590bf11a6b6fbbfaa8032c43bfffabfc80644dd1beb0c7bfb0587ade0c2b905c377c5fecf11ba3096fe1920ff5d0c26578ec9a"
                hex"f2e9eaaefba037bf058a6b879ae9c0fed058a39525f100";
        }

        // soak state 51 -- https://example.com/t/52# (mask 6, heart match 69.8%)
        if (id == 52) {
            return hex"fee5bbabe8bf3fc13d36ea4f86906e8f38e1887ecbb747ffd7f6ffa5dba7fffbeeef52ec13edbf1b77f107faaaaaaaaaaafe01fedbc7b7fb00da7ffffffdffa0cefffffffffffcefffce69fb9ff9f7bfbed67f339863fffffdfffbb78deffffdbff9ef7affe7cf39f207df7bfffffffffdffdfffffffdffdffbeffffefbffbfd"
                hex"fffeeefbbbbbfbdfbfedbffb5eb3f7ffffffffde7be3effffffff3bdf1fffce79fbdbe1efbffedf7fb7dbebfffffffffffff5effffdbffbffb4ffffcff9fb9fe971ffffc7fbb51d7affffebdd9ca9fc7ffff1bedbc567ffeeffbba37fe9bfedbefb7fae5be7ffffffdfe80067fffffffff77b6bfce7dfb9fbbddbffed7ffa5fd"
                hex"4afffffdbffefaed2ffffffffbb3b69bffcff9fbba3d427fff7ffffff52fe7ff9bdffcd0e401ffffbffab9c7bdeeffbbbb4fe6a6edbefb7fdadf20ffffffdb78436e4ffffffd73769bc4e7dfb97c1ff10f6d7ffb7cb20305e9bffeb3fc80669071ff0cc7ff80f8ba9e202af0483f7c6fecf1fbad03fff5b2dfbdd5835353f89a"
                hex"92e982eedb28b2af05a2dbcda7e90bfeb0f72e7c6b9c00";
        }
        revert NoBitmapFor(id);
    }
}
