// Regenerate src/clock/abi.mjs from the compiled contract artifact.
//
//   cd warden && node tools/gen-abi.mjs
//
// Reads the Foundry build output rather than shelling out to `forge inspect`,
// so it needs no PATH setup and cannot disagree with the bytecode that was
// actually built. Run it after any change to MachineReadableOnly.sol -- an ABI
// that has drifted from the contract encodes calls the chain will reject, and
// the failure looks like a chain problem rather than a stale file.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const ARTIFACT = fileURLToPath(
  new URL("../../contracts/out/MachineReadableOnly.sol/MachineReadableOnly.json", import.meta.url)
);
const OUT = fileURLToPath(new URL("../src/clock/abi.mjs", import.meta.url));

const artifact = JSON.parse(readFileSync(ARTIFACT, "utf8"));
const abi = artifact.abi;
if (!Array.isArray(abi) || abi.length === 0) {
  throw new Error(`no abi in ${ARTIFACT} -- run \`forge build\` in contracts/ first`);
}

// The functions the Clock actually sends, checked here so a renamed or
// re-signatured contract function fails LOUDLY at generation time rather than
// as a confusing revert at 00:05 UTC.
const REQUIRED_FUNCTIONS = ["mint", "batchCheckIn", "applyMark", "seed"];
const REQUIRED_EVENTS = ["Minted", "BatchCheckedIn", "MarkApplied", "Rebound", "Transfer", "Rested"];

for (const name of REQUIRED_FUNCTIONS) {
  if (!abi.some((e) => e.type === "function" && e.name === name)) {
    throw new Error(`the contract has no function ${name}(): the Clock cannot be generated against it`);
  }
}
for (const name of REQUIRED_EVENTS) {
  if (!abi.some((e) => e.type === "event" && e.name === name)) {
    throw new Error(`the contract has no event ${name}: reconcile depends on it`);
  }
}

const header = `// GENERATED by tools/gen-abi.mjs -- do not edit by hand.
// Source: contracts/out/MachineReadableOnly.sol/MachineReadableOnly.json
// Regenerate with: cd warden && node tools/gen-abi.mjs
//
// The full ABI, not a hand-picked subset. viem's parseEventLogs needs every
// event definition to decode a reconcile window, and a subset is a second
// place for the truth to live and drift.
`;

writeFileSync(OUT, `${header}export const MRO_ABI = ${JSON.stringify(abi, null, 2)};\n`);
console.log(`wrote ${OUT}: ${abi.length} entries`);
console.log(`functions: ${REQUIRED_FUNCTIONS.join(", ")}`);
console.log(`events:    ${REQUIRED_EVENTS.join(", ")}`);
