// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {LibBit} from "solady/src/utils/LibBit.sol";
import {HeartMask} from "./HeartMask.sol";

/// @notice Draws the code block: the QR modules, split into the heart and the
/// noise around it, as two SVG paths.
///
/// @dev Three things about this library are load-bearing, all measured.
///
/// 1. **Same-colour horizontal runs are merged into one path per colour.** The
///    same picture drawn one `<rect>` per module measured 70,298 bytes; drawn as
///    merged runs inside two paths it measured 4,986. That 14x is the difference
///    between fitting the marketplace byte budget and missing it by a factor of
///    three, so run merging is not an optimisation here, it is the mechanism.
///
/// 2. **The heart and the noise are separated by the shared mask, not by
///    anything stored per token.** `HeartMask` is one 172-byte constant, identical
///    for every token, so a mint carries only its own code. A module is a heart
///    module when the token's code and the mask both have that bit set.
///
/// 3. **Nothing is allocated per run.** A row is read as one word, and each run
///    is composed in a register and written with a single `mstore` into a buffer
///    reserved up front. This is gas, not style, and it is the whole task: the
///    obvious implementation of this library cost 3,198,702 gas against a
///    2,000,000 ceiling. Per-run allocation was almost all of it.
///
/// The output is deliberately byte-for-byte identical to `tools/render-token.mjs`,
/// which is asserted in `CodeRenderer.t.sol` against paths generated by that
/// script. Two independent renderers that must agree is a far stronger check than
/// either one alone, and it is what makes the assembly below safe to write.
library CodeRenderer {
    /// @dev The buffer is sized for the WORST case, not the measured one. A real
    /// token's heart path measures 2,495 bytes and its noise path 1,970, but the
    /// code is written at mint and this library must not corrupt memory if it is
    /// ever handed something degenerate. A row of 37 alternating modules is 19
    /// separate runs, so one class can reach 37 * 19 runs of at most
    /// MAX_RUN_BYTES each. Sizing to the measured figure instead would let an
    /// alternating pattern write roughly 8,000 bytes past the end.
    uint256 private constant MAX_RUNS_PER_ROW = (HeartMask.SIZE + 1) / 2;
    uint256 private constant MAX_RUN_BYTES = 20;
    uint256 private constant PATH_CAPACITY = HeartMask.SIZE * MAX_RUNS_PER_ROW * MAX_RUN_BYTES;

    /// @dev Each run is written as a full 32-byte word, so the last one can reach
    /// past its own end. The buffer carries a spare word for it.
    uint256 private constant SLACK = 32;

    /// @dev Each run is composed into a single word, so its text must fit in 32
    /// bytes. The longest possible run is "M<x> <y>h<w>v1h-<w>z" with three digits
    /// everywhere, which is 20 bytes. Keeping every coordinate below 1000 is what
    /// guarantees that, and the canvas is 51 cells at year zero and grows by two
    /// a year, so this is not a limit anything can reach.
    uint256 private constant MAX_COORD = 1000;

    /// @notice Is module `k` set in a packed bitmap?
    /// @dev Row major, one bit per module, bit 7 of byte 0 is module (0,0). This
    /// is the packing `tools/qart.mjs` produces, and the same one `HeartMask`
    /// uses, so a token's code and the mask can be indexed with identical code.
    function isDark(bytes memory packed, uint256 k) internal pure returns (bool) {
        // Shifting a literal by a variable is deliberate throughout this library:
        // the literal is the bit being placed, and the variable says where.
        // forge-lint: disable-next-line(incorrect-shift)
        return uint8(packed[k >> 3]) & (0x80 >> (k & 7)) != 0;
    }

    /// @notice The code block as two `<path>` elements.
    /// @param code   the token's packed modules, 172 bytes
    /// @param mask   the shared heart target, same packing and size
    /// @param offset where the code's top-left module sits on the canvas
    /// @param heartFill colour for modules that landed on the heart
    /// @param noiseFill colour for every other set module
    /// @dev The noise path is emitted first and the heart second, matching the
    /// reference renderer's draw order. The two sets are disjoint, so the order
    /// changes no pixel; it is fixed only so the two renderers can be compared
    /// byte for byte.
    function paths(
        bytes memory code,
        bytes memory mask,
        uint256 offset,
        string memory heartFill,
        string memory noiseFill
    ) internal pure returns (string memory) {
        require(offset + HeartMask.SIZE < MAX_COORD, "CodeRenderer: offset too large");

        // Filled and finished one at a time. The write slack of the noise path
        // can reach a word past its own content, so the heart's buffer is only
        // allocated once the noise path is complete.
        bytes memory noiseD = new bytes(PATH_CAPACITY + SLACK);
        uint256 noiseLen = _runs(noiseD, code, mask, offset, false);
        bytes memory heartD = new bytes(PATH_CAPACITY + SLACK);
        uint256 heartLen = _runs(heartD, code, mask, offset, true);
        // Cut both buffers back to what was actually written. The slack beyond
        // stays allocated and unread.
        /// @solidity memory-safe-assembly
        assembly {
            mstore(noiseD, noiseLen)
            mstore(heartD, heartLen)
        }

        return string(
            abi.encodePacked(
                '<path fill="', noiseFill, '" d="', noiseD,
                '"/><path fill="', heartFill, '" d="', heartD, '"/>'
            )
        );
    }

    /// @dev Writes one class of modules into `out` as merged horizontal runs and
    /// returns how many bytes were written. A run never crosses a row boundary:
    /// modules 36 and 37 are adjacent in the packing but sit at opposite edges of
    /// the picture, so merging them would draw a cell where there is none.
    function _runs(bytes memory out, bytes memory code, bytes memory mask, uint256 offset, bool wantHeart)
        private
        pure
        returns (uint256 len)
    {
        uint256 size = HeartMask.SIZE;
        uint256 ptr;
        /// @solidity memory-safe-assembly
        assembly {
            ptr := add(out, 0x20)
        }

        for (uint256 y; y < size; ++y) {
            uint256 codeRow = _rowBits(code, y);
            if (codeRow == 0) continue;   // a blank row is most of the quiet edges
            // The mask splits the row in one operation, so the inner loop touches
            // no memory at all.
            uint256 row = wantHeart ? codeRow & _rowBits(mask, y) : codeRow & ~_rowBits(mask, y);
            if (row == 0) continue;

            // Jump run to run rather than testing every module. Walking all 37
            // bits of every row cost 954,000 gas on its own; this visits each run
            // once instead, roughly 370 times in total across both classes.
            while (row != 0) {
                uint256 high = LibBit.fls(row);              // leftmost module still to draw
                // The run ends at the first zero below `high`. Inverting the row
                // turns that zero into the highest set bit of what remains below.
                // forge-lint: disable-next-line(incorrect-shift)
                uint256 gap = ~row & ((1 << high) - 1);
                uint256 low = gap == 0 ? 0 : LibBit.fls(gap) + 1;
                // Cheap next to the 693,747 gas this function costs, and it turns
                // any future miscalculation of PATH_CAPACITY into a revert rather
                // than a silent write into whatever memory follows the buffer.
                require(len + MAX_RUN_BYTES <= PATH_CAPACITY, "CodeRenderer: path overflow");
                len = _writeRun(ptr, len, size - 1 - high + offset, y + offset, high - low + 1);
                // forge-lint: disable-next-line(incorrect-shift)
                row &= (1 << low) - 1;                       // drop the run just drawn
            }
        }
    }

    /// @dev One row of the code as a single word, module (0,y) in the highest of
    /// the 37 live bits.
    ///
    /// Reading a row at a time rather than a module at a time replaces 5,476
    /// bounds-checked byte loads with 74 word loads. A row starts at an arbitrary
    /// bit offset, so this loads the 32 bytes from the row's first byte and shifts
    /// the wanted 37 bits down. On the last row the load reaches a few bytes past
    /// the end of `packed`; those bytes are shifted away unread, and reading past
    /// a memory array is safe -- it either lands in allocated memory or reads zero.
    function _rowBits(bytes memory packed, uint256 y) private pure returns (uint256 bits) {
        uint256 size = HeartMask.SIZE;
        uint256 start = y * size;
        uint256 byteIndex = start >> 3;
        uint256 bitOffset = start & 7;
        /// @solidity memory-safe-assembly
        assembly {
            bits := shr(sub(256, size), shl(bitOffset, mload(add(add(packed, 0x20), byteIndex))))
        }
    }

    /// @dev Composes "M<x> <y>h<w>v1h-<w>z" in a register and writes it with one
    /// `mstore`, returning the new length. Writing 32 bytes for a run of 12 is
    /// deliberate: the surplus is overwritten by the next run, and the buffer
    /// carries a word of slack for the last one.
    function _writeRun(uint256 ptr, uint256 len, uint256 x, uint256 y, uint256 w)
        private
        pure
        returns (uint256)
    {
        uint256 acc = 0x4D;                            // "M"
        uint256 n = 1;
        (acc, n) = _digits(acc, n, x);
        acc = acc << 8 | 0x20;                         // " "
        (acc, n) = _digits(acc, n + 1, y);
        acc = acc << 8 | 0x68;                         // "h"
        (acc, n) = _digits(acc, n + 1, w);
        acc = acc << 32 | 0x7631682D;                  // "v1h-"
        (acc, n) = _digits(acc, n + 4, w);
        acc = acc << 8 | 0x7A;                         // "z"
        unchecked {
            ++n;
        }
        /// @solidity memory-safe-assembly
        assembly {
            mstore(add(ptr, len), shl(shl(3, sub(32, n)), acc))
        }
        return len + n;
    }

    /// @dev Appends the decimal digits of `v` (below 1000) to the accumulator.
    function _digits(uint256 acc, uint256 n, uint256 v) private pure returns (uint256, uint256) {
        if (v >= 100) {
            (acc, n) = (acc << 8 | (0x30 + v / 100), n + 1);
        }
        if (v >= 10) {
            (acc, n) = (acc << 8 | (0x30 + (v / 10) % 10), n + 1);
        }
        return (acc << 8 | (0x30 + v % 10), n + 1);
    }
}
