// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {HeartMask} from "./HeartMask.sol";
import {PathWriter} from "./PathWriter.sol";

/// @notice Draws the code block: the QR modules, split into the heart and the
/// noise around it, as two SVG paths.
///
/// @dev Two things about this library are load-bearing, both measured.
///
/// 1. **The heart and the noise are separated by the shared mask, not by anything
///    stored per token.** `HeartMask` is one 172-byte constant, identical for
///    every token, so a mint carries only its own code. A module is a heart module
///    when the token's code and the mask both have that bit set.
///
/// 2. **A row of modules is read as one word.** Reading module by module cost
///    954,000 gas in the scan alone. See docs/phase0-results.md for the full
///    ladder from 3,198,702 gas down to 714,651.
///
/// The output is deliberately byte-for-byte identical to `tools/render-token.mjs`,
/// which is asserted in `CodeRenderer.t.sol` against paths generated by that
/// script. Two independent renderers that must agree is a far stronger check than
/// either one alone, and it is what makes the assembly here and in `PathWriter`
/// safe to write.
library CodeRenderer {
    /// @dev A row of 37 alternating modules is 19 separate runs, which is the most
    /// any row can produce. No real code looks like that, but the code is written
    /// at mint and this library must not corrupt memory if handed something
    /// degenerate.
    uint256 private constant MAX_RUNS =
        HeartMask.SIZE * ((HeartMask.SIZE + 1) / 2);

    /// @notice Is module `k` set in a packed bitmap?
    /// @dev Row major, one bit per module, bit 7 of byte 0 is module (0,0). This
    /// is the packing `tools/qart.mjs` produces, and the same one `HeartMask`
    /// uses, so a token's code and the mask can be indexed with identical code.
    function isDark(bytes memory packed, uint256 k) internal pure returns (bool) {
        // Shifting a literal by a variable is deliberate throughout this library:
        // the literal is the bit being placed, and the variable says where.
        // forge-lint: disable-next-line(incorrect-shift)
        return uint8(packed[k >> 3]) & (0x80 >> (k & 7)) != 0;
    }

    /// @notice The code block as two `<path>` elements.
    /// @param code   the token's packed modules, 172 bytes
    /// @param mask   the shared heart target, same packing and size
    /// @param offset where the code's top-left module sits on the canvas
    /// @param heartFill colour for modules that landed on the heart
    /// @param noiseFill colour for every other set module
    /// @dev The noise path is emitted first and the heart second. The two sets are
    /// disjoint, so the order changes no pixel; it is fixed only so the two
    /// renderers can be compared byte for byte.
    function paths(
        bytes memory code,
        bytes memory mask,
        uint256 offset,
        string memory heartFill,
        string memory noiseFill
    ) internal pure returns (string memory) {
        require(offset + HeartMask.SIZE < 1000, "CodeRenderer: offset too large");

        PathWriter.Buffer memory noiseBuf = PathWriter.create(MAX_RUNS);
        PathWriter.Buffer memory heartBuf = PathWriter.create(MAX_RUNS);

        uint256 size = HeartMask.SIZE;
        for (uint256 y; y < size; ++y) {
            uint256 codeRow = _rowBits(code, y);
            if (codeRow == 0) continue;   // a blank row is most of the quiet edges
            // The mask splits the row in one operation, so neither call below has
            // to look at the modules again.
            uint256 maskRow = _rowBits(mask, y);
            PathWriter.writeRow(noiseBuf, codeRow & ~maskRow, size, offset, y + offset);
            PathWriter.writeRow(heartBuf, codeRow & maskRow, size, offset, y + offset);
        }

        return string(
            abi.encodePacked(
                '<path fill="', noiseFill, '" d="', PathWriter.seal(noiseBuf),
                '"/><path fill="', heartFill, '" d="', PathWriter.seal(heartBuf), '"/>'
            )
        );
    }

    /// @dev One row of the code as a single word, module (0,y) in the highest of
    /// the 37 live bits.
    ///
    /// Reading a row at a time rather than a module at a time replaces 5,476
    /// bounds-checked byte loads with 74 word loads. A row starts at an arbitrary
    /// bit offset, so this loads the 32 bytes from the row's first byte and shifts
    /// the wanted 37 bits down. On the last row the load reaches a few bytes past
    /// the end of `packed`; those bytes are shifted away unread, and reading past
    /// a memory array is safe -- it either lands in allocated memory or reads zero.
    function _rowBits(bytes memory packed, uint256 y) private pure returns (uint256 bits) {
        uint256 size = HeartMask.SIZE;
        uint256 start = y * size;
        uint256 byteIndex = start >> 3;
        uint256 bitOffset = start & 7;
        /// @solidity memory-safe-assembly
        assembly {
            bits := shr(sub(256, size), shl(bitOffset, mload(add(add(packed, 0x20), byteIndex))))
        }
    }
}
