// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {LibString} from "solady/src/utils/LibString.sol";

import {FrameGeometry} from "./FrameGeometry.sol";
import {PathWriter} from "./PathWriter.sol";
import {TokenView} from "./TokenView.sol";

/// @notice Draws the day frame, the cells not yet earned, and the year rings.
///
/// @dev The frame is the token's history: one cell per credited day, filling
/// from the top, plus one outline ring once the year is finished.
///
/// The frame holds 376 cells and a year is 365 days, because two concentric
/// rings always hold an even count. The 11 spare cells sit at the bottom and
/// light only once the heart is whole, so the ring seals on the day the year
/// completes rather than early.
///
/// MUST stay byte-for-byte identical to `tools/render-token.mjs`;
/// `FrameRenderer.t.sol` asserts it against paths generated by that script.
library FrameRenderer {
    /// @dev One blank cell between the year rings and the day frame, so a ring
    /// can never be mistaken for a day.
    uint256 internal constant GAP = 1;

    /// @dev How many cells the rings occupy on each side: one cell per ring with
    /// one cell of field between them, so they can be counted rather than
    /// merging into a single slab of colour.
    ///
    /// MUST stay identical to ringSpan in tools/render-token.mjs.
    function ringSpan(uint256 ringCount) internal pure returns (uint256) {
        return ringCount == 0 ? 0 : 2 * ringCount - 1;
    }

    /// @notice The ring a token earns for finishing its year, and the ring a
    /// child carries for the line it came from.
    ///
    /// @dev A token stops accruing at 365 credited days, so it has at most ONE
    /// ring of its own, and the echo slot is taken by ANY non-zero echo rather
    /// than by a whole year of it. Both are written as caps rather than as
    /// arithmetic so a swapped renderer can never draw a ring count the chain
    /// cannot produce. The widest canvas is a finished child's 57 cells.
    ///
    /// MUST stay identical to ringBudget in tools/render-token.mjs.
    /// @param level the token's own credited days
    /// @param echo  the days its line had run when it was seeded; 0 if founding
    function ringBudget(uint32 level, uint32 echo)
        internal
        pure
        returns (uint256 own, uint256 echoRings)
    {
        echoRings = echo > 0 ? 1 : 0;
        own = level >= FrameGeometry.DAY_CELLS ? 1 : 0;
    }

    /// @notice The finished-year ring plus the echo ring: the total rings
    /// drawn, which is what sets the canvas size.
    function rings(uint32 level, uint32 echo) internal pure returns (uint256) {
        (uint256 own, uint256 echoRings) = ringBudget(level, echo);
        return own + echoRings;
    }

    /// @notice The canvas edge for a token with `ringCount` rings.
    function canvas(uint256 ringCount) internal pure returns (uint256) {
        return FrameGeometry.BLOCK + 2 * (FrameGeometry.THICK + GAP + ringSpan(ringCount));
    }

    /// @notice The ghost path and the lit path, in that order.
    /// @param colour     the streak colour the earned days and rings are drawn in
    /// @param ghostFill  the colour of a day not yet earned
    /// @dev An empty path is omitted rather than emitted. A brand-new token has
    /// no lit path and a whole one has no ghost path.
    function paths(TokenView memory v, string memory colour, string memory ghostFill)
        internal
        pure
        returns (string memory)
    {
        (uint256 ownRings, uint256 echoRings) = ringBudget(v.level, v.echo);
        uint256 ringCount = ownRings + echoRings;
        uint256 size = canvas(ringCount);
        uint256 frameOff = ringSpan(ringCount) + GAP;

        uint256[] memory litRows = new uint256[](size);
        uint256[] memory ghostRows = new uint256[](size);
        _fill(v, litRows, ghostRows, size, frameOff);

        return _emit(litRows, ghostRows, size, ownRings, echoRings, colour, ghostFill);
    }

    /// @dev Marks every frame cell into one of the two row bitmaps.
    ///
    /// A whole frame skips the per-cell walk: every cell lights, so the
    /// precomputed row bitmap is shifted into place directly. Below wholeness the
    /// walk covers only the days earned, and the ghost is the whole frame minus
    /// what is lit -- one XOR per row instead of a second walk.
    function _fill(
        TokenView memory v,
        uint256[] memory litRows,
        uint256[] memory ghostRows,
        uint256 size,
        uint256 frameOff
    ) private pure {
        bytes memory rowBits = FrameGeometry.rows();

        if (v.level >= FrameGeometry.DAY_CELLS) {
            for (uint256 y; y < FrameGeometry.LOCAL; ++y) {
                litRows[y + frameOff] = _localRow(rowBits, y) << frameOff;
            }
            return;
        }

        bytes memory cells = FrameGeometry.cells();
        uint256 base;
        /// @solidity memory-safe-assembly
        assembly {
            base := add(cells, 0x20)
        }
        uint256 word;
        for (uint256 i; i < v.level; ++i) {
            // Sixteen cells fit in one word, so the constant is read once every
            // sixteen days rather than twice a day.
            if (i & 15 == 0) {
                /// @solidity memory-safe-assembly
                assembly {
                    word := mload(add(base, mul(i, 2)))
                }
            }
            uint256 pair = (word >> (240 - ((i & 15) << 4))) & 0xFFFF;
            uint256 x = (pair >> 8) + frameOff;
            uint256 y = (pair & 0xFF) + frameOff;
            // forge-lint: disable-next-line(incorrect-shift)
            litRows[y] |= 1 << (size - 1 - x);
        }

        for (uint256 y; y < FrameGeometry.LOCAL; ++y) {
            uint256 row = y + frameOff;
            ghostRows[row] = (_localRow(rowBits, y) << frameOff) ^ litRows[row];
        }
    }

    /// @dev Writes both paths, adding the year rings to the lit one as it goes.
    ///
    /// A ring is an outline, so on its own top and bottom rows it fills the whole
    /// width, and everywhere between it contributes one cell at each edge. Rings
    /// nest, so those edge cells are adjacent and merge: any row deep enough to
    /// sit inside every ring has one block of them on each side. Deriving that
    /// per row is what keeps the runs merged, which the byte budget needs.
    function _emit(
        uint256[] memory litRows,
        uint256[] memory ghostRows,
        uint256 size,
        uint256 ownRings,
        uint256 echoRings,
        string memory colour,
        string memory ghostFill
    ) private pure returns (string memory) {
        // Only frame cells go through the row walk -- the rings are appended as
        // bars afterwards -- so one run per frame cell bounds it.
        uint256 maxRuns = FrameGeometry.CELL_COUNT;
        PathWriter.Buffer memory ghostBuf = PathWriter.create(maxRuns);
        PathWriter.Buffer memory litBuf = PathWriter.create(maxRuns);

        for (uint256 y; y < size; ++y) {
            PathWriter.writeRow(ghostBuf, ghostRows[y], size, 0, y);
            PathWriter.writeRow(litBuf, litRows[y], size, 0, y);
        }

        bytes memory ghostD = PathWriter.seal(ghostBuf);
        if (echoRings != 0) {
            // The echo ring is the innermost slot, at depth 2 * ownRings, and
            // is always 53 cells on a side whatever the ring count.
            ghostD = abi.encodePacked(ghostD, echoRingBars(2 * ownRings, 53));
        }
        bytes memory litD = abi.encodePacked(PathWriter.seal(litBuf), _ringBars(ownRings, size));

        bytes memory out;
        if (ghostD.length != 0) out = abi.encodePacked('<path fill="', ghostFill, '" d="', ghostD, '"/>');
        if (litD.length != 0) out = abi.encodePacked(out, '<path fill="', colour, '" d="', litD, '"/>');
        return string(out);
    }

    /// @dev One outline ring per drawn ring, outermost first, as four bars.
    ///
    /// Row by row, each ring would put two one-cell runs on every row it
    /// crosses; as bars it is four runs per ring whatever the canvas size. GAP
    /// keeps a blank cell between the innermost ring and the day frame, so no run
    /// here could ever have merged with a frame run.
    function _ringBars(uint256 ringCount, uint256 size) private pure returns (bytes memory d) {
        for (uint256 k; k < ringCount; ++k) {
            uint256 o = 2 * k;              // ring k sits at depth 2k
            uint256 len = size - 2 * o;     // its full width, corners included
            d = abi.encodePacked(
                d,
                "M", LibString.toString(o), " ", LibString.toString(o),
                "h", LibString.toString(len), "v1h-", LibString.toString(len), "z",
                "M", LibString.toString(o), " ", LibString.toString(size - 1 - o),
                "h", LibString.toString(len), "v1h-", LibString.toString(len), "z"
            );
            if (len > 2) {
                uint256 h = len - 2;        // the sides, corners already drawn
                d = abi.encodePacked(
                    d,
                    "M", LibString.toString(o), " ", LibString.toString(o + 1),
                    "h1v", LibString.toString(h), "h-1z",
                    "M", LibString.toString(size - 1 - o), " ", LibString.toString(o + 1),
                    "h1v", LibString.toString(h), "h-1z"
                );
            }
        }
    }

    /// @dev The echo ring: the innermost ring, drawn as a DASH -- two cells on,
    /// two off -- in the GHOST fill rather than the token's own colour. It is
    /// the years the token inherited, so it must not read as years it has kept.
    ///
    /// A cell is INK when its offset along its own edge is 0 or 1 mod 4,
    /// measured in x from `o` on the horizontal edges and in y from `o` on the
    /// vertical ones. Offsets 0 and 1 are both ink, so all four corners are
    /// drawn and the phase is unambiguous on every edge; 53 = 13 * 4 + 1, so
    /// offset 52 is ink too and every edge is anchored at both ends. Consecutive
    /// ink is emitted as ONE run, which is what keeps the run count down.
    ///
    /// The side length is ALWAYS 53: with r rings the innermost sits at
    /// o = 2(r-1) and canvas is 49 + 4r, so the depth cancels.
    ///
    /// MUST stay identical to echoRingBars in tools/render-token.mjs.
    /// @param o   the ring's depth from the canvas edge, in cells
    /// @param len its full width, corners included
    function echoRingBars(uint256 o, uint256 len) internal pure returns (bytes memory d) {
        // `len - 1` below is unsigned, so a zero length would underflow to
        // 2**256-1 and loop forever. A ring of under two cells has no edges to
        // mark anyway.
        if (len < 2) return d;
        uint256 last = o + len - 1;
        // The two horizontal edges, corners included. A group starts every
        // fourth offset and is two cells long, emitted as ONE run.
        for (uint256 i; i < len; i += 4) {
            // The group starting at the final offset has no room for a second
            // cell. Clipped, not skipped: 53 = 13 * 4 + 1, so that offset is ink
            // and it is what anchors the far end of the edge.
            uint256 run = len - i >= 2 ? 2 : 1;
            uint256 x = o + i;
            d = abi.encodePacked(
                d,
                "M", LibString.toString(x), " ", LibString.toString(o),
                "h", LibString.toString(run), "v1h-", LibString.toString(run), "z",
                "M", LibString.toString(x), " ", LibString.toString(last),
                "h", LibString.toString(run), "v1h-", LibString.toString(run), "z"
            );
        }
        // The two vertical edges. Offsets run from 1 to len - 2, because both
        // corners belong to the horizontal edges that already drew them.
        if (len > 2) {
            // Offset 1 is ink and stands alone: offset 0 is its group's other
            // half and was drawn above.
            d = abi.encodePacked(
                d,
                "M", LibString.toString(o), " ", LibString.toString(o + 1), "h1v1h-1z",
                "M", LibString.toString(last), " ", LibString.toString(o + 1), "h1v1h-1z"
            );
            for (uint256 i = 4; i < len - 1; i += 4) {
                uint256 run = (len - 1) - i >= 2 ? 2 : 1;
                uint256 y = o + i;
                d = abi.encodePacked(
                    d,
                    "M", LibString.toString(o), " ", LibString.toString(y),
                    "h1v", LibString.toString(run), "h-1z",
                    "M", LibString.toString(last), " ", LibString.toString(y),
                    "h1v", LibString.toString(run), "h-1z"
                );
            }
        }
    }

    /// @dev One local row of the frame bitmap, bit LOCAL-1-x set for a frame cell.
    /// @dev Eight bytes per row. The load reaches past the end of the constant on
    /// the last row; those bytes are shifted away unread, and reading past a
    /// memory array is safe -- it either lands in allocated memory or reads zero.
    function _localRow(bytes memory rowBits, uint256 y) private pure returns (uint256 r) {
        /// @solidity memory-safe-assembly
        assembly {
            r := shr(192, mload(add(add(rowBits, 0x20), mul(y, 8))))
        }
    }
}
