// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {FrameGeometry} from "./FrameGeometry.sol";
import {PathWriter} from "./PathWriter.sol";
import {TokenView} from "./TokenView.sol";

/// @notice Draws the day frame, the cells not yet earned, and the year rings.
///
/// @dev This is the part of the image that carries the piece's subject. The code
/// block is fixed at mint and never changes; the frame is the token's history --
/// one cell per credited day, filling from the top so the ring closes as the year
/// goes on, plus one outline ring for every completed year.
///
/// Two cells matter more than the rest. The frame holds 376 cells but a year is
/// 365 days, because two concentric rings always hold an even count and 365 is
/// odd. The 11 spare cells sit at the bottom and light only once the heart is
/// whole, so the ring stays visibly open all year and seals on the day the year
/// completes.
///
/// The output is byte-for-byte identical to `tools/render-token.mjs`, asserted in
/// `FrameRenderer.t.sol` against paths generated by that script.
library FrameRenderer {
    /// @dev One blank cell between the year rings and the day frame, so a ring
    /// can never be mistaken for a day.
    uint256 internal constant GAP = 1;

    /// @dev Year rings stop growing the canvas here. Two independent measurements
    /// put the ceiling in the same place. By bytes: the reference renderer's
    /// tokenURI crosses the 20,000 limit at 85 completed years (84 measured at
    /// 19,932, 85 at 20,044), so 80 leaves 448 bytes of headroom. By this
    /// renderer: a canvas row is held in one 256-bit word, and 80 rings make the
    /// canvas 211 cells while 107 would make it 265 and break that.
    ///
    /// Eighty years is far past any plausible tenure, and the alternative to a cap
    /// is a token that eventually cannot be rendered at all.
    ///
    /// MUST stay identical to MAX_RINGS in tools/render-token.mjs.
    uint256 internal constant MAX_RINGS = 80;

    /// @notice Completed years, which is how many rings the token has earned.
    function rings(uint32 level) internal pure returns (uint256 r) {
        r = level / FrameGeometry.DAY_CELLS;
        if (r > MAX_RINGS) r = MAX_RINGS;
    }

    /// @notice The canvas edge for a token with `ringCount` rings.
    function canvas(uint256 ringCount) internal pure returns (uint256) {
        return FrameGeometry.BLOCK + 2 * (FrameGeometry.THICK + GAP + ringCount);
    }

    /// @notice The ghost path and the lit path, in that order.
    /// @param colour     the streak colour the earned days and rings are drawn in
    /// @param ghostFill  the colour of a day not yet earned
    /// @dev An empty path is omitted rather than emitted, because an empty
    /// `<path>` element is pure waste in a budget measured in bytes. A brand-new
    /// token has no lit path and a whole one has no ghost path.
    function paths(TokenView memory v, string memory colour, string memory ghostFill)
        internal
        pure
        returns (string memory)
    {
        uint256 ringCount = rings(v.level);
        uint256 size = canvas(ringCount);
        uint256 frameOff = ringCount + GAP;

        uint256[] memory litRows = new uint256[](size);
        uint256[] memory ghostRows = new uint256[](size);
        _fill(v, litRows, ghostRows, size, frameOff);

        return _emit(litRows, ghostRows, size, ringCount, colour, ghostFill);
    }

    /// @dev Marks every frame cell into one of the two row bitmaps.
    ///
    /// A whole frame skips the per-cell walk entirely: every cell lights, so the
    /// precomputed row bitmap can be shifted into place directly. That is worth
    /// having rather than tidy -- walking the 376 cells measured 1,131 gas each,
    /// about 425,000 in total, and a token spends most of its life whole.
    ///
    /// Below wholeness the walk covers only the days actually earned, and the
    /// ghost is then the whole frame minus what is lit: one XOR per row instead of
    /// a second walk over the remainder.
    function _fill(
        TokenView memory v,
        uint256[] memory litRows,
        uint256[] memory ghostRows,
        uint256 size,
        uint256 frameOff
    ) private pure {
        bytes memory rowBits = FrameGeometry.rows();

        if (v.level >= FrameGeometry.DAY_CELLS) {
            for (uint256 y; y < FrameGeometry.LOCAL; ++y) {
                litRows[y + frameOff] = _localRow(rowBits, y) << frameOff;
            }
            return;
        }

        bytes memory cells = FrameGeometry.cells();
        uint256 base;
        /// @solidity memory-safe-assembly
        assembly {
            base := add(cells, 0x20)
        }
        uint256 word;
        for (uint256 i; i < v.level; ++i) {
            // Sixteen cells fit in one word, so the constant is read once every
            // sixteen days rather than twice a day.
            if (i & 15 == 0) {
                /// @solidity memory-safe-assembly
                assembly {
                    word := mload(add(base, mul(i, 2)))
                }
            }
            uint256 pair = (word >> (240 - ((i & 15) << 4))) & 0xFFFF;
            uint256 x = (pair >> 8) + frameOff;
            uint256 y = (pair & 0xFF) + frameOff;
            // forge-lint: disable-next-line(incorrect-shift)
            litRows[y] |= 1 << (size - 1 - x);
        }

        for (uint256 y; y < FrameGeometry.LOCAL; ++y) {
            uint256 row = y + frameOff;
            ghostRows[row] = (_localRow(rowBits, y) << frameOff) ^ litRows[row];
        }
    }

    /// @dev Writes both paths, adding the year rings to the lit one as it goes.
    ///
    /// A ring is an outline, so on its own top and bottom rows it fills the whole
    /// width, and everywhere between it contributes one cell at each edge. Rings
    /// nest, so those edge cells are adjacent and merge: any row deep enough to
    /// sit inside every ring has exactly one block of them on each side. Deriving
    /// that per row is O(canvas); drawing each ring separately would be O(rings x
    /// canvas), which at the cap is 16,880 iterations instead of 211.
    function _emit(
        uint256[] memory litRows,
        uint256[] memory ghostRows,
        uint256 size,
        uint256 ringCount,
        string memory colour,
        string memory ghostFill
    ) private pure returns (string memory) {
        // A row can hold at most one run per frame cell, plus the two blocks of
        // ring cells. Bounding this by what the geometry can produce rather than
        // by what it typically does is what keeps the buffer safe.
        uint256 maxRuns = FrameGeometry.CELL_COUNT + 2 * size;
        PathWriter.Buffer memory ghostBuf = PathWriter.create(maxRuns);
        PathWriter.Buffer memory litBuf = PathWriter.create(maxRuns);

        // forge-lint: disable-next-line(incorrect-shift)
        uint256 full = (1 << size) - 1;
        // forge-lint: disable-next-line(incorrect-shift)
        uint256 edges = ringCount == 0 ? 0 : (((1 << ringCount) - 1) << (size - ringCount)) | ((1 << ringCount) - 1);

        for (uint256 y; y < size; ++y) {
            uint256 lit = litRows[y];
            if (ringCount != 0) {
                // Rows inside a ring's own top or bottom edge are filled across.
                lit |= (y < ringCount || size - 1 - y < ringCount) ? full : edges;
            }
            PathWriter.writeRow(ghostBuf, ghostRows[y], size, 0, y);
            PathWriter.writeRow(litBuf, lit, size, 0, y);
        }

        bytes memory ghostD = PathWriter.seal(ghostBuf);
        bytes memory litD = PathWriter.seal(litBuf);

        bytes memory out;
        if (ghostD.length != 0) out = abi.encodePacked('<path fill="', ghostFill, '" d="', ghostD, '"/>');
        if (litD.length != 0) out = abi.encodePacked(out, '<path fill="', colour, '" d="', litD, '"/>');
        return string(out);
    }

    /// @dev One local row of the frame bitmap, bit LOCAL-1-x set for a frame cell.
    /// @dev Eight bytes per row. The load reaches past the end of the constant on
    /// the last row; those bytes are shifted away unread, and reading past a
    /// memory array is safe -- it either lands in allocated memory or reads zero.
    function _localRow(bytes memory rowBits, uint256 y) private pure returns (uint256 r) {
        /// @solidity memory-safe-assembly
        assembly {
            r := shr(192, mload(add(add(rowBits, 0x20), mul(y, 8))))
        }
    }
}
