// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

// GENERATED by tools/heart-mask.mjs -- do not edit by hand.
// Change the generator and re-run it instead.
//
// The heart target for a 57x57 code, one bit per module, row major,
// bit 7 of byte 0 is module (0,0). Identical for every token: only the noise
// around the heart differs, so this is stored once rather than per mint.
library HeartMask {
    uint256 internal constant SIZE = 57;
    uint256 internal constant BYTES = 407;

    function bits() internal pure returns (bytes memory) {
        return hex"00000000000000000000000000000001fc0001fc000007ffc007ffc0000ffff80ffff8001ffffe0fffff001fffffdfffffc00fffffefffffe00ffffffffffff80ffffffffffffe07ffffffffffff07ffffffffffffc3ffffffffffffe1fffffffffffff1fffffffffffffcfffffffffffffe7fffffffffffff3fffffffffffff9fffffffffffffcfffffffffffffe7fffffffffffff3fffffffffffff9fffffffffffffcfffffffffffffe3ffffffffffffe1fffffffffffff0fffffffffffff87ffffffffffffc1ffffffffffffc0ffffffffffffe07ffffffffffff01ffffffffffff00ffffffffffff803fffffffffff800fffffffffff8007ffffffffffc001ffffffffffc000ffffffffffe0003fffffffffe0000fffffffffe00003ffffffffe00000ffffffffe000003fffffffe000000fffffffe0000003ffffffe0000000ffffffe00000003fffffe00000000fffffe000000003ffffe0000000007fffc0000000001fffc00000000003ff800000000000ff8000000000001f000000000000070000000000000100000000000000000000000";
    }
}
