// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

// GENERATED by tools/heart-mask.mjs -- do not edit by hand.
// Change the generator and re-run it instead.
//
// The heart target for a 37x37 code, one bit per module, row major,
// bit 7 of byte 0 is module (0,0). Identical for every token: only the noise
// around the heart differs, so this is stored once rather than per mint.
library HeartMask {
    uint256 internal constant SIZE = 37;
    uint256 internal constant BYTES = 172;

    function bits() internal pure returns (bytes memory) {
        return hex"00000000000380038000ff80ff801fff1fff01fffdfffc1ffffffff0ffffffff8ffffffffe7ffffffff3ffffffff9ffffffffcffffffffe7ffffffff3ffffffff9ffffffffcffffffffe7ffffffff3ffffffff8ffffffff87fffffffc1fffffffc0fffffffe03ffffffe01fffffff007ffffff001ffffff0007fffff0003fffff8000fffff80001ffff000007fff000001fff0000007ff0000000fe00000003e000000004000000002000000";
    }
}
