// Generates contracts/test/ColourFixture.sol: the 88 colour boundary pairs and
// the colour the JS reference produces for each.
//
// The two renderers compute the tier and the lapse independently, in two
// languages. The full-render differential pins a few dozen states; this pins
// every threshold on both axes, one step either side, for the price of a table.
// A boundary off by one would be invisible in the images and permanent once
// tokens exist.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { lapsedColour, tierColour } from "./render-token.mjs";
import { colourCases } from "./state-matrix.mjs";

export function rows() {
  return colourCases().map(c => ({
    ...c,
    live: tierColour(c.streak),
    lapsed: lapsedColour(c.streak, c.lastDay, c.today),
  }));
}

export function render(all) {
  const lines = all.map(r =>
    `        c[i++] = Case(${r.streak}, ${r.lastDay}, ${r.today}, "${r.live}", "${r.lapsed}");`
  ).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/colour-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/colour-fixture.mjs
pragma solidity ^0.8.30;

/// @notice Every tier threshold crossed with every lapse threshold, one step
/// either side, and the colour tools/render-token.mjs produces for each.
library ColourFixture {
    struct Case {
        uint32 streak;
        uint32 lastDay;
        uint32 today;
        string live;    // Palette.tier(streak)
        string lapsed;  // Palette.lapsed(streak, lastDay, today)
    }

    uint256 internal constant COUNT = ${all.length};

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
${lines}
    }
}
`;
}

const here = dirname(fileURLToPath(import.meta.url));

if (process.argv[1] && process.argv[1].endsWith("colour-fixture.mjs")) {
  const all = rows();
  const out = join(here, "..", "contracts", "test", "ColourFixture.sol");
  writeFileSync(out, render(all));
  const inks = new Set(all.flatMap(r => [r.live, r.lapsed]));
  console.error(`${all.length} pairs, ${inks.size} distinct inks: ${[...inks].sort().join(" ")}`);
  console.error(`wrote ${out}`);
}
