// Generates contracts/test/CombinationFixture.sol: every one of the 459
// renderable Mark combinations, with the byte length and keccak256 of the
// tokenURI the JS reference produces for each.
//
// WHY. combination-sweep.mjs renders all 459 and DECODES them -- it answers
// "does the QR still scan wearing this?" and never compares the two renderers.
// The cross-language differential (RenderFixture) covers 15 Mark-bearing states
// out of 189 legal sets, so combinations including Hush + Break, Aura + Break
// and the bought Iris under Break had no differential case at all. Two
// renderers can each be self-consistent and disagree with each other; that is
// the entire reason a differential exists, and the Mark surface was the thinnest
// part of it.
//
// This is the whole set rather than a sample. Rendering a tokenURI is string
// work with no rasterising -- the expensive part of the decode sweep is resvg,
// which this never touches -- so the full 459 costs a few seconds here and a
// few seconds in Solidity. A sample would have needed a rule for what to leave
// out, and the honest rule turned out to be "nothing".
//
//   node tools/combination-fixture.mjs [tokenId] [domain]
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { keccak256, toBytes } from "viem";

import { tokenBitmap, SIZE } from "./token-bitmap.mjs";
import { heartMaskBytes } from "./heart-mask.mjs";
import { unpackModules } from "./qart.mjs";
import { tokenUri } from "./render-token.mjs";
import { generateCombinations, packCombination } from "./mark-combinations.mjs";

/// The state every combination is rendered at, held constant so the ONLY
/// variable is the Mark set. Whole, at the top tier, one ring: the state in
/// which the most Marks are legal and the most surface is drawn.
///
/// `irisRun` matters whenever the EARNED Iris is held -- it stores the run it
/// was granted on, which the renderer reads for that eye's ink. Fixed at 400
/// so the earned and bought routes are distinguishable in the output.
const STATE = { level: 365, streak: 400, lastDay: 1000, today: 1000, irisRun: 400 };

export function fixtures(domain, tokenId) {
  const bitmap = tokenBitmap(domain, tokenId);
  const modules = unpackModules(Buffer.from(bitmap.hex, "hex"), SIZE);
  const want = unpackModules(heartMaskBytes(), SIZE);
  const { combos } = generateCombinations();

  return combos.map(c => {
    const uri = tokenUri(modules, want, SIZE, {
      tokenId,
      mintDay: 900,
      ...STATE,
      marks: c.ids,
      irisVariant: c.irisVariant,
      tintVariant: c.tintVariant,
    });
    return {
      ...c,
      marksBits: packCombination(c, STATE.irisRun),
      bytes: uri.length,
      hash: keccak256(toBytes(uri)),
    };
  });
}

export function render(all, domain, tokenId) {
  const lines = all.map(r =>
    `        c[i++] = Case(${r.marksBits}, ${r.bytes}, ${r.hash}, "${r.label}");`
  ).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/combination-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/combination-fixture.mjs ${tokenId} ${domain}
pragma solidity ^0.8.30;

/// @notice All ${all.length} renderable Mark combinations, with the byte length and
/// keccak256 of the tokenURI tools/render-token.mjs produces for each.
/// Token ${tokenId} on ${domain}.
///
/// @dev The Mark half of the cross-language differential. RenderFixture covers
/// 15 Mark-bearing states; the decode sweep covers all 459 but never compares
/// the two renderers. This closes that: every legal set, every Iris shape and
/// every Tint ink, diffed byte for byte.
///
/// Every case is rendered at the SAME state -- level ${STATE.level}, streak ${STATE.streak},
/// lastDay ${STATE.lastDay}, today ${STATE.today}, irisRun ${STATE.irisRun} -- so a failure is
/// about the Marks and nothing else.
library CombinationFixture {
    struct Case {
        uint256 marks;
        uint256 bytesLen;
        bytes32 hash;
        string label;
    }

    uint256 internal constant COUNT = ${all.length};

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
${lines}
    }
}
`;
}

const tokenId = Number(process.argv[2] ?? 1);
const domain = process.argv[3] ?? "example.com";
const here = dirname(fileURLToPath(import.meta.url));
const all = fixtures(domain, tokenId);
const out = join(here, "..", "contracts", "test", "CombinationFixture.sol");
writeFileSync(out, render(all, domain, tokenId));
console.log(
  `${all.length} combinations, ${Math.min(...all.map(a => a.bytes))}-${Math.max(...all.map(a => a.bytes))} bytes`
);
console.log(`wrote ${out}`);
