// Generates contracts/src/render/HeartMask.sol: the heart target the code is
// driven towards, as one shared 172-byte constant.
//
// Shared, not per token, and that is the decision that makes duotone affordable.
// The target is identical for every token -- only the noise differs -- so storing
// it per token would add 172 bytes to every mint carrying no information at all.
// The renderer splits a token's modules into heart and noise by testing each
// module against this one mask.
import { writeFileSync } from "node:fs";
import { heartTarget } from "./heart-target.mjs";
import { packModules, VERSION_SIZE } from "./qart.mjs";

export const SIZE = VERSION_SIZE;
export const OUT = "../contracts/src/render/HeartMask.sol";

// The packed target: bit 7 of byte 0 is module (0,0), row major. Same packing as
// qart.packModules, so a bitmap and this mask can be indexed identically.
export function heartMaskBytes() {
  const { want } = heartTarget(SIZE);
  return packModules(want, SIZE);
}

const hex = bytes => Array.from(bytes, b => b.toString(16).padStart(2, "0")).join("");

export function toSolidity() {
  const bytes = heartMaskBytes();
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

// GENERATED by tools/heart-mask.mjs -- do not edit by hand.
// Change the generator and re-run it instead.
//
// The heart target for a ${SIZE}x${SIZE} code, one bit per module, row major,
// bit 7 of byte 0 is module (0,0). Identical for every token: only the noise
// around the heart differs, so this is stored once rather than per mint.
library HeartMask {
    uint256 internal constant SIZE = ${SIZE};
    uint256 internal constant BYTES = ${bytes.length};

    function bits() internal pure returns (bytes memory) {
        return hex"${hex(bytes)}";
    }
}
`;
}

if (process.argv[1] && process.argv[1].endsWith("heart-mask.mjs")) {
  const sol = toSolidity();
  writeFileSync(new URL(OUT, import.meta.url), sol);
  const bytes = heartMaskBytes();
  const on = Array.from(bytes).reduce((n, b) => n + b.toString(2).split("1").length - 1, 0);
  console.log(`wrote HeartMask.sol: ${SIZE}x${SIZE}, ${bytes.length} bytes, ${on} modules in the heart`);
}
