// Generates contracts/test/IdentityFixture.sol: the same rendered state at
// several token IDENTITIES -- a different id, a different mint day, and the
// bitmap that belongs to each.
//
// WHY THIS IS A SEPARATE FIXTURE from render-fixture.mjs. That one varies the
// token's STATE (tier, rings, fill, Marks, lifecycle) and holds the identity
// fixed at token 1, mint day 900, on one bitmap -- necessarily, because every
// case there shares a single `_bitmap()` in the test. So `toString(v.tokenId)`
// on the Solidity side and a JS template literal on the other were compared at
// exactly one value, one digit long, and the `%23` that precedes it with them.
// A four-digit id costs a different number of bytes and is where a length or
// an off-by-one in the name would show.
//
// Each case carries its OWN bitmap, because a bitmap encodes its own url: the
// payload is `https://<domain>/t/<id>#`, so token 4242's code is not token 1's.
// That is also why this is a generator and not a loop in the test -- solving
// one bitmap takes about three seconds.
//
//   node tools/identity-fixture.mjs [domain]
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { keccak256, toBytes } from "viem";

import { tokenBitmap, SIZE } from "./token-bitmap.mjs";
import { heartMaskBytes } from "./heart-mask.mjs";
import { unpackModules } from "./qart.mjs";
import { tokenUri } from "./render-token.mjs";

/// One state, held constant across every identity, so the ONLY thing that
/// differs between cases is who the token is. A whole token at the top tier:
/// it draws the most surface, so a name-length error has the most room to
/// hide behind everything else in the document.
const STATE = { level: 365, streak: 400, lastDay: 1000, today: 1000 };

/// The identities worth rendering. One digit, two, four, and the largest id
/// the contract will ever mint -- `mint` rejects anything above 2**32 - 1, so
/// 4294967295 is the widest `toString` this renderer can be asked for.
export const IDENTITIES = [
  { tokenId: 1, mintDay: 900, label: "id 1, one digit" },
  { tokenId: 42, mintDay: 0, label: "id 42, mint day zero" },
  { tokenId: 4242, mintDay: 12345, label: "id 4242, four digits" },
  { tokenId: 4294967295, mintDay: 16777215, label: "id 2**32-1, the widest the contract can mint" },
];

export function fixtures(domain) {
  const want = unpackModules(heartMaskBytes(), SIZE);

  return IDENTITIES.map(idc => {
    const bitmap = tokenBitmap(domain, idc.tokenId);
    const modules = unpackModules(Buffer.from(bitmap.hex, "hex"), SIZE);
    const uri = tokenUri(modules, want, SIZE, {
      tokenId: idc.tokenId,
      mintDay: idc.mintDay,
      ...STATE,
    });
    return { ...idc, code: bitmap.hex, bytes: uri.length, hash: keccak256(toBytes(uri)) };
  });
}

export function render(all, domain) {
  const lines = all.map(r =>
    `        c[i++] = Case(${r.tokenId}, ${r.mintDay}, ${r.bytes}, ${r.hash}, hex"${r.code}", "${r.label}");`
  ).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/identity-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/identity-fixture.mjs ${domain}
pragma solidity ^0.8.30;

/// @notice One rendered state at four token identities, with the byte length
/// and keccak256 of the tokenURI tools/render-token.mjs produces for each.
///
/// @dev RenderFixture varies STATE at a fixed identity. This varies IDENTITY at
/// a fixed state, which is the axis that file cannot cover: every case there
/// shares one bitmap, and a bitmap encodes its own token's url.
///
/// State held constant across all four: level ${STATE.level}, streak ${STATE.streak},
/// lastDay ${STATE.lastDay}, today ${STATE.today}, no Marks, live.
library IdentityFixture {
    struct Case {
        uint256 tokenId;
        uint32 mintDay;
        uint256 bytesLen;
        bytes32 hash;
        bytes code;
        string label;
    }

    uint256 internal constant COUNT = ${all.length};

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
${lines}
    }
}
`;
}

const domain = process.argv[2] ?? "example.com";
const here = dirname(fileURLToPath(import.meta.url));
const all = fixtures(domain);
const out = join(here, "..", "contracts", "test", "IdentityFixture.sol");
writeFileSync(out, render(all, domain));
console.log(`${all.length} identities, ${Math.min(...all.map(a => a.bytes))}-${Math.max(...all.map(a => a.bytes))} bytes`);
console.log(`wrote ${out}`);
