// Generates contracts/test/RenderFixture.sol: every state in the render matrix,
// with the byte length and keccak256 of the complete tokenURI the JS reference
// produces for it.
//
// Hashes rather than the strings themselves, because one tokenURI is around
// 9,000 bytes and thirty-two of them embedded in a test file would be
// unreadable. The byte length sits alongside each hash so a failure says
// whether the two renderers disagree on length or only on content.
//
//   node tools/render-fixture.mjs [tokenId] [domain]
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { keccak256, toBytes } from "viem";

import { tokenBitmap, SIZE } from "./token-bitmap.mjs";
import { heartMaskBytes } from "./heart-mask.mjs";
import { unpackModules } from "./qart.mjs";
import { tokenUri } from "./render-token.mjs";
import { renderCases, soakCases } from "./state-matrix.mjs";

/// `marks` is already an array of Mark ids (1..10) -- id n is bit n.
export const marksToBits = ids =>
  (ids ?? []).reduce((acc, id) => acc | (1n << BigInt(id)), 0n);

/// The full `_marks` word a case renders with: the Mark bits, plus whichever
/// of the Task 6 variant/run bits the case set. MUST mirror the bit layout
/// `applyMark` writes on chain (bits 16-23 Iris shape, 24-31 Tint ink, 32-63
/// the earned run) -- `render-token.mjs`'s `renderSvg`/`tokenUri` read
/// `irisVariant`/`tintVariant`/`irisRun` as SEPARATE state fields when the JS
/// side renders a case, so if this function does not fold them back into the
/// same word RenderMatrixTest.sol reconstructs `TokenView.marks` from, the
/// Solidity side would render shape/ink 0 while the JS reference rendered
/// whatever the case actually asked for -- a silent mismatch the differential
/// test would then (correctly) fail on.
export const packMarks = c => {
  let bits = marksToBits(c.marks);
  if (c.irisVariant) bits |= BigInt(c.irisVariant) << 16n;
  if (c.tintVariant) bits |= BigInt(c.tintVariant) << 24n;
  if (c.irisRun) bits |= BigInt(c.irisRun) << 32n;
  return bits;
};

export function fixtures(domain, tokenId) {
  const bitmap = tokenBitmap(domain, tokenId);
  const modules = unpackModules(Buffer.from(bitmap.hex, "hex"), SIZE);
  const want = unpackModules(heartMaskBytes(), SIZE);

  return renderCases().map(c => {
    const uri = tokenUri(modules, want, SIZE, { tokenId, mintDay: 900, ...c });
    return {
      ...c,
      marksBits: packMarks(c),
      bytes: uri.length,
      hash: keccak256(toBytes(uri)),
    };
  });
}

export function render(all, domain, tokenId) {
  const lines = all.map(r =>
    `        c[i++] = Case(${r.level}, ${r.streak}, ${r.lastDay}, ${r.today}, `
    + `${r.marksBits}, ${!!r.resting}, ${!!r.sunset}, ${r.sunsetDay ?? 0}, `
    + `${r.fellRun ?? 0}, ${r.fellDay ?? 0}, ${r.bytes}, ${r.hash}, "${r.label}");`
  ).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs ${tokenId} ${domain}
pragma solidity ^0.8.30;

/// @notice Every state in the render matrix, with the byte length and
/// keccak256 of the tokenURI tools/render-token.mjs produces for it.
/// Token ${tokenId} on ${domain}.
library RenderFixture {
    struct Case {
        uint32 level;
        uint32 streak;
        uint32 lastDay;
        uint32 today;
        uint256 marks;
        bool resting;
        bool sunset;
        uint32 sunsetDay;
        uint16 fellRun;
        uint24 fellDay;
        uint256 bytesLen;
        bytes32 hash;
        string label;
    }

    uint256 internal constant COUNT = ${all.length};

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
${lines}
    }
}
`;
}

/// The same states as Solidity the deploy script can walk, without the hashes:
/// the on-chain clock is not the fixture's, so a hash could not match anyway.
/// A lapse is carried as a GAP in days and rebuilt against the real clock.
///
/// Sunset is excluded on purpose. It is piece-wide and irreversible, so calling
/// it inside the batch would freeze all twenty-six other tokens and every state
/// read afterwards would be wrong. The soak applies it last, on its own.
export function renderSoakStates() {
  const cases = soakCases().filter(c => !c.sunset);
  const lines = cases.map((c, i) =>
    `        s[${i}] = State(${c.level}, ${c.streak}, ${(c.today ?? 0) - (c.lastDay ?? 0)}, `
    + `${packMarks(c)}, ${!!c.resting}, "${c.label}");`
  ).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs
pragma solidity ^0.8.30;

/// @notice Every state the Sepolia soak drives a token through, one token each.
/// @dev \`gap\` is days since the last check-in, rebuilt against the chain's own
/// clock rather than the fixture's. Sunset is not here: it is piece-wide and
/// irreversible, so the soak applies it last and on its own.
library SoakStates {
    struct State {
        uint32 level;
        uint32 streak;
        uint32 gap;
        uint256 marks;
        bool resting;
        string label;
    }

    uint256 internal constant COUNT = ${cases.length};

    function all() internal pure returns (State[] memory s) {
        s = new State[](COUNT);
${lines}
    }
}
`;
}

const here = dirname(fileURLToPath(import.meta.url));

if (process.argv[1] && process.argv[1].endsWith("render-fixture.mjs")) {
  const [tokenId = "1", domain = "example.com"] = process.argv.slice(2);
  const all = fixtures(domain, Number(tokenId));
  const out = join(here, "..", "contracts", "test", "RenderFixture.sol");
  writeFileSync(out, render(all, domain, tokenId));
  const soakOut = join(here, "..", "contracts", "script", "SoakStates.sol");
  writeFileSync(soakOut, renderSoakStates());
  console.error(`wrote ${soakOut}`);
  const sizes = all.map(r => r.bytes);
  console.error(`${all.length} states, ${Math.min(...sizes)}-${Math.max(...sizes)} bytes`);
  console.error(`wrote ${out}`);
}
