// Generates contracts/test/RenderFixture.sol: every state in the render matrix,
// with the byte length and keccak256 of the complete tokenURI the JS reference
// produces for it.
//
// Hashes rather than the strings themselves, because one tokenURI is around
// 9,000 bytes and thirty-two of them embedded in a test file would be
// unreadable. The byte length sits alongside each hash so a failure says
// whether the two renderers disagree on length or only on content.
//
//   node tools/render-fixture.mjs [tokenId] [domain]
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { keccak256, toBytes } from "viem";

import { tokenBitmap, SIZE } from "./token-bitmap.mjs";
import { heartMaskBytes } from "./heart-mask.mjs";
import { unpackModules } from "./qart.mjs";
import { tokenUri, MARKS } from "./render-token.mjs";
import { renderCases } from "./state-matrix.mjs";

/// Mark id n is bit n, and MARKS is in ladder order, so index i is bit i+1.
export const marksToBits = names =>
  (names ?? []).reduce((acc, n) => acc | (1n << BigInt(MARKS.indexOf(n) + 1)), 0n);

export function fixtures(domain, tokenId) {
  const bitmap = tokenBitmap(domain, tokenId);
  const modules = unpackModules(Buffer.from(bitmap.hex, "hex"), SIZE);
  const want = unpackModules(heartMaskBytes(), SIZE);

  return renderCases().map(c => {
    const uri = tokenUri(modules, want, SIZE, { tokenId, mintDay: 900, ...c });
    return {
      ...c,
      marksBits: marksToBits(c.marks),
      bytes: uri.length,
      hash: keccak256(toBytes(uri)),
    };
  });
}

export function render(all, domain, tokenId) {
  const lines = all.map(r =>
    `        c[i++] = Case(${r.level}, ${r.streak}, ${r.lastDay}, ${r.today}, `
    + `${r.marksBits}, ${!!r.resting}, ${!!r.sunset}, ${r.bytes}, ${r.hash}, "${r.label}");`
  ).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/render-fixture.mjs -- do not edit by hand.
// Regenerate with: node tools/render-fixture.mjs ${tokenId} ${domain}
pragma solidity ^0.8.30;

/// @notice Every state in the render matrix, with the byte length and
/// keccak256 of the tokenURI tools/render-token.mjs produces for it.
/// Token ${tokenId} on ${domain}.
library RenderFixture {
    struct Case {
        uint32 level;
        uint32 streak;
        uint32 lastDay;
        uint32 today;
        uint256 marks;
        bool resting;
        bool sunset;
        uint256 bytesLen;
        bytes32 hash;
        string label;
    }

    uint256 internal constant COUNT = ${all.length};

    function cases() internal pure returns (Case[] memory c) {
        c = new Case[](COUNT);
        uint256 i;
${lines}
    }
}
`;
}

const here = dirname(fileURLToPath(import.meta.url));

if (process.argv[1] && process.argv[1].endsWith("render-fixture.mjs")) {
  const [tokenId = "1", domain = "example.com"] = process.argv.slice(2);
  const all = fixtures(domain, Number(tokenId));
  const out = join(here, "..", "contracts", "test", "RenderFixture.sol");
  writeFileSync(out, render(all, domain, tokenId));
  const sizes = all.map(r => r.bytes);
  console.error(`${all.length} states, ${Math.min(...sizes)}-${Math.max(...sizes)} bytes`);
  console.error(`wrote ${out}`);
}
