// Generates contracts/script/SpikeBitmaps.sol -- the code bitmaps the deploy
// script mints with.
//
// Each token's code encodes its OWN url, so the bitmaps cannot be shared and
// cannot be invented: they have to come from the same generator the renderer
// tests use. Hard-coding them into the deploy script by hand would be four
// 344-character literals nobody could check; generating them keeps the script
// honest and matches how FrameGeometry.sol and HeartMask.sol are produced.
//
//   node tools/spike-bitmaps.mjs [domain]
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { tokenBitmap } from "./token-bitmap.mjs";
import { payloadFor } from "./qart.mjs";

/// The ids the deploy script mints, and why each one is there.
export const SPIKE_TOKENS = [
  { id: 1, note: "day one" },
  { id: 2, note: "level 200, a part-filled frame" },
  { id: 3, note: "whole, one year, every Mark but Singularity" },
  { id: 4, note: "level 364, the measured worst case" },
];

/// The state soak mints one token per state, so each keeps its OWN code and the
/// "decoded to its own url" check stays strict. Reusing one bitmap across the
/// soak would weaken that check to nothing.
export function soakTokens(count) {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    note: i < SPIKE_TOKENS.length ? SPIKE_TOKENS[i].note : `soak state ${i}`,
  }));
}

export function spikeBitmaps(domain, tokens = SPIKE_TOKENS) {
  return tokens.map(t => ({ ...t, ...tokenBitmap(domain, t.id), url: payloadFor(domain, t.id) }));
}

export function render(domain, rows) {
  const cases = rows.map(r => `
        // ${r.note} -- ${r.url} (mask ${r.mask}, heart match ${(r.match * 100).toFixed(1)}%)
        if (id == ${r.id}) {
            return hex"${r.hex.slice(0, 172)}"
                hex"${r.hex.slice(172)}";
        }`).join("\n");

  return `// SPDX-License-Identifier: MIT
// GENERATED by tools/spike-bitmaps.mjs -- do not edit by hand.
// Regenerate with: node tools/spike-bitmaps.mjs ${domain}
pragma solidity ^0.8.30;

/// @notice The code bitmaps the deploy script mints with, one per token id.
/// @dev Each token's code encodes its own URL, so these cannot be shared
/// between ids. Domain: ${domain}.
library SpikeBitmaps {
    /// @dev The packed 37x37 grid, 172 bytes, the width HeartMask expects.
    uint256 internal constant BYTES = ${rows[0].bytes};

    error NoBitmapFor(uint256 id);

    function code(uint256 id) internal pure returns (bytes memory) {${cases}
        revert NoBitmapFor(id);
    }
}
`;
}

const here = dirname(fileURLToPath(import.meta.url));

if (process.argv[1] && process.argv[1].endsWith("spike-bitmaps.mjs")) {
  const [domain = "example.com", countArg] = process.argv.slice(2);
  const count = Number(countArg ?? SPIKE_TOKENS.length);
  const rows = spikeBitmaps(domain, soakTokens(count));
  const out = join(here, "..", "contracts", "script", "SpikeBitmaps.sol");
  writeFileSync(out, render(domain, rows));
  for (const r of rows) {
    console.error(`token ${r.id} (${r.note}): mask ${r.mask}, match ${(r.match * 100).toFixed(1)}%`);
  }
  console.error(`wrote ${out}`);
}
